import 'package:clock/clock.dart';
import 'package:flutter/material.dart';
import 'package:butlery/models/recipe_unified.dart';
import 'package:butlery/models/tagging/tag_overrides.dart';
import 'package:butlery/services/tagging/tag_display_utils.dart';
import 'package:butlery/theme/app_text_styles.dart';
import 'package:butlery/theme/app_dimensions.dart';
import 'package:butlery/core/extensions/localization_extension.dart';

/// Dialog for viewing and managing all recipe tags.
///
/// Allows users to:
/// - View all effective tags (auto-generated + user-added)
/// - Remove tags they don't want
/// - Add custom tags
///
/// Returns the updated [TagOverrides] when saved, or null if cancelled.
class TagEditorDialog extends StatefulWidget {
  final Recipe recipe;

  const TagEditorDialog({
    super.key,
    required this.recipe,
  });

  /// Shows the tag editor dialog and returns updated overrides if saved.
  static Future<TagOverrides?> show(BuildContext context, Recipe recipe) {
    return showDialog<TagOverrides>(
      context: context,
      builder: (context) => TagEditorDialog(recipe: recipe),
    );
  }

  @override
  State<TagEditorDialog> createState() => _TagEditorDialogState();
}

class _TagEditorDialogState extends State<TagEditorDialog> {
  late Set<String> _addedTags;
  late Set<String> _removedTags;
  final _newTagController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  @override
  void initState() {
    super.initState();
    _addedTags = Set.from(widget.recipe.tagOverrides?.addedTags ?? {});
    _removedTags = Set.from(widget.recipe.tagOverrides?.removedTags ?? {});
  }

  @override
  void dispose() {
    _newTagController.dispose();
    super.dispose();
  }

  /// Auto-generated tags from the tagging system.
  Set<String> get _autoGeneratedTags => widget.recipe.tagResult?.tags ?? {};

  /// All effective tags currently visible.
  Set<String> get _effectiveTags {
    return _autoGeneratedTags.union(_addedTags).difference(_removedTags);
  }

  /// Checks if a tag is user-added.
  bool _isUserAdded(String tag) => _addedTags.contains(tag);

  void _removeTag(String tag) {
    setState(() {
      if (_addedTags.contains(tag)) {
        // User-added tag: just remove from addedTags
        _addedTags.remove(tag);
      } else {
        // Auto-generated tag: add to removedTags
        _removedTags.add(tag);
      }
    });
  }

  void _restoreTag(String tag) {
    setState(() {
      _removedTags.remove(tag);
    });
  }

  void _addNewTag() {
    if (!_formKey.currentState!.validate()) return;

    final newTag = _newTagController.text.trim().toLowerCase();
    if (newTag.isEmpty) return;

    // Don't add duplicates
    if (_effectiveTags.contains(newTag)) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(context.l10n.tagAlreadyExists)),
      );
      return;
    }

    setState(() {
      _addedTags.add(newTag);
      // If tag was in removedTags, restore it
      _removedTags.remove(newTag);
    });

    _newTagController.clear();
  }

  void _save() {
    final overrides = TagOverrides(
      addedTags: _addedTags,
      removedTags: _removedTags,
      allergenOverrides:
          widget.recipe.tagOverrides?.allergenOverrides ?? const {},
      dietaryOverrides:
          widget.recipe.tagOverrides?.dietaryOverrides ?? const {},
      lastEditedAt: clock.now(),
    );
    Navigator.of(context).pop(overrides);
  }

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final sortedTags = _effectiveTags.toList()..sort();
    final removedTagsList = _removedTags.toList()..sort();

    return Dialog(
      backgroundColor: cs.surfaceContainerHighest,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppDimensions.borderRadiusL),
      ),
      child: ConstrainedBox(
        constraints: const BoxConstraints(
          maxWidth: AppDimensions.dialogMaxHeightSmall,
          maxHeight: AppDimensions.dialogMaxHeightMedium,
        ),
        child: Padding(
          padding: const EdgeInsets.all(AppDimensions.paddingL),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                children: [
                  Icon(
                    Icons.local_offer_outlined,
                    color: cs.primary,
                    size: AppDimensions.iconSizeAction,
                  ),
                  const SizedBox(width: AppDimensions.spacingM),
                  Semantics(
                    header: true,
                    child: Text(
                      context.l10n.tagManageTags,
                      style: AppTextStyles.titleLarge,
                    ),
                  ),
                  const Spacer(),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () => Navigator.of(context).pop(),
                    tooltip: context.l10n.commonClose,
                  ),
                ],
              ),
              const Divider(height: AppDimensions.spacingXl),

              // Tags list
              Flexible(
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Active tags section
                      if (sortedTags.isNotEmpty) ...[
                        Semantics(
                          header: true,
                          child: Text(
                            context.l10n.tagActiveTags,
                            style: AppTextStyles.titleSmall,
                          ),
                        ),
                        const SizedBox(height: AppDimensions.spacingS),
                        Wrap(
                          spacing: AppDimensions.spacingS,
                          runSpacing: AppDimensions.spacingS,
                          children: sortedTags
                              .map((tag) => _buildTagChip(tag))
                              .toList(),
                        ),
                        const SizedBox(height: AppDimensions.spacingL),
                      ],

                      // Removed tags section (can be restored)
                      if (removedTagsList.isNotEmpty) ...[
                        Semantics(
                          header: true,
                          child: Text(
                            context.l10n.tagRemovedTags,
                            style: AppTextStyles.titleSmall.copyWith(
                              color: cs.onSurfaceVariant,
                            ),
                          ),
                        ),
                        const SizedBox(height: AppDimensions.spacingS),
                        Wrap(
                          spacing: AppDimensions.spacingS,
                          runSpacing: AppDimensions.spacingS,
                          children: removedTagsList
                              .map((tag) => _buildRemovedTagChip(tag))
                              .toList(),
                        ),
                        const SizedBox(height: AppDimensions.spacingL),
                      ],

                      // Add new tag
                      Semantics(
                        header: true,
                        child: Text(
                          context.l10n.tagAddNewTag,
                          style: AppTextStyles.titleSmall,
                        ),
                      ),
                      const SizedBox(height: AppDimensions.spacingS),
                      Form(
                        key: _formKey,
                        child: Row(
                          children: [
                            Expanded(
                              child: TextFormField(
                                controller: _newTagController,
                                decoration: InputDecoration(
                                  labelText: context.l10n.tagAddNewTag,
                                  hintText: context.l10n.tagWriteTagHint,
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(
                                      AppDimensions.borderRadiusM,
                                    ),
                                  ),
                                  contentPadding: const EdgeInsets.symmetric(
                                    horizontal: AppDimensions.paddingM,
                                    vertical: AppDimensions.paddingS,
                                  ),
                                ),
                                validator: (value) {
                                  if (value == null || value.trim().isEmpty) {
                                    return context.l10n.tagEnterTag;
                                  }
                                  if (value.trim().length < 2) {
                                    return context.l10n.tagMinTwoChars;
                                  }
                                  return null;
                                },
                                onFieldSubmitted: (_) => _addNewTag(),
                              ),
                            ),
                            const SizedBox(width: AppDimensions.spacingS),
                            IconButton.filled(
                              onPressed: _addNewTag,
                              icon: const Icon(Icons.add),
                              tooltip: context.l10n.tagAddTag,
                              style: IconButton.styleFrom(
                                backgroundColor: cs.primary,
                                foregroundColor: cs.onPrimary,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              const SizedBox(height: AppDimensions.spacingL),
              const Divider(),
              const SizedBox(height: AppDimensions.spacingM),

              // Actions
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: Text(context.l10n.commonCancel),
                  ),
                  const SizedBox(width: AppDimensions.spacingM),
                  FilledButton(
                    onPressed: _save,
                    child: Text(context.l10n.commonSave),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTagChip(String tag) {
    final cs = Theme.of(context).colorScheme;
    final isUserAdded = _isUserAdded(tag);
    final displayName = TagDisplayUtils.getDisplayName(tag);

    return InputChip(
      label: Text(displayName),
      labelStyle: AppTextStyles.bodySmall.copyWith(
        color: isUserAdded ? cs.primary : cs.onSurface,
        fontWeight: isUserAdded ? FontWeight.w600 : FontWeight.normal,
      ),
      backgroundColor: isUserAdded
          ? cs.primary.withValues(alpha: AppDimensions.opacityVeryLight)
          : cs.surface,
      side: BorderSide(
        color: isUserAdded
            ? cs.primary.withValues(alpha: AppDimensions.opacityMediumLight)
            : cs.outlineVariant,
      ),
      deleteIcon: const Icon(Icons.close, size: AppDimensions.iconSize18),
      deleteIconColor: cs.onSurfaceVariant,
      onDeleted: () => _removeTag(tag),
      avatar: isUserAdded
          ? Icon(Icons.person, size: AppDimensions.iconSizeS, color: cs.primary)
          : null,
      tooltip: isUserAdded
          ? context.l10n.tagManuallyAdded
          : context.l10n.tagAutoGenerated,
    );
  }

  Widget _buildRemovedTagChip(String tag) {
    final cs = Theme.of(context).colorScheme;
    final displayName = TagDisplayUtils.getDisplayName(tag);

    return ActionChip(
      label: Text(displayName),
      labelStyle: AppTextStyles.bodySmall.copyWith(
        color: cs.onSurfaceVariant,
        decoration: TextDecoration.lineThrough,
      ),
      backgroundColor: cs.surface.withValues(alpha: AppDimensions.opacityHalf),
      side: BorderSide(
        color: cs.outlineVariant.withValues(alpha: AppDimensions.opacityHalf),
      ),
      avatar: Icon(
        Icons.undo,
        size: AppDimensions.iconSizeS,
        color: cs.onSurfaceVariant,
      ),
      onPressed: () => _restoreTag(tag),
      tooltip: context.l10n.tagClickToRestore,
    );
  }
}
