import 'package:flutter/material.dart';
import 'package:butlery/models/recipe_unified.dart';
import 'package:butlery/models/tagging/tag_overrides.dart';
import 'package:butlery/services/tagging/tag_display_utils.dart';
import 'package:butlery/theme/app_colors.dart';
import 'package:butlery/theme/app_text_styles.dart';
import 'package:butlery/theme/app_dimensions.dart';

/// Dialog for viewing and managing all recipe tags.
///
/// Allows users to:
/// - View all effective tags (auto-generated + user-added)
/// - Remove tags they don't want
/// - Add custom tags
///
/// Returns the updated [TagOverrides] when saved, or null if cancelled.
class TagEditorDialog extends StatefulWidget {
  final Recipe recipe;

  const TagEditorDialog({
    super.key,
    required this.recipe,
  });

  /// Shows the tag editor dialog and returns updated overrides if saved.
  static Future<TagOverrides?> show(BuildContext context, Recipe recipe) {
    return showDialog<TagOverrides>(
      context: context,
      builder: (context) => TagEditorDialog(recipe: recipe),
    );
  }

  @override
  State<TagEditorDialog> createState() => _TagEditorDialogState();
}

class _TagEditorDialogState extends State<TagEditorDialog> {
  late Set<String> _addedTags;
  late Set<String> _removedTags;
  final _newTagController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  @override
  void initState() {
    super.initState();
    _addedTags = Set.from(widget.recipe.tagOverrides?.addedTags ?? {});
    _removedTags = Set.from(widget.recipe.tagOverrides?.removedTags ?? {});
  }

  @override
  void dispose() {
    _newTagController.dispose();
    super.dispose();
  }

  /// Auto-generated tags from the tagging system.
  Set<String> get _autoGeneratedTags => widget.recipe.tagResult?.tags ?? {};

  /// All effective tags currently visible.
  Set<String> get _effectiveTags {
    return _autoGeneratedTags.union(_addedTags).difference(_removedTags);
  }

  /// Checks if a tag is user-added.
  bool _isUserAdded(String tag) => _addedTags.contains(tag);

  void _removeTag(String tag) {
    setState(() {
      if (_addedTags.contains(tag)) {
        // User-added tag: just remove from addedTags
        _addedTags.remove(tag);
      } else {
        // Auto-generated tag: add to removedTags
        _removedTags.add(tag);
      }
    });
  }

  void _restoreTag(String tag) {
    setState(() {
      _removedTags.remove(tag);
    });
  }

  void _addNewTag() {
    if (!_formKey.currentState!.validate()) return;

    final newTag = _newTagController.text.trim().toLowerCase();
    if (newTag.isEmpty) return;

    // Don't add duplicates
    if (_effectiveTags.contains(newTag)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Taggen finns redan')),
      );
      return;
    }

    setState(() {
      _addedTags.add(newTag);
      // If tag was in removedTags, restore it
      _removedTags.remove(newTag);
    });

    _newTagController.clear();
  }

  void _save() {
    final overrides = TagOverrides(
      addedTags: _addedTags,
      removedTags: _removedTags,
      allergenOverrides:
          widget.recipe.tagOverrides?.allergenOverrides ?? const {},
      dietaryOverrides:
          widget.recipe.tagOverrides?.dietaryOverrides ?? const {},
      lastEditedAt: DateTime.now(),
    );
    Navigator.of(context).pop(overrides);
  }

  @override
  Widget build(BuildContext context) {
    final sortedTags = _effectiveTags.toList()..sort();
    final removedTagsList = _removedTags.toList()..sort();

    return Dialog(
      backgroundColor: AppColors.cardWhite,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppDimensions.borderRadiusL),
      ),
      child: ConstrainedBox(
        constraints: const BoxConstraints(
            maxWidth: AppDimensions.dialogMaxHeightSmall,
            maxHeight: AppDimensions.dialogMaxHeightMedium),
        child: Padding(
          padding: const EdgeInsets.all(AppDimensions.paddingL),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                children: [
                  const Icon(
                    Icons.local_offer_outlined,
                    color: AppColors.forestGreen,
                    size: AppDimensions.iconSizeAction,
                  ),
                  const SizedBox(width: AppDimensions.spacingM),
                  Text(
                    'Hantera taggar',
                    style: AppTextStyles.titleLarge,
                  ),
                  const Spacer(),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () => Navigator.of(context).pop(),
                  ),
                ],
              ),
              const Divider(height: AppDimensions.spacingXl),

              // Tags list
              Flexible(
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Active tags section
                      if (sortedTags.isNotEmpty) ...[
                        Text(
                          'Aktiva taggar',
                          style: AppTextStyles.titleSmall,
                        ),
                        const SizedBox(height: AppDimensions.spacingS),
                        Wrap(
                          spacing: AppDimensions.spacingS,
                          runSpacing: AppDimensions.spacingS,
                          children: sortedTags
                              .map((tag) => _buildTagChip(tag))
                              .toList(),
                        ),
                        const SizedBox(height: AppDimensions.spacingL),
                      ],

                      // Removed tags section (can be restored)
                      if (removedTagsList.isNotEmpty) ...[
                        Text(
                          'Borttagna taggar',
                          style: AppTextStyles.titleSmall.copyWith(
                            color: AppColors.textMedium,
                          ),
                        ),
                        const SizedBox(height: AppDimensions.spacingS),
                        Wrap(
                          spacing: AppDimensions.spacingS,
                          runSpacing: AppDimensions.spacingS,
                          children: removedTagsList
                              .map((tag) => _buildRemovedTagChip(tag))
                              .toList(),
                        ),
                        const SizedBox(height: AppDimensions.spacingL),
                      ],

                      // Add new tag
                      Text(
                        'Lägg till ny tagg',
                        style: AppTextStyles.titleSmall,
                      ),
                      const SizedBox(height: AppDimensions.spacingS),
                      Form(
                        key: _formKey,
                        child: Row(
                          children: [
                            Expanded(
                              child: TextFormField(
                                controller: _newTagController,
                                decoration: InputDecoration(
                                  hintText: 'Skriv en tagg...',
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(
                                        AppDimensions.borderRadiusM),
                                  ),
                                  contentPadding: const EdgeInsets.symmetric(
                                    horizontal: AppDimensions.paddingM,
                                    vertical: AppDimensions.paddingS,
                                  ),
                                ),
                                validator: (value) {
                                  if (value == null || value.trim().isEmpty) {
                                    return 'Ange en tagg';
                                  }
                                  if (value.trim().length < 2) {
                                    return 'Minst 2 tecken';
                                  }
                                  return null;
                                },
                                onFieldSubmitted: (_) => _addNewTag(),
                              ),
                            ),
                            const SizedBox(width: AppDimensions.spacingS),
                            IconButton.filled(
                              onPressed: _addNewTag,
                              icon: const Icon(Icons.add),
                              style: IconButton.styleFrom(
                                backgroundColor: AppColors.forestGreen,
                                foregroundColor: AppColors.cardWhite,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              const SizedBox(height: AppDimensions.spacingL),
              const Divider(),
              const SizedBox(height: AppDimensions.spacingM),

              // Actions
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Avbryt'),
                  ),
                  const SizedBox(width: AppDimensions.spacingM),
                  FilledButton(
                    onPressed: _save,
                    child: const Text('Spara'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTagChip(String tag) {
    final isUserAdded = _isUserAdded(tag);
    final displayName = TagDisplayUtils.getDisplayName(tag);

    return InputChip(
      label: Text(displayName),
      labelStyle: AppTextStyles.bodySmall.copyWith(
        color: isUserAdded ? AppColors.forestGreen : AppColors.textDark,
        fontWeight: isUserAdded ? FontWeight.w600 : FontWeight.normal,
      ),
      backgroundColor: isUserAdded
          ? AppColors.forestGreen
              .withValues(alpha: AppDimensions.opacityVeryLight)
          : AppColors.cream,
      side: BorderSide(
        color: isUserAdded
            ? AppColors.forestGreen
                .withValues(alpha: AppDimensions.opacityMediumLight)
            : AppColors.divider,
      ),
      deleteIcon: const Icon(Icons.close, size: AppDimensions.iconSize18),
      deleteIconColor: AppColors.textMedium,
      onDeleted: () => _removeTag(tag),
      avatar: isUserAdded
          ? const Icon(Icons.person,
              size: AppDimensions.iconSizeS, color: AppColors.forestGreen)
          : null,
      tooltip: isUserAdded ? 'Manuellt tillagd' : 'Automatiskt genererad',
    );
  }

  Widget _buildRemovedTagChip(String tag) {
    final displayName = TagDisplayUtils.getDisplayName(tag);

    return ActionChip(
      label: Text(displayName),
      labelStyle: AppTextStyles.bodySmall.copyWith(
        color: AppColors.textMedium,
        decoration: TextDecoration.lineThrough,
      ),
      backgroundColor:
          AppColors.cream.withValues(alpha: AppDimensions.opacityHalf),
      side: BorderSide(
          color:
              AppColors.divider.withValues(alpha: AppDimensions.opacityHalf)),
      avatar: const Icon(Icons.undo,
          size: AppDimensions.iconSizeS, color: AppColors.textMedium),
      onPressed: () => _restoreTag(tag),
      tooltip: 'Klicka för att återställa',
    );
  }
}
