/// YouTube video import strategy for recipe extraction.
///
/// Handles YouTube recipe video imports by:
/// 1. Extracting video ID from URL
/// 2. Fetching video metadata (title, thumbnail)
/// 3. Fetching video transcript
/// 4. Sending transcript to LLM for recipe extraction
/// 5. Falling back to user-assisted import if needed
library;

import 'package:butlery/core/l10n/app_locale.dart';
import 'package:butlery/core/utils/logger.dart';
import 'package:butlery/services/import/import_strategy.dart';
import 'package:butlery/services/import/llm/llm_enhancement_service.dart';
import 'package:butlery/services/import/models/import_result_v2.dart';
import 'package:butlery/services/import/youtube/youtube_transcript_service.dart';

/// Import strategy for YouTube recipe videos.
///
/// Tier structure:
/// 1. Fetch transcript + LLM extraction (requires LLM, paid)
/// 2. User-assisted import with transcript (free fallback)
/// 3. Failure with manual screenshot option (no transcript available)
class YouTubeImportStrategy extends ImportStrategy with ImportValidationMixin {
  @override
  String get strategyName => 'youtube';

  @override
  String get description =>
      'Importera recept från YouTube-videor genom att analysera undertextningen';

  @override
  String get inputExample => 'https://www.youtube.com/watch?v=VIDEO_ID';

  final YouTubeTranscriptService _transcriptService;
  final LlmEnhancementService _llmService;

  YouTubeImportStrategy({
    required YouTubeTranscriptService transcriptService,
    required LlmEnhancementService llmService,
  })  : _transcriptService = transcriptService,
        _llmService = llmService;

  @override
  bool canHandle(String input) {
    return _transcriptService.isYouTubeUrl(input);
  }

  @override
  bool validateInput(String input) {
    return _transcriptService.extractVideoId(input) != null;
  }

  @override
  Future<ImportResult> import(
    String input, {
    Map<String, dynamic>? options,
  }) async {
    // Use the V2 import method and convert result
    final resultV2 = await importV2(input, options: options);
    return _convertToLegacyResult(resultV2);
  }

  /// Import using the new V2 result types.
  Future<ImportResultV2> importV2(
    String input, {
    Map<String, dynamic>? options,
  }) async {
    AppLogger.info('YouTubeImportStrategy: Starting import for $input');

    final videoId = _transcriptService.extractVideoId(input);
    if (videoId == null) {
      return ImportFailure(
        message: AppLocale.current.errorInvalidYoutubeUrl,
        errorCode: ImportErrorCode.invalidUrl,
        pipeline: 'youtube',
        tier: 0,
      );
    }

    // Fetch metadata first (for title and thumbnail)
    final metadata = await _transcriptService.fetchVideoMetadata(videoId);
    if (metadata == null) {
      AppLogger.warning(
        'YouTubeImportStrategy: Failed to fetch metadata for $videoId',
      );
    }

    // Tier 1: Fetch transcript and use LLM
    final transcriptResult = await _transcriptService.fetchTranscript(videoId);

    if (!transcriptResult.isSuccess || transcriptResult.isEmpty) {
      AppLogger.warning(
        'YouTubeImportStrategy: No transcript available - ${transcriptResult.error}',
      );

      // Tier 3: No transcript, request screenshot
      return ImportNeedsScreenshot(
        platform: 'YouTube',
        url: metadata?.watchUrl ?? 'https://www.youtube.com/watch?v=$videoId',
        thumbnailUrl: metadata?.hqThumbnailUrl,
        message: 'Videon saknar undertexter. Ta en skärmbild av receptet.',
      );
    }

    AppLogger.info(
      'YouTubeImportStrategy: Got transcript (${transcriptResult.transcript!.length} chars, '
      'lang: ${transcriptResult.language}, auto: ${transcriptResult.isAutoGenerated})',
    );

    // Tier 1: Try LLM extraction
    final llmResult = await _llmService.extractFromTranscript(
      transcriptResult.transcript!,
      metadata?.watchUrl ?? 'https://www.youtube.com/watch?v=$videoId',
      videoTitle: metadata?.title,
    );

    if (llmResult.isSuccess) {
      // Add YouTube-specific metadata
      final success = llmResult as ImportSuccess;
      // BUT-980: persist the YouTube watch URL on the recipe so the detail
      // view can offer a "View original" link back to the source video.
      // The LLM extracts the recipe from the transcript and doesn't know
      // where that transcript came from — has to be wired in here.
      final videoUrl =
          metadata?.watchUrl ?? 'https://www.youtube.com/watch?v=$videoId';
      return ImportSuccess(
        recipe: success.recipe.copyWith(sourceUrl: videoUrl),
        confidence: success.confidence,
        pipeline: 'youtube',
        tier: 1,
        method: 'transcript-llm',
        usedLlm: true,
        requiresReview: true,
        metadata: {
          ...?success.metadata,
          'videoId': videoId,
          'videoTitle': metadata?.title,
          'channelName': metadata?.channelName,
          'thumbnailUrl': metadata?.hqThumbnailUrl,
          'transcriptLanguage': transcriptResult.language,
          'transcriptAutoGenerated': transcriptResult.isAutoGenerated,
        },
      );
    }

    // Check if we got a rate limit failure
    if (llmResult is ImportFailure &&
        llmResult.errorCode == ImportErrorCode.rateLimited) {
      // Tier 2: Fall back to user-assisted with transcript
      return ImportNeedsAssistance(
        extractedText: transcriptResult.transcript!,
        suggestedTitle: metadata?.title,
        thumbnailUrl: metadata?.hqThumbnailUrl,
        message: 'AI-kvoten är slut. Markera receptdelar manuellt.',
        partialData: {
          'videoId': videoId,
          'sourceUrl': metadata?.watchUrl,
        },
      );
    }

    // If LLM failed but not due to rate limit, still offer user-assisted
    if (llmResult is ImportNeedsAssistance) {
      return ImportNeedsAssistance(
        extractedText: llmResult.extractedText,
        suggestedTitle: metadata?.title ?? llmResult.suggestedTitle,
        thumbnailUrl: metadata?.hqThumbnailUrl ?? llmResult.thumbnailUrl,
        message: llmResult.message,
        partialData: {
          'videoId': videoId,
          'sourceUrl': metadata?.watchUrl,
          ...?llmResult.partialData,
        },
      );
    }

    // Tier 2: User-assisted fallback
    return ImportNeedsAssistance(
      extractedText: transcriptResult.transcript!,
      suggestedTitle: metadata?.title,
      thumbnailUrl: metadata?.hqThumbnailUrl,
      message:
          'AI kunde inte extrahera receptet. Markera receptdelar manuellt.',
      partialData: {
        'videoId': videoId,
        'sourceUrl': metadata?.watchUrl,
      },
    );
  }

  /// Convert V2 result to legacy ImportResult for compatibility.
  ImportResult _convertToLegacyResult(ImportResultV2 resultV2) {
    return switch (resultV2) {
      final ImportSuccess success => ImportResult.success(
          success.recipe,
          metadata: {
            'pipeline': success.pipeline,
            'tier': success.tier,
            'method': success.method,
            'usedLlm': success.usedLlm,
            ...?success.metadata,
          },
        ),
      final ImportNeedsAssistance assistance => ImportResult.assistance(
          extractedText: assistance.extractedText,
          suggestedTitle: assistance.suggestedTitle,
          metadata: assistance.partialData,
        ),
      final ImportNeedsScreenshot screenshot => ImportResult.failure(
          screenshot.message,
          metadata: {
            'platform': screenshot.platform,
            'url': screenshot.url,
            'thumbnailUrl': screenshot.thumbnailUrl,
            'needsScreenshot': true,
          },
        ),
      final ImportPartial partial => ImportResult.assistance(
          extractedText: partial.extractedText ?? '',
          suggestedTitle: partial.title,
          metadata: partial.partialData,
        ),
      final ImportFailure failure => ImportResult.failure(
          failure.message,
          metadata: {
            'errorCode': failure.errorCode.name,
            'pipeline': failure.pipeline,
            'tier': failure.tier,
          },
        ),
    };
  }
}
