/// Models for YouTube video import functionality.
///
/// Contains data classes for transcript results and video metadata
/// used during YouTube recipe video import.
library;

/// Result of fetching a transcript from a YouTube video.
class TranscriptResult {
  /// The transcript text, or null if not available.
  final String? transcript;

  /// Language code of the transcript (e.g., 'sv', 'en').
  final String? language;

  /// Whether the transcript was auto-generated by YouTube.
  final bool isAutoGenerated;

  /// Error message if transcript fetch failed.
  final String? error;

  /// Whether the transcript was successfully fetched.
  bool get isSuccess => transcript != null && error == null;

  /// Whether the transcript is empty or not available.
  bool get isEmpty => transcript == null || transcript!.trim().isEmpty;

  const TranscriptResult({
    this.transcript,
    this.language,
    this.isAutoGenerated = false,
    this.error,
  });

  /// Create a successful result with transcript.
  factory TranscriptResult.success({
    required String transcript,
    String? language,
    bool isAutoGenerated = false,
  }) {
    return TranscriptResult(
      transcript: transcript,
      language: language,
      isAutoGenerated: isAutoGenerated,
    );
  }

  /// Create a failure result with error message.
  factory TranscriptResult.failure(String error) {
    return TranscriptResult(error: error);
  }

  @override
  String toString() {
    if (isSuccess) {
      return 'TranscriptResult(success, ${transcript!.length} chars, '
          'lang: $language, auto: $isAutoGenerated)';
    }
    return 'TranscriptResult(failure: $error)';
  }
}

/// Metadata for a YouTube video.
class VideoMetadata {
  /// The YouTube video ID (11 characters).
  final String videoId;

  /// Video title.
  final String title;

  /// Video description, if available.
  final String? description;

  /// URL of the video thumbnail.
  final String? thumbnailUrl;

  /// Name of the channel that uploaded the video.
  final String? channelName;

  /// Duration of the video.
  final Duration? duration;

  /// Original URL used to fetch this video.
  final String? sourceUrl;

  const VideoMetadata({
    required this.videoId,
    required this.title,
    this.description,
    this.thumbnailUrl,
    this.channelName,
    this.duration,
    this.sourceUrl,
  });

  /// Get the standard YouTube watch URL.
  String get watchUrl => 'https://www.youtube.com/watch?v=$videoId';

  /// Get the high-quality thumbnail URL.
  String get hqThumbnailUrl =>
      'https://img.youtube.com/vi/$videoId/hqdefault.jpg';

  /// Get the maximum resolution thumbnail URL.
  String get maxresThumbnailUrl =>
      'https://img.youtube.com/vi/$videoId/maxresdefault.jpg';

  @override
  String toString() {
    return 'VideoMetadata(id: $videoId, title: $title, channel: $channelName)';
  }
}

/// Available caption track from a YouTube video.
class CaptionTrack {
  /// URL to fetch the caption/transcript.
  final String baseUrl;

  /// Language code (e.g., 'sv', 'en').
  final String languageCode;

  /// Human-readable language name.
  final String languageName;

  /// Whether this is an auto-generated caption.
  final bool isAutoGenerated;

  /// Whether this is a translation.
  final bool isTranslatable;

  const CaptionTrack({
    required this.baseUrl,
    required this.languageCode,
    required this.languageName,
    this.isAutoGenerated = false,
    this.isTranslatable = false,
  });

  @override
  String toString() {
    return 'CaptionTrack($languageCode, auto: $isAutoGenerated)';
  }
}
