#!/usr/bin/env bash
# PreCompact hook: Captures session state before context compaction.
# Writes a checkpoint to memory/current-state.md so the post-compaction
# session can pick up where it left off.

set -euo pipefail

PROJECT_DIR="/home/user/butlery"
MEMORY_DIR="/root/.claude/projects/-home-user-butlery/memory"
CHECKPOINT_FILE="$MEMORY_DIR/current-state.md"

cd "$PROJECT_DIR"

# Gather git state
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
MODIFIED_FILES=$(git diff --name-only 2>/dev/null | head -20)
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null | head -20)
UNTRACKED_FILES=$(git ls-files --others --exclude-standard 2>/dev/null | head -10)
RECENT_COMMITS=$(git log --oneline -10 2>/dev/null || echo "none")

# Gather todo/plan state
TODO_STATE=""
if [ -f "$PROJECT_DIR/tasks/todo.md" ]; then
  TODO_STATE=$(head -100 "$PROJECT_DIR/tasks/todo.md")
else
  # No todo.md means either no plan mode was active, or TodoWrite was used
  # without syncing to disk. Git state below will provide context.
  TODO_STATE="No /tasks/todo.md found. Check git diff and modified files for active work context."
fi

# Gather lessons if they exist
RECENT_LESSONS=""
if [ -f "$PROJECT_DIR/tasks/lessons.md" ]; then
  RECENT_LESSONS=$(tail -30 "$PROJECT_DIR/tasks/lessons.md")
fi

# Write checkpoint
cat > "$CHECKPOINT_FILE" << CHECKPOINT
# Current Session State

> Auto-generated by PreCompact hook at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
> This is PRESCRIPTIVE: tells you what to do, not what was discussed.

## Branch
\`$BRANCH\`

## Modified Files (unstaged)
\`\`\`
${MODIFIED_FILES:-none}
\`\`\`

## Staged Files
\`\`\`
${STAGED_FILES:-none}
\`\`\`

## Untracked Files
\`\`\`
${UNTRACKED_FILES:-none}
\`\`\`

## Recent Commits (this session)
\`\`\`
$RECENT_COMMITS
\`\`\`

## Todo State
${TODO_STATE:-No active todo.md found.}

## Recent Lessons
${RECENT_LESSONS:-No recent lessons.}
CHECKPOINT

exit 0
