#!/usr/bin/env bash
# PreCompact hook: Captures session state before context compaction.
# Writes a checkpoint to memory/current-state.md so the post-compaction
# session can pick up where it left off.

set -euo pipefail

# Cross-platform Python detection
PYTHON=$(command -v python3 2>/dev/null || command -v python 2>/dev/null || echo "python3")

# Use CLAUDE_PROJECT_DIR (provided by Claude Code) or detect via git
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

# Derive memory dir: ~/.claude/projects/<encoded-path>/memory
# Path encoding: normalize to forward slashes, handle git-bash /c/ -> C:, replace :/ with -
MEMORY_DIR=$($PYTHON -c "
import os, re, sys
p = sys.argv[1].replace(os.sep, '/')
# Git Bash /c/... -> C:/...
if len(p) > 2 and p[0] == '/' and p[2] == '/':
    p = p[1].upper() + ':' + p[2:]
encoded = re.sub(r'[:/]', '-', p)
home = os.path.expanduser('~').replace(os.sep, '/')
print(home + '/.claude/projects/' + encoded + '/memory')
" "$PROJECT_DIR")

CHECKPOINT_FILE="$MEMORY_DIR/current-state.md"

# Ensure memory dir exists
mkdir -p "$MEMORY_DIR"

cd "$PROJECT_DIR"

# Gather git state
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
MODIFIED_FILES=$(git diff --name-only 2>/dev/null | head -20)
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null | head -20)
UNTRACKED_FILES=$(git ls-files --others --exclude-standard 2>/dev/null | head -10)
RECENT_COMMITS=$(git log --oneline -10 2>/dev/null || echo "none")

# Gather task state from Claude Code's persistent todos and /tasks/todo.md
TASK_STATE=""

# Read Claude Code's persistent task files
TASK_STATE=$($PYTHON -c "
import json, os, glob

search_dirs = [
    os.path.expanduser('~/.claude/todos'),
    os.path.join('$PROJECT_DIR', '.claude', 'tasks'),
]

for todo_dir in search_dirs:
    if not os.path.isdir(todo_dir):
        continue
    files = sorted(glob.glob(os.path.join(todo_dir, '*.json')), key=os.path.getmtime, reverse=True)
    for f in files:
        try:
            with open(f) as fh:
                todos = json.load(fh)
            if not todos:
                continue
            icons = {'completed': '[x]', 'in_progress': '[>]', 'pending': '[ ]'}
            for t in todos:
                icon = icons.get(t.get('status', 'pending'), '[ ]')
                print(f\"{icon} {t.get('content', 'unknown')}\")
            exit(0)
        except (json.JSONDecodeError, IOError):
            continue
" 2>/dev/null || true)

# Also check /tasks/todo.md for plan-mode plans
if [ -f "$PROJECT_DIR/tasks/todo.md" ]; then
  PLAN_STATE=$(head -100 "$PROJECT_DIR/tasks/todo.md")
  TASK_STATE="${TASK_STATE:+$TASK_STATE
}### Plan (/tasks/todo.md)
${PLAN_STATE}"
fi

if [ -z "$TASK_STATE" ]; then
  TASK_STATE="No active tasks found. Check git diff and modified files for work context."
fi

# Gather lessons if they exist
RECENT_LESSONS=""
if [ -f "$PROJECT_DIR/tasks/lessons.md" ]; then
  RECENT_LESSONS=$(tail -30 "$PROJECT_DIR/tasks/lessons.md")
fi

# Write checkpoint
cat > "$CHECKPOINT_FILE" << CHECKPOINT
# Current Session State

> Auto-generated by PreCompact hook at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
> This is PRESCRIPTIVE: tells you what to do, not what was discussed.

## Branch
\`$BRANCH\`

## Modified Files (unstaged)
\`\`\`
${MODIFIED_FILES:-none}
\`\`\`

## Staged Files
\`\`\`
${STAGED_FILES:-none}
\`\`\`

## Untracked Files
\`\`\`
${UNTRACKED_FILES:-none}
\`\`\`

## Recent Commits (this session)
\`\`\`
$RECENT_COMMITS
\`\`\`

## Active Tasks
${TASK_STATE}

## Recent Lessons
${RECENT_LESSONS:-No recent lessons.}
CHECKPOINT

exit 0
