#!/usr/bin/env bash
# PreCompact hook: Captures session state before context compaction.
# Writes a checkpoint to memory/current-state.md so the post-compaction
# session can pick up where it left off.

set -euo pipefail

PROJECT_DIR="/home/user/butlery"
MEMORY_DIR="/root/.claude/projects/-home-user-butlery/memory"
CHECKPOINT_FILE="$MEMORY_DIR/current-state.md"

cd "$PROJECT_DIR"

# Gather git state
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
MODIFIED_FILES=$(git diff --name-only 2>/dev/null | head -20)
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null | head -20)
UNTRACKED_FILES=$(git ls-files --others --exclude-standard 2>/dev/null | head -10)
RECENT_COMMITS=$(git log --oneline -10 2>/dev/null || echo "none")

# Gather task state from Claude Code's persistent todos (~/.claude/todos/)
# and from /tasks/todo.md (plan-mode plans).
TASK_STATE=""

# Read Claude Code's persistent task files
# Check all known locations: ~/.claude/todos/ (v2.1.x), .claude/tasks/ (newer)
TASK_STATE=$(python3 -c "
import json, os, glob

search_dirs = [
    os.path.expanduser('~/.claude/todos'),
    os.path.join('$PROJECT_DIR', '.claude', 'tasks'),
]

for todo_dir in search_dirs:
    if not os.path.isdir(todo_dir):
        continue
    files = sorted(glob.glob(os.path.join(todo_dir, '*.json')), key=os.path.getmtime, reverse=True)
    for f in files:
        try:
            with open(f) as fh:
                todos = json.load(fh)
            if not todos:
                continue
            icons = {'completed': '[x]', 'in_progress': '[>]', 'pending': '[ ]'}
            for t in todos:
                icon = icons.get(t.get('status', 'pending'), '[ ]')
                print(f\"{icon} {t.get('content', 'unknown')}\")
            exit(0)  # Found active tasks, done
        except (json.JSONDecodeError, IOError):
            continue
" 2>/dev/null || true)

# Also check /tasks/todo.md for plan-mode plans
if [ -f "$PROJECT_DIR/tasks/todo.md" ]; then
  PLAN_STATE=$(head -100 "$PROJECT_DIR/tasks/todo.md")
  TASK_STATE="${TASK_STATE:+$TASK_STATE
}### Plan (/tasks/todo.md)
${PLAN_STATE}"
fi

if [ -z "$TASK_STATE" ]; then
  TASK_STATE="No active tasks found. Check git diff and modified files for work context."
fi

# Gather lessons if they exist
RECENT_LESSONS=""
if [ -f "$PROJECT_DIR/tasks/lessons.md" ]; then
  RECENT_LESSONS=$(tail -30 "$PROJECT_DIR/tasks/lessons.md")
fi

# Write checkpoint
cat > "$CHECKPOINT_FILE" << CHECKPOINT
# Current Session State

> Auto-generated by PreCompact hook at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
> This is PRESCRIPTIVE: tells you what to do, not what was discussed.

## Branch
\`$BRANCH\`

## Modified Files (unstaged)
\`\`\`
${MODIFIED_FILES:-none}
\`\`\`

## Staged Files
\`\`\`
${STAGED_FILES:-none}
\`\`\`

## Untracked Files
\`\`\`
${UNTRACKED_FILES:-none}
\`\`\`

## Recent Commits (this session)
\`\`\`
$RECENT_COMMITS
\`\`\`

## Active Tasks
${TASK_STATE}

## Recent Lessons
${RECENT_LESSONS:-No recent lessons.}
CHECKPOINT

exit 0
