/// The Butlery icon family, drawn from the design system's own SVG masters.
///
/// Source of authority:
/// - beslutslogg.md:9 (B-02): all iconography is Butlery's own family, no
///   icon library.
/// - Grafisk manual v6:308 and :322: 24 grid, stroke 1.75 from 15 px up and
///   2.2 at 14 px and below, round caps and joins, `currentColor`, the nav
///   family on a 160 grid with stroke 7.
/// - icons.json `contract` (copied byte-identical to assets/icons/icons.json):
///   the SVG contract per family and the filled exceptions.
/// - plattformsmatris.md:75: the icon family is identical on both platforms.
///
/// The masters live in assets/icons/*.svg. `ButleryIcons` (generated by
/// tools/generate_butlery_icons.dart) embeds each master's exact text so a
/// glyph paints synchronously, with no asset load and no extra package.
library;

import 'package:flutter/widgets.dart';
import 'package:xml/xml.dart';

/// Font family name carried by every [ButleryGlyph]. No font by this name is
/// bundled: a [ButleryGlyph] is painted by [ButleryIcon], never by a font.
const String kButleryGlyphFontFamily = 'ButleryIcons';

/// One glyph of the Butlery icon family.
///
/// It is an [IconData] so it flows through every API that takes an icon
/// (widget parameters, `find.byIcon`), but it must be rendered through
/// [ButleryIcon]; a plain [Icon] has no font for it.
@immutable
class ButleryGlyph extends IconData {
  /// Creates a glyph. Only the generated `ButleryIcons` register calls this.
  const ButleryGlyph(
    super.codePoint, {
    required this.name,
    required this.meaning,
    required this.svg,
    this.outlined = false,
  }) : super(fontFamily: kButleryGlyphFontFamily);

  /// The icons.json key, e.g. `arrow-left`.
  final String name;

  /// The icons.json meaning, e.g. `Tillbaka`.
  final String meaning;

  /// The exact text of the master `assets/icons/<name>.svg`.
  final String svg;

  /// Paint a filled master as a 1.75 stroke outline (the off state of
  /// `heart` and `star`, drawn that way in Skarmar v12 del 1:311).
  final bool outlined;

  @override
  String toString() => 'ButleryGlyph($name${outlined ? ', outlined' : ''})';
}

/// Renders an icon. A [ButleryGlyph] is painted from its SVG master; any
/// other [IconData] (the Material residue listed in
/// test/architecture/icon_census_test.dart) falls back to [Icon].
///
/// Colour, size, opacity and text scaling come from the ambient [IconTheme]
/// exactly as for [Icon], so every colour follows the theme in light and
/// dark mode. Semantics match [Icon]: the label is announced when given,
/// otherwise the glyph is excluded from the semantics tree.
class ButleryIcon extends Icon {
  /// Creates an icon.
  const ButleryIcon(
    super.icon, {
    super.key,
    super.size,
    super.color,
    super.semanticLabel,
    super.textDirection,
    super.applyTextScaling,
    super.shadows,
  });

  @override
  Widget build(BuildContext context) {
    final glyph = icon;
    if (glyph is! ButleryGlyph) return super.build(context);

    final iconTheme = IconTheme.of(context);
    final scale = applyTextScaling ?? iconTheme.applyTextScaling ?? false;
    final tentative = size ?? iconTheme.size ?? kDefaultFontSize;
    final iconSize = scale
        ? MediaQuery.textScalerOf(context).scale(tentative)
        : tentative;

    var iconColor = color ?? iconTheme.color!;
    final opacity = iconTheme.opacity ?? 1.0;
    if (opacity != 1.0) {
      iconColor = iconColor.withValues(alpha: iconColor.a * opacity);
    }

    return Semantics(
      label: semanticLabel,
      child: ExcludeSemantics(
        child: SizedBox(
          width: iconSize,
          height: iconSize,
          child: CustomPaint(
            painter: ButleryGlyphPainter(glyph, iconColor),
          ),
        ),
      ),
    );
  }
}

/// Paints a [ButleryGlyph] in [color], scaled to the canvas.
class ButleryGlyphPainter extends CustomPainter {
  /// Creates a painter.
  ButleryGlyphPainter(this.glyph, this.color);

  /// The glyph to paint.
  final ButleryGlyph glyph;

  /// The `currentColor` of the glyph.
  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    final drawing = GlyphDrawing.of(glyph);
    final side = size.shortestSide;
    if (side <= 0) return;
    final window = displayWindow(drawing.viewBox);
    final k = side / window.width;
    canvas.save();
    canvas.translate(
      (size.width - side) / 2,
      (size.height - side) / 2,
    );
    canvas.scale(k);
    canvas.translate(-window.left, -window.top);
    for (final shape in drawing.shapes) {
      if (shape.fill) {
        canvas.drawPath(
          shape.path,
          Paint()
            ..isAntiAlias = true
            ..style = PaintingStyle.fill
            ..color = color,
        );
      }
      if (shape.stroke) {
        canvas.drawPath(
          shape.path,
          Paint()
            ..isAntiAlias = true
            ..style = PaintingStyle.stroke
            ..color = color
            ..strokeCap = shape.cap
            ..strokeJoin = shape.join
            ..strokeWidth = compensatedStrokeWidth(
              shape.strokeWidth,
              renderedSize: side,
              viewBox: drawing.viewBox,
            ),
        );
      }
    }
    canvas.restore();
  }

  @override
  bool shouldRepaint(ButleryGlyphPainter oldDelegate) =>
      oldDelegate.glyph != glyph || oldDelegate.color != color;
}

/// The part of a master's viewBox that fills the icon box.
///
/// The UI family shows its whole 24 grid. The nav family is drawn on a 160
/// grid but every drawn tab bar shows only its live area, viewBox
/// `22 22 116 116` at 24 px (Komponentark v1:667, the Skarmar v12 tab bars),
/// so the tab glyphs keep the same optical size as the UI family.
Rect displayWindow(double viewBox) => viewBox == 160
    ? const Rect.fromLTWH(22, 22, 116, 116)
    : Rect.fromLTWH(0, 0, viewBox, viewBox);

/// The master stroke of the UI family.
const double kButleryGlyphStroke = 1.75;

/// The single compensation weight at 14 px and below (Grafisk manual
/// v6:322, icons.json decision.geometry).
const double kButleryGlyphSmallStroke = 2.2;

/// Stroke width in viewBox units for a glyph rendered at [renderedSize].
///
/// Only the 24-grid master weight 1.75 is compensated; heavier exceptions
/// (check and x at 2.2, pause at 2) and the 160-grid nav family keep their
/// drawn weight.
double compensatedStrokeWidth(
  double master, {
  required double renderedSize,
  required double viewBox,
}) {
  if (viewBox == 24 && master == kButleryGlyphStroke && renderedSize <= 14) {
    return kButleryGlyphSmallStroke;
  }
  return master;
}

/// One painted element of a glyph.
@immutable
class GlyphShape {
  /// Creates a shape.
  const GlyphShape({
    required this.path,
    required this.fill,
    required this.stroke,
    required this.strokeWidth,
    required this.cap,
    required this.join,
  });

  /// Geometry in viewBox units.
  final Path path;

  /// Whether the element is filled with `currentColor`.
  final bool fill;

  /// Whether the element is stroked with `currentColor`.
  final bool stroke;

  /// Stroke width in viewBox units.
  final double strokeWidth;

  /// Stroke cap.
  final StrokeCap cap;

  /// Stroke join.
  final StrokeJoin join;
}

/// A parsed glyph: its square viewBox side and its shapes.
@immutable
class GlyphDrawing {
  /// Creates a drawing.
  const GlyphDrawing(this.viewBox, this.shapes);

  /// The side of the square viewBox (24 or 160).
  final double viewBox;

  /// The shapes in paint order.
  final List<GlyphShape> shapes;

  static final Map<ButleryGlyph, GlyphDrawing> _cache = {};

  /// The parsed drawing for [glyph], cached.
  static GlyphDrawing of(ButleryGlyph glyph) => _cache.putIfAbsent(
    glyph,
    () => parse(glyph.svg, outlined: glyph.outlined),
  );

  /// Parses an SVG master that follows the icons.json contract.
  ///
  /// Supports the elements and attributes the masters use: `path`, `circle`
  /// and `rect` (with `rx`), and `fill`, `stroke`, `stroke-width`,
  /// `stroke-linecap` and `stroke-linejoin` on the root or the element.
  /// With [outlined], a filled master is drawn as a 1.75 round stroke.
  static GlyphDrawing parse(String svg, {bool outlined = false}) {
    final root = XmlDocument.parse(svg).rootElement;
    final viewBox = root
        .getAttribute('viewBox')!
        .trim()
        .split(RegExp(r'[\s,]+'))
        .map(double.parse)
        .toList();
    final shapes = <GlyphShape>[];
    for (final el in root.childElements) {
      final Path? path = switch (el.name.local) {
        'path' => parseSvgPath(el.getAttribute('d')!),
        'circle' =>
          Path()..addOval(
            Rect.fromCircle(
              center: Offset(_num(el, 'cx'), _num(el, 'cy')),
              radius: _num(el, 'r'),
            ),
          ),
        'rect' =>
          Path()..addRRect(
            RRect.fromRectAndRadius(
              Rect.fromLTWH(
                _num(el, 'x'),
                _num(el, 'y'),
                _num(el, 'width'),
                _num(el, 'height'),
              ),
              Radius.circular(_num(el, 'rx')),
            ),
          ),
        _ => null,
      };
      if (path == null) continue;
      String? attr(String name) =>
          el.getAttribute(name) ?? root.getAttribute(name);
      final fill = outlined ? false : (attr('fill') ?? 'black') != 'none';
      final stroke = outlined ? true : (attr('stroke') ?? 'none') != 'none';
      shapes.add(
        GlyphShape(
          path: path,
          fill: fill,
          stroke: stroke,
          strokeWidth: outlined
              ? kButleryGlyphStroke
              : double.parse(attr('stroke-width') ?? '1'),
          cap: switch (outlined ? 'round' : attr('stroke-linecap')) {
            'round' => StrokeCap.round,
            'square' => StrokeCap.square,
            _ => StrokeCap.butt,
          },
          join: switch (outlined ? 'round' : attr('stroke-linejoin')) {
            'round' => StrokeJoin.round,
            'bevel' => StrokeJoin.bevel,
            _ => StrokeJoin.miter,
          },
        ),
      );
    }
    return GlyphDrawing(viewBox[2], List.unmodifiable(shapes));
  }

  static double _num(XmlElement el, String name) =>
      double.parse(el.getAttribute(name) ?? '0');
}

/// Parses SVG path data (M, L, H, V, C, S, Q, T, A, Z, absolute and
/// relative) into a [Path].
Path parseSvgPath(String d) {
  final t = _PathTokens(d);
  final path = Path();
  var cur = Offset.zero;
  var start = Offset.zero;
  Offset? lastCubicCtrl;
  Offset? lastQuadCtrl;
  String? cmd;
  while (true) {
    t.skipSeparators();
    if (t.done) break;
    if (t.atCommand) {
      cmd = t.command();
    } else if (cmd == null) {
      throw FormatException('Path data must start with a command', d);
    }
    final rel = cmd == cmd.toLowerCase();
    Offset pt(double x, double y) => rel ? cur + Offset(x, y) : Offset(x, y);
    Offset? nextCubic;
    Offset? nextQuad;
    switch (cmd.toUpperCase()) {
      case 'M':
        cur = pt(t.number(), t.number());
        start = cur;
        path.moveTo(cur.dx, cur.dy);
        // Further coordinate pairs after a moveto are implicit linetos.
        cmd = rel ? 'l' : 'L';
      case 'L':
        cur = pt(t.number(), t.number());
        path.lineTo(cur.dx, cur.dy);
      case 'H':
        final x = t.number();
        cur = Offset(rel ? cur.dx + x : x, cur.dy);
        path.lineTo(cur.dx, cur.dy);
      case 'V':
        final y = t.number();
        cur = Offset(cur.dx, rel ? cur.dy + y : y);
        path.lineTo(cur.dx, cur.dy);
      case 'C':
        final c1 = pt(t.number(), t.number());
        final c2 = pt(t.number(), t.number());
        final end = pt(t.number(), t.number());
        path.cubicTo(c1.dx, c1.dy, c2.dx, c2.dy, end.dx, end.dy);
        nextCubic = c2;
        cur = end;
      case 'S':
        final c1 = lastCubicCtrl == null ? cur : cur * 2 - lastCubicCtrl;
        final c2 = pt(t.number(), t.number());
        final end = pt(t.number(), t.number());
        path.cubicTo(c1.dx, c1.dy, c2.dx, c2.dy, end.dx, end.dy);
        nextCubic = c2;
        cur = end;
      case 'Q':
        final c = pt(t.number(), t.number());
        final end = pt(t.number(), t.number());
        path.quadraticBezierTo(c.dx, c.dy, end.dx, end.dy);
        nextQuad = c;
        cur = end;
      case 'T':
        final c = lastQuadCtrl == null ? cur : cur * 2 - lastQuadCtrl;
        final end = pt(t.number(), t.number());
        path.quadraticBezierTo(c.dx, c.dy, end.dx, end.dy);
        nextQuad = c;
        cur = end;
      case 'A':
        final rx = t.number();
        final ry = t.number();
        final rotation = t.number();
        final largeArc = t.flag();
        final sweep = t.flag();
        final end = pt(t.number(), t.number());
        path.arcToPoint(
          end,
          radius: Radius.elliptical(rx, ry),
          rotation: rotation,
          largeArc: largeArc,
          clockwise: sweep,
        );
        cur = end;
      case 'Z':
        path.close();
        cur = start;
      default:
        throw FormatException('Unsupported path command $cmd', d);
    }
    lastCubicCtrl = nextCubic;
    lastQuadCtrl = nextQuad;
  }
  return path;
}

class _PathTokens {
  _PathTokens(this.s);

  final String s;
  int i = 0;

  bool get done => i >= s.length;

  bool get atCommand => RegExp('[MmLlHhVvCcSsQqTtAaZz]').hasMatch(s[i]);

  void skipSeparators() {
    while (i < s.length &&
        (s[i] == ' ' || s[i] == ',' || s[i].trim().isEmpty)) {
      i++;
    }
  }

  String command() => s[i++];

  bool flag() {
    skipSeparators();
    final c = s[i++];
    if (c != '0' && c != '1') throw FormatException('Bad arc flag', s, i - 1);
    return c == '1';
  }

  static final RegExp _number = RegExp(
    r'[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?',
  );

  double number() {
    skipSeparators();
    final m = _number.matchAsPrefix(s, i);
    if (m == null) throw FormatException('Expected a number', s, i);
    i = m.end;
    return double.parse(m.group(0)!);
  }
}
