// GENERATED by tools/generate_butlery_icons.dart. Do not edit.
// Source: assets/icons/icons.json v1.8 (2026-08-03), 78 masters.

import 'package:butlery/widgets/common/icons/butlery_glyph.dart';

/// The Butlery icon family (beslutslogg.md:9, B-02).
///
/// Render with `ButleryIcon`, never with a plain `Icon`.
abstract final class ButleryIcons {
  /// `archive`: Arkivera.
  static const ButleryGlyph archive = ButleryGlyph(
    0xf1000,
    name: 'archive',
    meaning: 'Arkivera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>archive</title>\n  <rect x="4.5" y="4.5" width="15" height="4" rx="1.4"></rect><path d="M6 8.5v9.9A1.6 1.6 0 0 0 7.6 20h8.8a1.6 1.6 0 0 0 1.6-1.6V8.5"></path><path d="M10.2 12.2h3.6"></path>\n</svg>',
  );

  /// `arrow-left`: Tillbaka.
  static const ButleryGlyph arrowLeft = ButleryGlyph(
    0xf1001,
    name: 'arrow-left',
    meaning: 'Tillbaka',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>arrow-left</title>\n  <path d="M14.5 5.5L8 12l6.5 6.5"></path>\n</svg>',
  );

  /// `arrow-right`: Nästa steg — arrow-left fanns, arrow-right saknades.
  static const ButleryGlyph arrowRight = ButleryGlyph(
    0xf1002,
    name: 'arrow-right',
    meaning: 'Nästa steg — arrow-left fanns, arrow-right saknades',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>arrow-right</title>\n  <path d="M4.5 12h15"></path><path d="M13.5 6l6 6-6 6"></path>\n</svg>',
  );

  /// `arrow-up-down`: Sortera.
  static const ButleryGlyph arrowUpDown = ButleryGlyph(
    0xf1003,
    name: 'arrow-up-down',
    meaning: 'Sortera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>arrow-up-down</title>\n  <path d="M4 6.5h9.5M4 12h6.5M4 17.5h3.5"></path><path d="M17.5 7.5v11"></path><path d="M14.9 15.9L17.5 18.5l2.6-2.6"></path>\n</svg>',
  );

  /// `bell`: Timern är klar.
  static const ButleryGlyph bell = ButleryGlyph(
    0xf1004,
    name: 'bell',
    meaning: 'Timern är klar',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>bell</title>\n  <path d="M18 9a6 6 0 1 0-12 0c0 5.2-1.5 6.6-1.5 6.6h15S18 14.2 18 9"></path><path d="M13.7 19a2 2 0 0 1-3.4 0"></path>\n</svg>',
  );

  /// `block`: Blockerad.
  static const ButleryGlyph block = ButleryGlyph(
    0xf1005,
    name: 'block',
    meaning: 'Blockerad',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>block</title>\n  <circle cx="12" cy="12" r="7.5"></circle><path d="M6.7 6.7l10.6 10.6"></path>\n</svg>',
  );

  /// `calendar`: Veckomeny / datum.
  static const ButleryGlyph calendar = ButleryGlyph(
    0xf1006,
    name: 'calendar',
    meaning: 'Veckomeny / datum',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>calendar</title>\n  <rect x="4.5" y="6" width="15" height="14" rx="2"></rect><path d="M4.5 10h15"></path><path d="M8.6 3.8v3.4M15.4 3.8v3.4"></path>\n</svg>',
  );

  /// `camera`: Kamera.
  static const ButleryGlyph camera = ButleryGlyph(
    0xf1007,
    name: 'camera',
    meaning: 'Kamera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>camera</title>\n  <path d="M4.5 8.4h2.9l1.5-2.2h6.2l1.5 2.2h2.9a1 1 0 0 1 1 1v8.4a1 1 0 0 1-1 1H4.5a1 1 0 0 1-1-1V9.4a1 1 0 0 1 1-1z"></path><circle cx="12" cy="13.4" r="3.4"></circle>\n</svg>',
  );

  /// `check`: Bockad / klar.
  static const ButleryGlyph check = ButleryGlyph(
    0xf1008,
    name: 'check',
    meaning: 'Bockad / klar',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">\n  <title>check</title>\n  <path d="M5.5 12.5l4 4 9-9"></path>\n</svg>',
  );

  /// `check-square`: Markera alla.
  static const ButleryGlyph checkSquare = ButleryGlyph(
    0xf1009,
    name: 'check-square',
    meaning: 'Markera alla',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>check-square</title>\n  <rect x="4.5" y="4.5" width="15" height="15" rx="2.4"></rect><path d="M8.4 12.2l2.6 2.6 4.6-5"></path>\n</svg>',
  );

  /// `chevron-down`: Fäll ut.
  static const ButleryGlyph chevronDown = ButleryGlyph(
    0xf100a,
    name: 'chevron-down',
    meaning: 'Fäll ut',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>chevron-down</title>\n  <path d="M5.5 9.5L12 16l6.5-6.5"></path>\n</svg>',
  );

  /// `chevron-left`: Föregående.
  static const ButleryGlyph chevronLeft = ButleryGlyph(
    0xf100b,
    name: 'chevron-left',
    meaning: 'Föregående',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>chevron-left</title>\n  <path d="M14.5 5.5L8 12l6.5 6.5"></path>\n</svg>',
  );

  /// `chevron-right`: Nästa / framåt i rad.
  static const ButleryGlyph chevronRight = ButleryGlyph(
    0xf100c,
    name: 'chevron-right',
    meaning: 'Nästa / framåt i rad',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>chevron-right</title>\n  <path d="M9.5 5.5L16 12l-6.5 6.5"></path>\n</svg>',
  );

  /// `chevron-up`: Fäll in.
  static const ButleryGlyph chevronUp = ButleryGlyph(
    0xf100d,
    name: 'chevron-up',
    meaning: 'Fäll in',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>chevron-up</title>\n  <path d="M5.5 14.5L12 8l6.5 6.5"></path>\n</svg>',
  );

  /// `circle-check`: Bekräftad.
  static const ButleryGlyph circleCheck = ButleryGlyph(
    0xf100e,
    name: 'circle-check',
    meaning: 'Bekräftad',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>circle-check</title>\n  <circle cx="12" cy="12" r="8.5"></circle><path d="M8 12.2l2.8 2.8 5.2-5.6"></path>\n</svg>',
  );

  /// `circle-help`: Okänt / förstods inte.
  static const ButleryGlyph circleHelp = ButleryGlyph(
    0xf100f,
    name: 'circle-help',
    meaning: 'Okänt / förstods inte',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>circle-help</title>\n  <circle cx="12" cy="12" r="8.6"></circle><path d="M9.9 9.6a2.1 2.1 0 1 1 3 1.9c-.6.3-.9.8-.9 1.5"></path><path d="M12 16.4v.01"></path>\n</svg>',
  );

  /// `clock`: Tid.
  static const ButleryGlyph clock = ButleryGlyph(
    0xf1010,
    name: 'clock',
    meaning: 'Tid',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>clock</title>\n  <circle cx="12" cy="12" r="8.5"></circle><path d="M12 7.6V12l2.9 1.8"></path>\n</svg>',
  );

  /// `copy`: Duplicera.
  static const ButleryGlyph copy = ButleryGlyph(
    0xf1011,
    name: 'copy',
    meaning: 'Duplicera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>copy</title>\n  <rect x="9" y="9" width="10.5" height="10.5" rx="2"></rect><path d="M15 9V6.5A1.5 1.5 0 0 0 13.5 5H6.5A1.5 1.5 0 0 0 5 6.5v7A1.5 1.5 0 0 0 6.5 15H9"></path>\n</svg>',
  );

  /// `download`: Spara offline.
  static const ButleryGlyph download = ButleryGlyph(
    0xf1012,
    name: 'download',
    meaning: 'Spara offline',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>download</title>\n  <path d="M12 4v11"></path><path d="M7.5 10.5L12 15l4.5-4.5"></path><path d="M5 19.5h14"></path>\n</svg>',
  );

  /// `drag`: Dra för att ordna.
  static const ButleryGlyph drag = ButleryGlyph(
    0xf1013,
    name: 'drag',
    meaning: 'Dra för att ordna',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>drag</title>\n  <circle cx="9" cy="6" r="1.5"></circle><circle cx="15" cy="6" r="1.5"></circle><circle cx="9" cy="12" r="1.5"></circle><circle cx="15" cy="12" r="1.5"></circle><circle cx="9" cy="18" r="1.5"></circle><circle cx="15" cy="18" r="1.5"></circle>\n</svg>',
  );

  /// `drop`: Släppmål i veckorutnätet.
  static const ButleryGlyph drop = ButleryGlyph(
    0xf1014,
    name: 'drop',
    meaning: 'Släppmål i veckorutnätet',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>drop</title>\n  <path d="M12 3.8s5.4 5.6 5.4 9.3A5.4 5.4 0 0 1 12 18.5a5.4 5.4 0 0 1-5.4-5.4C6.6 9.4 12 3.8 12 3.8Z"></path>\n</svg>',
  );

  /// `export`: Exportera (skild från download).
  static const ButleryGlyph export = ButleryGlyph(
    0xf1015,
    name: 'export',
    meaning: 'Exportera (skild från download)',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>export</title>\n  <path d="M12 19.5V8.5"></path><path d="M7.5 13L12 8.5l4.5 4.5"></path><path d="M5 4.5h14"></path>\n</svg>',
  );

  /// `eye`: Visa/dölj.
  static const ButleryGlyph eye = ButleryGlyph(
    0xf1016,
    name: 'eye',
    meaning: 'Visa/dölj',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>eye</title>\n  <path d="M3.2 12S6.8 6.8 12 6.8 20.8 12 20.8 12 17.2 17.2 12 17.2 3.2 12 3.2 12z"></path><circle cx="12" cy="12" r="2.6"></circle>\n</svg>',
  );

  /// `file`: Fil.
  static const ButleryGlyph file = ButleryGlyph(
    0xf1017,
    name: 'file',
    meaning: 'Fil',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>file</title>\n  <path d="M6.5 3.5h7L18 8v11.5a1 1 0 0 1-1 1H6.5a1 1 0 0 1-1-1V4.5a1 1 0 0 1 1-1z"></path><path d="M13.5 3.5V8H18"></path><path d="M8.5 13h7M8.5 16.5h4.5"></path>\n</svg>',
  );

  /// `filter`: Filtrera.
  static const ButleryGlyph filter = ButleryGlyph(
    0xf1018,
    name: 'filter',
    meaning: 'Filtrera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>filter</title>\n  <path d="M4.5 7h15M7.5 12h9M10.5 17h3"></path>\n</svg>',
  );

  /// `folder`: Samling.
  static const ButleryGlyph folder = ButleryGlyph(
    0xf1019,
    name: 'folder',
    meaning: 'Samling',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>folder</title>\n  <path d="M4.5 7.6A1.6 1.6 0 0 1 6.1 6h3.3l2 2h6.5A1.6 1.6 0 0 1 19.5 9.6v7.8A1.6 1.6 0 0 1 17.9 19H6.1a1.6 1.6 0 0 1-1.6-1.6z"></path>\n</svg>',
  );

  /// `hand`: Gör själv / placera manuellt.
  static const ButleryGlyph hand = ButleryGlyph(
    0xf101a,
    name: 'hand',
    meaning: 'Gör själv / placera manuellt',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>hand</title>\n  <path d="M9 11V5.6a1.6 1.6 0 0 1 3.2 0V11"></path><path d="M12.2 10V6.8a1.6 1.6 0 0 1 3.2 0V13"></path><path d="M15.4 11.4a1.6 1.6 0 0 1 3.2 0V15a5.6 5.6 0 0 1-5.6 5.6h-1.4a5.6 5.6 0 0 1-5.6-5.6v-2.6a1.6 1.6 0 0 1 3.2 0"></path>\n</svg>',
  );

  /// `heart`: Favorit.
  static const ButleryGlyph heart = ButleryGlyph(
    0xf101b,
    name: 'heart',
    meaning: 'Favorit',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>heart</title>\n  <path d="M12 19.6l-7-6.9a4.3 4.3 0 0 1 6.1-6.05L12 7.5l.9-.85A4.3 4.3 0 0 1 19 12.7z"></path>\n</svg>',
  );

  /// `house`: Hemma (närvaro).
  static const ButleryGlyph house = ButleryGlyph(
    0xf101c,
    name: 'house',
    meaning: 'Hemma (närvaro)',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>house</title>\n  <path d="M4 10.5 12 4l8 6.5V20H4z"></path>\n</svg>',
  );

  /// `image`: Bild.
  static const ButleryGlyph image = ButleryGlyph(
    0xf101d,
    name: 'image',
    meaning: 'Bild',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>image</title>\n  <rect x="4" y="5" width="16" height="14" rx="2"></rect><circle cx="8.8" cy="9.6" r="1.5"></circle><path d="M4.6 17.4l4.4-4.4 3.4 3.4 2.9-2.9 4.7 4.7"></path>\n</svg>',
  );

  /// `info`: Information.
  static const ButleryGlyph info = ButleryGlyph(
    0xf101e,
    name: 'info',
    meaning: 'Information',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>info</title>\n  <circle cx="12" cy="12" r="8.5"></circle><path d="M12 11v5.5"></path><circle cx="12" cy="7.8" r="1" fill="currentColor" stroke="none"></circle>\n</svg>',
  );

  /// `link`: Kopiera länk.
  static const ButleryGlyph link = ButleryGlyph(
    0xf101f,
    name: 'link',
    meaning: 'Kopiera länk',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>link</title>\n  <path d="M9.5 12h5"></path><path d="M10 8.3H8.8a3.7 3.7 0 0 0 0 7.4H10"></path><path d="M14 8.3h1.2a3.7 3.7 0 0 1 0 7.4H14"></path>\n</svg>',
  );

  /// `list`: Lista / välj själv.
  static const ButleryGlyph list = ButleryGlyph(
    0xf1020,
    name: 'list',
    meaning: 'Lista / välj själv',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>list</title>\n  <path d="M4 7h16M4 12h16M4 17h11"></path>\n</svg>',
  );

  /// `list-check`: Välj flera.
  static const ButleryGlyph listCheck = ButleryGlyph(
    0xf1021,
    name: 'list-check',
    meaning: 'Välj flera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>list-check</title>\n  <path d="M4 7.5l2 2 3.5-3.5M12 8h8M4 16.5l2 2L9.5 15M12 17h8"></path>\n</svg>',
  );

  /// `lock`: Låst / privat.
  static const ButleryGlyph lock = ButleryGlyph(
    0xf1022,
    name: 'lock',
    meaning: 'Låst / privat',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>lock</title>\n  <rect x="5" y="10.6" width="14" height="9.4" rx="2"></rect><path d="M8.4 10.6V7.8a3.6 3.6 0 0 1 7.2 0v2.8"></path>\n</svg>',
  );

  /// `mail`: E-post.
  static const ButleryGlyph mail = ButleryGlyph(
    0xf1023,
    name: 'mail',
    meaning: 'E-post',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>mail</title>\n  <rect x="3.6" y="6" width="16.8" height="12" rx="2"></rect><path d="M4.2 7.3L12 12.8l7.8-5.5"></path>\n</svg>',
  );

  /// `message-square`: Meddelande.
  static const ButleryGlyph messageSquare = ButleryGlyph(
    0xf1024,
    name: 'message-square',
    meaning: 'Meddelande',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>message-square</title>\n  <path d="M4.5 6.6A2 2 0 0 1 6.5 4.6h11a2 2 0 0 1 2 2v7.2a2 2 0 0 1-2 2H9.4L5.6 19.4v-3.6h.9a2 2 0 0 1-2-2z"></path><circle cx="9.2" cy="10.2" r="1" fill="currentColor" stroke="none"></circle><circle cx="12" cy="10.2" r="1" fill="currentColor" stroke="none"></circle><circle cx="14.8" cy="10.2" r="1" fill="currentColor" stroke="none"></circle>\n</svg>',
  );

  /// `mic`: Diktera (röstinmatning).
  static const ButleryGlyph mic = ButleryGlyph(
    0xf1025,
    name: 'mic',
    meaning: 'Diktera (röstinmatning)',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>mic</title>\n  <rect x="9.2" y="3" width="5.6" height="10" rx="2.8"></rect><path d="M6 11.5a6 6 0 0 0 12 0"></path><path d="M12 17.5V21"></path>\n</svg>',
  );

  /// `minus`: Minska — stepparens andra hälft; plus fanns, minus saknades.
  static const ButleryGlyph minus = ButleryGlyph(
    0xf1026,
    name: 'minus',
    meaning: 'Minska — stepparens andra hälft; plus fanns, minus saknades',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>minus</title>\n  <path d="M5.5 12h13"></path>\n</svg>',
  );

  /// `more-vertical`: Fler åtgärder (kebab).
  static const ButleryGlyph moreVertical = ButleryGlyph(
    0xf1027,
    name: 'more-vertical',
    meaning: 'Fler åtgärder (kebab)',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>more-vertical</title>\n  <circle cx="12" cy="5.6" r="1.5"></circle><circle cx="12" cy="12" r="1.5"></circle><circle cx="12" cy="18.4" r="1.5"></circle>\n</svg>',
  );

  /// `move`: Flytta en måltid mellan platser.
  static const ButleryGlyph move = ButleryGlyph(
    0xf1028,
    name: 'move',
    meaning: 'Flytta en måltid mellan platser',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>move</title>\n  <path d="M12 4.5v15"></path><path d="M4.5 12h15"></path><path d="M9.4 7.1L12 4.5l2.6 2.6"></path><path d="M9.4 16.9L12 19.5l2.6-2.6"></path><path d="M7.1 9.4L4.5 12l2.6 2.6"></path><path d="M16.9 9.4L19.5 12l-2.6 2.6"></path>\n</svg>',
  );

  /// `paperclip`: Bifoga.
  static const ButleryGlyph paperclip = ButleryGlyph(
    0xf1029,
    name: 'paperclip',
    meaning: 'Bifoga',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>paperclip</title>\n  <path d="M13.7 7.1L7.7 13.1a3.4 3.4 0 0 0 4.8 4.8l6.4-6.4a4.9 4.9 0 0 0-6.9-6.9L6 10.6"></path>\n</svg>',
  );

  /// `pause`: Pausa en pågående timer i matlagningsläget..
  static const ButleryGlyph pause = ButleryGlyph(
    0xf102a,
    name: 'pause',
    meaning: 'Pausa en pågående timer i matlagningsläget.',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n  <title>pause</title>\n  <path d="M9.5 5.5v13M14.5 5.5v13"></path>\n</svg>',
  );

  /// `pencil`: Redigera.
  static const ButleryGlyph pencil = ButleryGlyph(
    0xf102b,
    name: 'pencil',
    meaning: 'Redigera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>pencil</title>\n  <path d="M4.5 19.5l1-4.4L15.9 4.7l3.4 3.4L8.9 18.5z"></path><path d="M13.6 7l3.4 3.4"></path>\n</svg>',
  );

  /// `pin`: Fäst.
  static const ButleryGlyph pin = ButleryGlyph(
    0xf102c,
    name: 'pin',
    meaning: 'Fäst',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>pin</title>\n  <path d="M12 3.6v9.2"></path><path d="M8.4 3.6h7.2"></path><path d="M12 12.8l-3.1 3.6h6.2z"></path><path d="M12 16.4V20.4"></path>\n</svg>',
  );

  /// `play`: Starta matlagning.
  static const ButleryGlyph play = ButleryGlyph(
    0xf102d,
    name: 'play',
    meaning: 'Starta matlagning',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>play</title>\n  <circle cx="12" cy="12" r="8.5"></circle><path d="M10.3 8.6l5.3 3.4-5.3 3.4z"></path>\n</svg>',
  );

  /// `plus`: Lägg till.
  static const ButleryGlyph plus = ButleryGlyph(
    0xf102e,
    name: 'plus',
    meaning: 'Lägg till',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>plus</title>\n  <path d="M12 5.5v13M5.5 12h13"></path>\n</svg>',
  );

  /// `reaction-add`: Lägg till en reaktion.
  static const ButleryGlyph reactionAdd = ButleryGlyph(
    0xf102f,
    name: 'reaction-add',
    meaning: 'Lägg till en reaktion',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>reaction-add</title>\n  <path d="M20 12a8 8 0 1 1-4.4-7.1"></path><path d="M9 10.2h.01"></path><path d="M15 10.2h.01"></path><path d="M8.6 14.4a4.3 4.3 0 0 0 6.3.5"></path><path d="M18 3.5v5"></path><path d="M15.5 6h5"></path>\n</svg>',
  );

  /// `refresh-cw`: Försök igen / synka.
  static const ButleryGlyph refreshCw = ButleryGlyph(
    0xf1030,
    name: 'refresh-cw',
    meaning: 'Försök igen / synka',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>refresh-cw</title>\n  <path d="M4.6 11a7.4 7.4 0 0 1 12.7-4.5L19.4 8.6"></path><path d="M19.4 4.8v3.8h-3.8"></path><path d="M19.4 13a7.4 7.4 0 0 1-12.7 4.5L4.6 15.4"></path><path d="M4.6 19.2v-3.8h3.8"></path>\n</svg>',
  );

  /// `search`: Sök.
  static const ButleryGlyph search = ButleryGlyph(
    0xf1031,
    name: 'search',
    meaning: 'Sök',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>search</title>\n  <circle cx="10.8" cy="10.8" r="6.3"></circle><path d="M15.4 15.4L20 20"></path>\n</svg>',
  );

  /// `send`: Skicka.
  static const ButleryGlyph send = ButleryGlyph(
    0xf1032,
    name: 'send',
    meaning: 'Skicka',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>send</title>\n  <path d="M20.5 3.5L4 10.6a.4.4 0 0 0 0 .74l5.5 2.1 2.1 5.5a.4.4 0 0 0 .74 0z"></path><path d="M20.5 3.5L9.5 13.4"></path>\n</svg>',
  );

  /// `server`: Drift och system (adminflik).
  static const ButleryGlyph server = ButleryGlyph(
    0xf1033,
    name: 'server',
    meaning: 'Drift och system (adminflik)',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>server</title>\n  <path d="M4 4.5h16v5H4zM4 14.5h16v5H4z"></path><path d="M7.5 7h.01M7.5 17h.01"></path>\n</svg>',
  );

  /// `settings`: Inställningar.
  static const ButleryGlyph settings = ButleryGlyph(
    0xf1034,
    name: 'settings',
    meaning: 'Inställningar',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>settings</title>\n  <circle cx="12" cy="12" r="2.9"></circle><path d="M19.1 14.4a1.5 1.5 0 0 0 .3 1.65l.05.06a1.8 1.8 0 1 1-2.55 2.55l-.06-.06a1.5 1.5 0 0 0-1.65-.3 1.5 1.5 0 0 0-.9 1.37v.17a1.8 1.8 0 1 1-3.6 0v-.09a1.5 1.5 0 0 0-.98-1.37 1.5 1.5 0 0 0-1.65.3l-.06.06a1.8 1.8 0 1 1-2.55-2.55l.06-.06a1.5 1.5 0 0 0 .3-1.65 1.5 1.5 0 0 0-1.37-.9h-.17a1.8 1.8 0 1 1 0-3.6h.09a1.5 1.5 0 0 0 1.37-.98 1.5 1.5 0 0 0-.3-1.65l-.06-.06a1.8 1.8 0 1 1 2.55-2.55l.06.06a1.5 1.5 0 0 0 1.65.3h.07a1.5 1.5 0 0 0 .9-1.37v-.17a1.8 1.8 0 1 1 3.6 0v.09a1.5 1.5 0 0 0 .9 1.37 1.5 1.5 0 0 0 1.65-.3l.06-.06a1.8 1.8 0 1 1 2.55 2.55l-.06.06a1.5 1.5 0 0 0-.3 1.65v.07a1.5 1.5 0 0 0 1.37.9h.17a1.8 1.8 0 1 1 0 3.6h-.09a1.5 1.5 0 0 0-1.37.9Z"></path>\n</svg>',
  );

  /// `share-2`: Dela.
  static const ButleryGlyph share2 = ButleryGlyph(
    0xf1035,
    name: 'share-2',
    meaning: 'Dela',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>share-2</title>\n  <path d="M9 4.5H6.1A1.6 1.6 0 0 0 4.5 6.1v11.8A1.6 1.6 0 0 0 6.1 19.5h11.8a1.6 1.6 0 0 0 1.6-1.6V15"></path><path d="M13.5 4.5h6v6"></path><path d="M19.5 4.5L11 13"></path>\n</svg>',
  );

  /// `shield-check`: Verifierad.
  static const ButleryGlyph shieldCheck = ButleryGlyph(
    0xf1036,
    name: 'shield-check',
    meaning: 'Verifierad',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>shield-check</title>\n  <path d="M12 3.2l6.4 2.3v5.1c0 4.4-3 7.5-6.4 8.9-3.4-1.4-6.4-4.5-6.4-8.9V5.5z"></path><path d="M9 12.2l2.4 2.4 4.1-4.5"></path>\n</svg>',
  );

  /// `shopping-cart`: Inköp.
  static const ButleryGlyph shoppingCart = ButleryGlyph(
    0xf1037,
    name: 'shopping-cart',
    meaning: 'Inköp',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>shopping-cart</title>\n  <path d="M4.5 6.2h2l2.7 8.9h8l2-6.2H7.2"></path><circle cx="9.6" cy="18.2" r="1.5"></circle><circle cx="16.4" cy="18.2" r="1.5"></circle>\n</svg>',
  );

  /// `shuffle`: Slumpa / fördela resten.
  static const ButleryGlyph shuffle = ButleryGlyph(
    0xf1038,
    name: 'shuffle',
    meaning: 'Slumpa / fördela resten',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>shuffle</title>\n  <path d="M4 6h3.5l9 12H20"></path><path d="M17 4l3 2-3 2"></path><path d="M4 18h3.5l2.6-3.5"></path><path d="M17 20l3-2-3-2"></path>\n</svg>',
  );

  /// `star`: Betyg.
  static const ButleryGlyph star = ButleryGlyph(
    0xf1039,
    name: 'star',
    meaning: 'Betyg',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>star</title>\n  <path d="M12 3.6l2.7 5.5 6 .9-4.35 4.25 1.03 5.95L12 17.35l-5.38 2.85 1.03-5.95L3.3 10l6-.9z"></path>\n</svg>',
  );

  /// `stop`: Stoppa inspelning i matlagningsläget.
  static const ButleryGlyph stop = ButleryGlyph(
    0xf103a,
    name: 'stop',
    meaning: 'Stoppa inspelning i matlagningsläget',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>stop</title>\n  <rect x="5.5" y="5.5" width="13" height="13" rx="2.2"></rect>\n</svg>',
  );

  /// `swap-horizontal`: Byt ut.
  static const ButleryGlyph swapHorizontal = ButleryGlyph(
    0xf103b,
    name: 'swap-horizontal',
    meaning: 'Byt ut',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>swap-horizontal</title>\n  <path d="M4 9h13l-3.2-3.2M20 15H7l3.2 3.2"></path>\n</svg>',
  );

  /// `tag`: Egen tagg.
  static const ButleryGlyph tag = ButleryGlyph(
    0xf103c,
    name: 'tag',
    meaning: 'Egen tagg',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>tag</title>\n  <path d="M11.1 4.5H5.6A1.1 1.1 0 0 0 4.5 5.6v5.5c0 .3.12.57.32.78l7.6 7.6a1.1 1.1 0 0 0 1.56 0l5.5-5.5a1.1 1.1 0 0 0 0-1.56l-7.6-7.6a1.1 1.1 0 0 0-.78-.32Z"></path><path d="M8.2 8.2h.01"></path>\n</svg>',
  );

  /// `trash-2`: Radera.
  static const ButleryGlyph trash2 = ButleryGlyph(
    0xf103d,
    name: 'trash-2',
    meaning: 'Radera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>trash-2</title>\n  <path d="M4.8 6.8h14.4"></path><path d="M9.4 6.8V4.9A1.4 1.4 0 0 1 10.8 3.5h2.4a1.4 1.4 0 0 1 1.4 1.4v1.9"></path><path d="M6.6 6.8l.85 12.3A1.5 1.5 0 0 0 8.95 20.5h6.1a1.5 1.5 0 0 0 1.5-1.4l.85-12.3"></path><path d="M10.3 10.4v6M13.7 10.4v6"></path>\n</svg>',
  );

  /// `triangle-alert`: Varning / fel.
  static const ButleryGlyph triangleAlert = ButleryGlyph(
    0xf103e,
    name: 'triangle-alert',
    meaning: 'Varning / fel',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>triangle-alert</title>\n  <path d="M10.35 5a1.9 1.9 0 0 1 3.3 0l7 12.2a1.9 1.9 0 0 1-1.65 2.85H5a1.9 1.9 0 0 1-1.65-2.85z"></path><path d="M12 9.9v4.2M12 17.2v.01"></path>\n</svg>',
  );

  /// `unlock`: Avblockera.
  static const ButleryGlyph unlock = ButleryGlyph(
    0xf103f,
    name: 'unlock',
    meaning: 'Avblockera',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>unlock</title>\n  <rect x="4.8" y="10.5" width="14.4" height="9" rx="2"></rect><path d="M8.2 10.5V7.9a3.8 3.8 0 0 1 7.4-1.3"></path>\n</svg>',
  );

  /// `user`: En person.
  static const ButleryGlyph user = ButleryGlyph(
    0xf1040,
    name: 'user',
    meaning: 'En person',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>user</title>\n  <circle cx="12" cy="9.4" r="3.4"></circle><path d="M5.6 19.8a6.4 6.4 0 0 1 12.8 0"></path>\n</svg>',
  );

  /// `user-minus`: Ta bort medlem.
  static const ButleryGlyph userMinus = ButleryGlyph(
    0xf1041,
    name: 'user-minus',
    meaning: 'Ta bort medlem',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>user-minus</title>\n  <path d="M15.5 19.5v-1.7a3.4 3.4 0 0 0-3.4-3.4H6.9a3.4 3.4 0 0 0-3.4 3.4v1.7"></path><circle cx="9.5" cy="7.6" r="3.4"></circle><path d="M16.5 11.5h4"></path>\n</svg>',
  );

  /// `users`: Flera personer / grupp.
  static const ButleryGlyph users = ButleryGlyph(
    0xf1042,
    name: 'users',
    meaning: 'Flera personer / grupp',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>users</title>\n  <circle cx="12" cy="8.2" r="3.1"></circle><path d="M6.8 18.4a5.2 5.2 0 0 1 10.4 0"></path><circle cx="5.2" cy="10.3" r="2"></circle><circle cx="18.8" cy="10.3" r="2"></circle><path d="M3 17.2a3 3 0 0 1 2.9-2.6M21 17.2a3 3 0 0 0-2.9-2.6"></path>\n</svg>',
  );

  /// `utensils`: Meny / måltid.
  static const ButleryGlyph utensils = ButleryGlyph(
    0xf1043,
    name: 'utensils',
    meaning: 'Meny / måltid',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>utensils</title>\n  <path d="M7 3v7.5a2.5 2.5 0 0 0 5 0V3"></path><path d="M9.5 10.5V21"></path><path d="M16.5 3c1.6 1.4 2 3.4 2 5.2 0 1.5-.7 2.3-1.6 2.7V21"></path>\n</svg>',
  );

  /// `volume`: Tysta uppläsningen.
  static const ButleryGlyph volume = ButleryGlyph(
    0xf1044,
    name: 'volume',
    meaning: 'Tysta uppläsningen',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>volume</title>\n  <path d="M11.5 5.2 7.3 8.7H4.5v6.6h2.8l4.2 3.5V5.2Z"></path><path d="M15.4 9.4a3.7 3.7 0 0 1 0 5.2"></path><path d="M18 6.8a7.3 7.3 0 0 1 0 10.4"></path>\n</svg>',
  );

  /// `vote`: Rösta / föreslå alternativ.
  static const ButleryGlyph vote = ButleryGlyph(
    0xf1045,
    name: 'vote',
    meaning: 'Rösta / föreslå alternativ',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>vote</title>\n  <path d="M4 15.5 12 19l8-3.5"></path><path d="M6.5 12 12 14.4 17.5 12"></path><path d="M8.5 8.6 12 4.8l3.5 3.8"></path>\n</svg>',
  );

  /// `wifi-off`: Offline.
  static const ButleryGlyph wifiOff = ButleryGlyph(
    0xf1046,
    name: 'wifi-off',
    meaning: 'Offline',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>wifi-off</title>\n  <path d="M4.4 8.8a11.4 11.4 0 0 1 15.2 0"></path><path d="M7.1 11.9a7.6 7.6 0 0 1 9.8 0"></path><path d="M9.7 14.9a3.8 3.8 0 0 1 4.6 0"></path><path d="M12 18v.01"></path><path d="M3.5 3.5l17 17"></path>\n</svg>',
  );

  /// `x`: Stäng.
  static const ButleryGlyph x = ButleryGlyph(
    0xf1047,
    name: 'x',
    meaning: 'Stäng',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">\n  <title>x</title>\n  <path d="M6 6l12 12M18 6L6 18"></path>\n</svg>',
  );

  /// `zap`: Snabbt.
  static const ButleryGlyph zap = ButleryGlyph(
    0xf1048,
    name: 'zap',
    meaning: 'Snabbt',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">\n  <title>zap</title>\n  <path d="M13.4 3.2L6.8 12.4h4.3l-.6 8.4 6.7-9.8h-4.4z"></path>\n</svg>',
  );

  /// `nav-home`: nav-home.
  static const ButleryGlyph navHome = ButleryGlyph(
    0xf1049,
    name: 'nav-home',
    meaning: 'nav-home',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">\n  <title>nav-home</title>\n  <path d="M40.5 104 C40.5 81.09 57.88 64.5 80 64.5 C102.12 64.5 119.5 81.09 119.5 104" stroke-linecap="butt"></path><path d="M28 113H132"></path><path d="M80 55V60"></path><rect x="72" y="48" width="16" height="8" rx="4" fill="currentColor" stroke="none"></rect>\n</svg>',
  );

  /// `nav-week`: nav-week.
  static const ButleryGlyph navWeek = ButleryGlyph(
    0xf104a,
    name: 'nav-week',
    meaning: 'nav-week',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">\n  <title>nav-week</title>\n  <rect x="31" y="40" width="98" height="88" rx="15"></rect><path d="M31 66H129"></path><path d="M57 27V49M103 27V49"></path><path d="M61 106 C61 93 69 86 80 86 C91 86 99 93 99 106" stroke-linecap="butt"></path><path d="M56 111H104"></path><path d="M80 82V85"></path><rect x="74" y="77" width="12" height="6" rx="3" fill="currentColor" stroke="none"></rect>\n</svg>',
  );

  /// `nav-add`: nav-add.
  static const ButleryGlyph navAdd = ButleryGlyph(
    0xf104b,
    name: 'nav-add',
    meaning: 'nav-add',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">\n  <title>nav-add</title>\n  <path d="M80 43v74M43 80h74"></path>\n</svg>',
  );

  /// `nav-shopping`: nav-shopping.
  static const ButleryGlyph navShopping = ButleryGlyph(
    0xf104c,
    name: 'nav-shopping',
    meaning: 'nav-shopping',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">\n  <title>nav-shopping</title>\n  <path d="M30 41H43L62 104H118L134 60H50"></path><circle cx="63" cy="123" r="9"></circle><circle cx="112" cy="123" r="9"></circle>\n</svg>',
  );

  /// `nav-more`: nav-more.
  static const ButleryGlyph navMore = ButleryGlyph(
    0xf104d,
    name: 'nav-more',
    meaning: 'nav-more',
    svg:
        '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">\n  <title>nav-more</title>\n  <path d="M40 52H120"></path><path d="M40 80H120"></path><path d="M40 108H120"></path>\n</svg>',
  );

  /// `heart` drawn as an outline (the off state).
  static const ButleryGlyph heartOutline = ButleryGlyph(
    0xf1100,
    name: 'heart',
    meaning: heartMeaning,
    svg: heartSvg,
    outlined: true,
  );

  /// The meaning of `heart`.
  static const String heartMeaning = 'Favorit';

  /// The master of `heart`.
  static const String heartSvg =
      '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>heart</title>\n  <path d="M12 19.6l-7-6.9a4.3 4.3 0 0 1 6.1-6.05L12 7.5l.9-.85A4.3 4.3 0 0 1 19 12.7z"></path>\n</svg>';

  /// `star` drawn as an outline (the off state).
  static const ButleryGlyph starOutline = ButleryGlyph(
    0xf1101,
    name: 'star',
    meaning: starMeaning,
    svg: starSvg,
    outlined: true,
  );

  /// The meaning of `star`.
  static const String starMeaning = 'Betyg';

  /// The master of `star`.
  static const String starSvg =
      '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="none">\n  <title>star</title>\n  <path d="M12 3.6l2.7 5.5 6 .9-4.35 4.25 1.03 5.95L12 17.35l-5.38 2.85 1.03-5.95L3.3 10l6-.9z"></path>\n</svg>';

  /// Semantic alias for [heart].
  static const ButleryGlyph favourite = heart;

  /// Semantic alias for [heartOutline].
  static const ButleryGlyph favouriteOutline = heartOutline;

  /// Semantic alias for [star].
  static const ButleryGlyph primary = star;

  /// Semantic alias for [starOutline].
  static const ButleryGlyph primaryOutline = starOutline;

  /// Semantic alias for [arrowLeft].
  static const ButleryGlyph back = arrowLeft;

  /// Semantic alias for [x].
  static const ButleryGlyph close = x;

  /// Every glyph, one per master, then the outline states.
  static const List<ButleryGlyph> values = [
    archive,
    arrowLeft,
    arrowRight,
    arrowUpDown,
    bell,
    block,
    calendar,
    camera,
    check,
    checkSquare,
    chevronDown,
    chevronLeft,
    chevronRight,
    chevronUp,
    circleCheck,
    circleHelp,
    clock,
    copy,
    download,
    drag,
    drop,
    export,
    eye,
    file,
    filter,
    folder,
    hand,
    heart,
    house,
    image,
    info,
    link,
    list,
    listCheck,
    lock,
    mail,
    messageSquare,
    mic,
    minus,
    moreVertical,
    move,
    paperclip,
    pause,
    pencil,
    pin,
    play,
    plus,
    reactionAdd,
    refreshCw,
    search,
    send,
    server,
    settings,
    share2,
    shieldCheck,
    shoppingCart,
    shuffle,
    star,
    stop,
    swapHorizontal,
    tag,
    trash2,
    triangleAlert,
    unlock,
    user,
    userMinus,
    users,
    utensils,
    volume,
    vote,
    wifiOff,
    x,
    zap,
    navHome,
    navWeek,
    navAdd,
    navShopping,
    navMore,
    heartOutline,
    starOutline,
  ];
}
