import 'package:butlery/core/base/base_service.dart';
import 'package:butlery/core/utils/logger.dart';
import 'package:butlery/models/social/content_report.dart';
import 'package:butlery/repositories/firebase/firebase_report_repository.dart';
import 'package:butlery/repositories/interfaces/auth_repository.dart' as auth;

/// Service for submitting and managing content reports.
class ReportService extends BaseService {
  @override
  String get serviceName => 'ReportService';

  final FirebaseReportRepository _reportRepository;
  final auth.AuthRepository _authRepository;

  ReportService({
    required FirebaseReportRepository reportRepository,
    required auth.AuthRepository authRepository,
  })  : _reportRepository = reportRepository,
        _authRepository = authRepository;

  /// Submit a content report.
  Future<bool> submitReport({
    required String contentType,
    required String contentId,
    required String reason,
    String? contentOwnerId,
    String? description,
  }) async {
    return await executeServiceOperation(
          () async {
            final userId = _authRepository.currentUserId;
            if (userId == null) {
              AppLogger.warning(
                  '[ReportService] Cannot submit report: not authenticated');
              return false;
            }

            final report = ContentReport(
              id: '', // Generated by Firestore
              reporterId: userId,
              contentType: contentType,
              contentId: contentId,
              contentOwnerId: contentOwnerId,
              reason: reason,
              description: description,
              createdAt: DateTime.now(),
            );

            final docId = await _reportRepository.submitReport(report);
            return docId != null;
          },
          operationName: 'Submit report',
          requiresAuth: true,
        ) ??
        false;
  }

  /// Get reports submitted by the current user.
  Future<List<ContentReport>> getMyReports() async {
    return await executeServiceOperation(
          () async {
            final userId = _authRepository.currentUserId;
            if (userId == null) return <ContentReport>[];
            return _reportRepository.getUserReports(userId);
          },
          operationName: 'Get my reports',
          requiresAuth: true,
        ) ??
        [];
  }
}
