import 'package:clock/clock.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:butlery/core/base/base_service.dart';
import 'package:butlery/core/constants/firestore_collections.dart';
import 'package:butlery/core/utils/logger.dart';
import 'package:butlery/models/social/content_report.dart';
import 'package:butlery/models/social/content_type.dart';
import 'package:butlery/repositories/firebase/firebase_report_repository.dart';
import 'package:butlery/repositories/firestore_repository.dart';
import 'package:butlery/repositories/interfaces/auth_repository.dart' as auth;

/// Service for submitting and managing content reports, including the
/// admin-gated moderation workflow.
class ReportService extends BaseService {
  @override
  String get serviceName => 'ReportService';

  final FirebaseReportRepository _reportRepository;
  final auth.AuthRepository _authRepository;
  final FirestoreRepository _firestore;

  ReportService({
    required FirebaseReportRepository reportRepository,
    required auth.AuthRepository authRepository,
    required FirestoreRepository firestoreRepository,
  })  : _reportRepository = reportRepository,
        _authRepository = authRepository,
        _firestore = firestoreRepository;

  /// Submit a content report.
  Future<bool> submitReport({
    required ContentType contentType,
    required String contentId,
    required String reason,
    String? contentOwnerId,
    String? description,
  }) async {
    return await executeServiceOperation(
          () async {
            final userId = _authRepository.currentUserId;
            if (userId == null) {
              AppLogger.warning(
                  '[ReportService] Cannot submit report: not authenticated');
              return false;
            }

            final report = ContentReport(
              id: '', // Generated by Firestore
              reporterId: userId,
              contentType: contentType,
              contentId: contentId,
              contentOwnerId: contentOwnerId,
              reason: reason,
              description: description,
              createdAt: clock.now(),
            );

            final docId = await _reportRepository.submitReport(report);
            return docId != null;
          },
          operationName: 'Submit report',
          requiresAuth: true,
        ) ??
        false;
  }

  /// Get reports submitted by the current user.
  Future<List<ContentReport>> getMyReports() async {
    return await executeServiceOperation(
          () async {
            final userId = _authRepository.currentUserId;
            if (userId == null) return <ContentReport>[];
            return _reportRepository.getUserReports(userId);
          },
          operationName: 'Get my reports',
          requiresAuth: true,
        ) ??
        [];
  }

  // ── Admin / moderation API ─────────────────────────────────────────────

  /// Stream whether the current user is an admin. Listens to
  /// `admins/{uid}` document existence — rules lock the collection so the
  /// existence of the doc is the source of truth.
  Stream<bool> watchIsAdmin() {
    final userId = _authRepository.currentUserId;
    if (userId == null) {
      return Stream<bool>.value(false);
    }
    return _firestore
        .collection('admins')
        .doc(userId)
        .snapshots()
        .map((snap) => snap.exists)
        .handleError((Object error) {
      AppLogger.warning(
          '[ReportService] watchIsAdmin error (treating as non-admin): $error');
      return false;
    });
  }

  /// Stream open reports (status != 'closed') ordered by newest first.
  /// Admin-only by rules; non-admins will receive a permission-denied
  /// on the underlying query.
  Stream<List<ContentReport>> watchOpenReports() {
    return _firestore
        .collection(FirestoreCollections.reports)
        .where('status', whereIn: ['new', 'in_review', 'actioned'])
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snap) => snap.docs
            .map(ContentReport.fromFirestore)
            .whereType<ContentReport>()
            .toList());
  }

  /// Advance a report's status one step forward. Returns `true` on success.
  /// Rules enforce the forward-only state machine authoritatively; this
  /// client-side helper just computes the next legal status.
  Future<bool> advanceReportStatus(ContentReport report) async {
    final next = switch (report.status) {
      ReportStatus.newReport => ReportStatus.inReview,
      ReportStatus.inReview => ReportStatus.actioned,
      ReportStatus.actioned => ReportStatus.closed,
      ReportStatus.closed => ReportStatus.closed,
    };
    if (next == report.status) return false;

    return await executeServiceOperation(
          () async {
            await _firestore
                .collection(FirestoreCollections.reports)
                .doc(report.id)
                .update({'status': next.wireName});
            return true;
          },
          operationName: 'Advance report status',
          requiresAuth: true,
        ) ??
        false;
  }

  /// Close a report outright (admin decision: not actionable / duplicate).
  Future<bool> closeReport(ContentReport report) async {
    if (report.status == ReportStatus.closed) return true;
    return await executeServiceOperation(
          () async {
            await _firestore
                .collection(FirestoreCollections.reports)
                .doc(report.id)
                .update({'status': ReportStatus.closed.wireName});
            return true;
          },
          operationName: 'Close report',
          requiresAuth: true,
        ) ??
        false;
  }

  /// Delete the content referenced by a report. Collection-specific paths
  /// are derived from `contentType`. Returns `true` on success; admins must
  /// be authenticated and the target's rule block must permit admin delete
  /// (see `firestore.rules`).
  Future<bool> deleteReportedContent(ContentReport report) async {
    return await executeServiceOperation(
          () async {
            final ref = _resolveContentRef(report);
            if (ref == null) {
              AppLogger.warning(
                  '[ReportService] Unknown contentType ${report.contentType}; cannot delete');
              return false;
            }
            await ref.delete();
            AppLogger.info(
                '[ReportService] Admin deleted ${report.contentType}/${report.contentId} via report ${report.id}');
            return true;
          },
          operationName: 'Delete reported content',
          requiresAuth: true,
        ) ??
        false;
  }

  /// Reversible profile takedown. Hard-delete is intentionally avoided so a
  /// moderator can un-hide and so the auth account / friendships stay intact.
  /// Returns `false` on contentType mismatch or missing owner.
  Future<bool> suspendReportedProfile(ContentReport report) async {
    return await executeServiceOperation(
          () async {
            if (report.contentType != ContentType.profile) {
              AppLogger.warning(
                  '[ReportService] suspendReportedProfile called on contentType ${report.contentType}; refusing');
              return false;
            }
            final ownerId = report.contentOwnerId;
            if (ownerId == null || ownerId.isEmpty) {
              AppLogger.warning(
                  '[ReportService] profile report ${report.id} missing contentOwnerId');
              return false;
            }
            await _firestore
                .collection(FirestoreCollections.publicProfiles)
                .doc(ownerId)
                .update({
              'isHidden': true,
              'hiddenAt': FieldValue.serverTimestamp(),
            });
            AppLogger.info(
                '[ReportService] Admin hid profile $ownerId via report ${report.id}');
            return true;
          },
          operationName: 'Suspend reported profile',
          requiresAuth: true,
        ) ??
        false;
  }

  DocumentReference<Map<String, dynamic>>? _resolveContentRef(
      ContentReport report) {
    switch (report.contentType) {
      case ContentType.recipe:
        // Recipes live under users/{ownerId}/recipes/{recipeId}.
        final ownerId = report.contentOwnerId;
        if (ownerId == null || ownerId.isEmpty) return null;
        return _firestore
            .collection(FirestoreCollections.users)
            .doc(ownerId)
            .collection(FirestoreCollections.userRecipes)
            .doc(report.contentId);
      case ContentType.comment:
        return _firestore
            .collection(FirestoreCollections.recipeComments)
            .doc(report.contentId);
      case ContentType.message:
        return _firestore
            .collection(FirestoreCollections.messages)
            .doc(report.contentId);
      case ContentType.cookSnap:
        return _firestore
            .collection(FirestoreCollections.cookSnaps)
            .doc(report.contentId);
      case ContentType.group:
        // FriendCategory lives under users/{ownerId}/friend_categories/{id};
        // we need the ownerId to resolve the path.
        final groupOwnerId = report.contentOwnerId;
        if (groupOwnerId == null || groupOwnerId.isEmpty) return null;
        return _firestore
            .collection(FirestoreCollections.users)
            .doc(groupOwnerId)
            .collection(FirestoreCollections.userFriendCategories)
            .doc(report.contentId);
      case ContentType.profile:
        // Profile uses a separate primitive — see suspendReportedProfile.
        return null;
    }
  }
}
