// BUT-1491: `ReservedTags._autoGeneratedTags` is a hand-copied literal list of
// the ~120 auto-tags the tagging phase calculators (Phase 1-4) emit. It exists
// so that `PersonalTag` creation can reject any name that collides with a system
// tag. Because that list is maintained by hand, separately from the phase code
// that actually emits the tags, the two can silently drift: add
// `tags.add('nyTagg')` to a phase without also reserving it and a user can then
// create a personal tag `nyTagg` that SHADOWS the auto-tag (isReserved returns
// false). These tests are the drift guard, in both directions:
//
//  * FORWARD  — every tag literal a phase emits must be reserved (the shadowing
//    bug above).
//  * REVERSE  — every reserved auto-generated tag must still correspond to a
//    literal somewhere in the phase sources (catches a reserved entry left
//    behind after a phase tag was renamed/removed, i.e. a dead/typo'd reserve).
//
// The emitted vocabulary is derived by scanning the phase source files rather
// than re-typing it (re-typing would just move the hand-copy problem into the
// test). Extraction targets the exact emit patterns these files use; the floor
// and representative-tag assertions fail loudly if a structural refactor breaks
// a pattern, so a broken scraper can't pass silently.
//
// NOT covered here (covered by construction, so they cannot drift): allergen,
// dietary and cuisine reserved tags are built dynamically in
// `_buildReservedSet` from the SAME AllergenConfig / DietaryConfig /
// CuisineConfig the phases read, so they are always in sync.

import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'package:butlery/services/tagging/config/allergen_config.dart';
import 'package:butlery/services/tagging/config/cuisine_config.dart';
import 'package:butlery/services/tagging/config/dietary_config.dart';
import 'package:butlery/services/tagging/config/reserved_tags.dart';

void main() {
  // The tag-emitting phase calculators. Phase 5 (cuisine) is config-derived and
  // deliberately excluded (see header). Paths are relative to the package root,
  // which is the cwd for `flutter test`.
  const phaseFiles = [
    'lib/services/tagging/phases/tag_phase1_base.dart',
    'lib/services/tagging/phases/tag_phase1_method.dart',
    'lib/services/tagging/phases/tag_phase1_nutrition.dart',
    'lib/services/tagging/phases/tag_phase2_derived.dart',
    'lib/services/tagging/phases/tag_phase3_complex.dart',
    'lib/services/tagging/phases/tag_phase4_mood.dart',
  ];

  // A missing file throws here (loud) rather than silently shrinking coverage.
  final sources = {
    for (final path in phaseFiles) path: File(path).readAsStringSync(),
  };

  // Every single-quoted string literal across the phase sources. Used for the
  // reverse check (a reserved auto-tag must appear as SOME literal). This is a
  // superset that also includes ingredient-matching keywords — fine, because the
  // reverse check only asserts a subset relationship.
  final allLiteral = RegExp(r"'([^'\n]+)'");
  final allLiterals = <String>{
    for (final src in sources.values)
      for (final m in allLiteral.allMatches(src)) m.group(1)!,
  };

  // The emitted-tag vocabulary, extracted per the three emit patterns these
  // files actually use:
  //   1. `tags.add('literal')`                 — the dominant pattern.
  //   2. `'key': [ ... ]` map entries          — Phase 1 dishTypes, added via
  //                                               `tags.add(entry.key)`.
  //   3. `return 'literal'`                     — Phase 3 difficulty
  //                                               (enkel/medel/avancerad).
  final literalAdd = RegExp(r"\.add\(\s*'([^'\n]+)'\s*\)");
  final mapKeyList = RegExp(r"'([^'\n]+)'\s*:\s*\[");
  final stringReturn = RegExp(r"return\s+'([^'\n]+)'");

  final emittedTags = <String>{};
  for (final src in sources.values) {
    for (final m in literalAdd.allMatches(src)) {
      emittedTags.add(m.group(1)!);
    }
    for (final m in mapKeyList.allMatches(src)) {
      emittedTags.add(m.group(1)!);
    }
    for (final m in stringReturn.allMatches(src)) {
      emittedTags.add(m.group(1)!);
    }
  }

  // Reconstruct the config-derived reserved tags (allergen/dietary/cuisine) the
  // same way `_buildReservedSet` does, so subtracting them from ReservedTags.all
  // leaves exactly the hand-maintained auto-generated subset.
  final configDerived = <String>{
    for (final e in DietaryConfig.all) e.tagSv.toLowerCase(),
    for (final e in AllergenConfig.all) ...[
      e.containsTag.toLowerCase(),
      if (e.freeTag != null) e.freeTag!.toLowerCase(),
    ],
    for (final c in CuisineConfig.cuisines) c.tag,
  };
  final autoGeneratedReserved = ReservedTags.all.difference(configDerived);

  group('ReservedTags ↔ phase-calculator drift guard (BUT-1491)', () {
    test('extraction actually fired — each emit pattern is represented', () {
      // Guards against a phase refactor silently breaking a scraper (which would
      // make the forward check vacuously pass).
      expect(
        allLiterals.length,
        greaterThan(150),
        reason: 'phase sources should yield many string literals',
      );
      expect(
        emittedTags.length,
        greaterThan(80),
        reason: 'expected ~110 emitted auto-tags from the phases',
      );
      // One representative tag per extraction path.
      expect(emittedTags, contains('kyckling')); // tags.add('literal')
      expect(emittedTags, contains('soppa')); // dishTypes map key
      expect(emittedTags, contains('enkel')); // difficulty return
      expect(emittedTags, contains('comfort-food')); // Phase 4 literal add
      expect(emittedTags, contains('sommar')); // Phase 4 season fallback
    });

    test(
      'FORWARD: every tag a phase emits is reserved (cannot be shadowed by a '
      'personal tag)',
      () {
        final unreserved = emittedTags.difference(ReservedTags.all);
        expect(
          unreserved,
          isEmpty,
          reason:
              'These tags are emitted by a phase calculator but are NOT in '
              'ReservedTags. A user could create a personal tag with the same '
              'name and shadow the auto-tag. Add them to '
              'ReservedTags._autoGeneratedTags: $unreserved',
        );
      },
    );

    test(
      'REVERSE: every reserved auto-generated tag still appears in the phase '
      'sources (no stale/typo reserves)',
      () {
        final orphaned = autoGeneratedReserved.difference(allLiterals);
        expect(
          orphaned,
          isEmpty,
          reason:
              'These tags are reserved as auto-generated but no phase '
              'calculator mentions them as a literal — likely a rename/removal '
              'left a stale entry (or a typo) in '
              'ReservedTags._autoGeneratedTags: $orphaned',
        );
      },
    );

    test('sanity: a reserved auto-tag really is treated as reserved', () {
      expect(ReservedTags.isReserved('kyckling'), isTrue);
      expect(ReservedTags.isReserved('Kyckling'), isTrue); // case-insensitive
      // A name no phase emits stays available for personal tags.
      expect(ReservedTags.isReserved('mormors-favorit'), isFalse);
    });
  });
}
