// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9gCXL9iNWm-BQbMd1okjVedVN8e5JIE',
    appId: '1:123359108218:web:26bf8ce40cdd7d8e016fc3',
    messagingSenderId: '123359108218',
    projectId: 'butlery-database',
    authDomain: 'butlery-database.firebaseapp.com',
    storageBucket: 'butlery-database.firebasestorage.app',
    measurementId: 'G-3BG94M2KX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vKil6agqVFqU1UfnAkVA3XPq9BPd8Yw',
    appId: '1:123359108218:android:e425e2e2b79a4b7a016fc3',
    messagingSenderId: '123359108218',
    projectId: 'butlery-database',
    storageBucket: 'butlery-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bix6FC1v6Dca-v2aCvOVbWEt_M4Rs44',
    appId: '1:123359108218:ios:8d43baf7adbd6322016fc3',
    messagingSenderId: '123359108218',
    projectId: 'butlery-database',
    storageBucket: 'butlery-database.firebasestorage.app',
    iosBundleId: 'com.example.butlery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6bix6FC1v6Dca-v2aCvOVbWEt_M4Rs44',
    appId: '1:123359108218:ios:8d43baf7adbd6322016fc3',
    messagingSenderId: '123359108218',
    projectId: 'butlery-database',
    storageBucket: 'butlery-database.firebasestorage.app',
    iosBundleId: 'com.example.butlery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe9gCXL9iNWm-BQbMd1okjVedVN8e5JIE',
    appId: '1:123359108218:web:0ea653801d91ed24016fc3',
    messagingSenderId: '123359108218',
    projectId: 'butlery-database',
    authDomain: 'butlery-database.firebaseapp.com',
    storageBucket: 'butlery-database.firebasestorage.app',
    measurementId: 'G-RTZ9SQPR2V',
  );
}
