// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZV38BdC1VBes0N-oiLdk1yi5xS_xKZ8g',
    appId: '1:976357691692:web:3e70520a0ac19514e4dc89',
    messagingSenderId: '976357691692',
    projectId: 'butlery-app-1',
    authDomain: 'butlery-app-1.firebaseapp.com',
    storageBucket: 'butlery-app-1.firebasestorage.app',
    measurementId: 'G-8Z7NX2QXW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmWnBxoQ4CYvvoMMFraZTRRD83qp8kew',
    appId: '1:976357691692:android:4a2e41f5eb04e0c2e4dc89',
    messagingSenderId: '976357691692',
    projectId: 'butlery-app-1',
    storageBucket: 'butlery-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRlLbFsy43gpKQK5aUmrQP2vQ7lAOd8aY',
    appId: '1:976357691692:ios:714dacad784ca7b7e4dc89',
    messagingSenderId: '976357691692',
    projectId: 'butlery-app-1',
    storageBucket: 'butlery-app-1.firebasestorage.app',
    iosBundleId: 'com.example.butlery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRlLbFsy43gpKQK5aUmrQP2vQ7lAOd8aY',
    appId: '1:976357691692:ios:714dacad784ca7b7e4dc89',
    messagingSenderId: '976357691692',
    projectId: 'butlery-app-1',
    storageBucket: 'butlery-app-1.firebasestorage.app',
    iosBundleId: 'com.example.butlery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZV38BdC1VBes0N-oiLdk1yi5xS_xKZ8g',
    appId: '1:976357691692:web:2b6a8efd2740a521e4dc89',
    messagingSenderId: '976357691692',
    projectId: 'butlery-app-1',
    authDomain: 'butlery-app-1.firebaseapp.com',
    storageBucket: 'butlery-app-1.firebasestorage.app',
    measurementId: 'G-SK8VB3DFE0',
  );

}