import 'package:butlery/core/utils/serialization_utils.dart';
import 'package:butlery/models/tagging/tri_state.dart';

/// User-applied overrides to auto-generated tag results.
///
/// Allows users to correct allergen/dietary status when they know
/// better than the automated tagging system. Overrides persist
/// across retagging operations to preserve user intent.
///
/// Safety features:
/// - Removing allergen CONTAINS status requires confirmation
/// - Shows "manually edited" indicator when overrides exist
/// - Stores separate from TagResult so auto-retagging doesn't clear
class TagOverrides {
  /// User corrections to allergen status.
  /// Key: allergen identifier (e.g., 'gluten', 'dairy')
  /// Value: user-specified status overriding auto-generated
  final Map<String, TriState> allergenOverrides;

  /// User corrections to dietary status.
  /// Key: dietary identifier (e.g., 'vegetarisk', 'vegansk')
  /// Value: user-specified status overriding auto-generated
  final Map<String, TriState> dietaryOverrides;

  /// Tags manually added by user (not auto-generated).
  final Set<String> addedTags;

  /// Tags removed by user (hide from display even if auto-generated).
  final Set<String> removedTags;

  /// When the last manual edit was made.
  final DateTime? lastEditedAt;

  /// Who made the last edit (user ID for audit trail).
  final String? lastEditedBy;

  const TagOverrides({
    this.allergenOverrides = const {},
    this.dietaryOverrides = const {},
    this.addedTags = const {},
    this.removedTags = const {},
    this.lastEditedAt,
    this.lastEditedBy,
  });

  /// Returns true if any manual edits have been made.
  bool get hasManualEdits =>
      allergenOverrides.isNotEmpty ||
      dietaryOverrides.isNotEmpty ||
      addedTags.isNotEmpty ||
      removedTags.isNotEmpty;

  /// Returns true if a specific allergen has been overridden.
  bool hasAllergenOverride(String allergenKey) =>
      allergenOverrides.containsKey(allergenKey);

  /// Returns true if a specific dietary status has been overridden.
  bool hasDietaryOverride(String dietaryKey) =>
      dietaryOverrides.containsKey(dietaryKey);

  /// Gets the effective allergen status, applying override if present.
  TriState getEffectiveAllergenStatus(
    String allergenKey,
    TriState autoGenerated,
  ) {
    return allergenOverrides[allergenKey] ?? autoGenerated;
  }

  /// Gets the effective dietary status, applying override if present.
  TriState getEffectiveDietaryStatus(
    String dietaryKey,
    TriState autoGenerated,
  ) {
    return dietaryOverrides[dietaryKey] ?? autoGenerated;
  }

  /// Gets the effective tags, applying additions and removals.
  Set<String> getEffectiveTags(Set<String> autoGeneratedTags) {
    return autoGeneratedTags.union(addedTags).difference(removedTags);
  }

  /// Creates a copy with the specified changes.
  TagOverrides copyWith({
    Map<String, TriState>? allergenOverrides,
    Map<String, TriState>? dietaryOverrides,
    Set<String>? addedTags,
    Set<String>? removedTags,
    DateTime? lastEditedAt,
    String? lastEditedBy,
  }) {
    return TagOverrides(
      allergenOverrides: allergenOverrides ?? this.allergenOverrides,
      dietaryOverrides: dietaryOverrides ?? this.dietaryOverrides,
      addedTags: addedTags ?? this.addedTags,
      removedTags: removedTags ?? this.removedTags,
      lastEditedAt: lastEditedAt ?? this.lastEditedAt,
      lastEditedBy: lastEditedBy ?? this.lastEditedBy,
    );
  }

  /// Creates with a single allergen override added/updated.
  TagOverrides withAllergenOverride(
    String allergenKey,
    TriState status, {
    required String editedBy,
  }) {
    final newOverrides = Map<String, TriState>.from(allergenOverrides);
    newOverrides[allergenKey] = status;
    return copyWith(
      allergenOverrides: newOverrides,
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Creates with a single dietary override added/updated.
  TagOverrides withDietaryOverride(
    String dietaryKey,
    TriState status, {
    required String editedBy,
  }) {
    final newOverrides = Map<String, TriState>.from(dietaryOverrides);
    newOverrides[dietaryKey] = status;
    return copyWith(
      dietaryOverrides: newOverrides,
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Creates with a tag added.
  TagOverrides withTagAdded(String tag, {required String editedBy}) {
    final newAdded = Set<String>.from(addedTags)..add(tag);
    final newRemoved = Set<String>.from(removedTags)..remove(tag);
    return copyWith(
      addedTags: newAdded,
      removedTags: newRemoved,
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Creates with a tag removed.
  TagOverrides withTagRemoved(String tag, {required String editedBy}) {
    final newRemoved = Set<String>.from(removedTags)..add(tag);
    final newAdded = Set<String>.from(addedTags)..remove(tag);
    return copyWith(
      addedTags: newAdded,
      removedTags: newRemoved,
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Removes an allergen override (reverts to auto-generated).
  TagOverrides withoutAllergenOverride(
    String allergenKey, {
    required String editedBy,
  }) {
    final newOverrides = Map<String, TriState>.from(allergenOverrides)
      ..remove(allergenKey);
    return copyWith(
      allergenOverrides: newOverrides,
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Removes a dietary override (reverts to auto-generated).
  TagOverrides withoutDietaryOverride(
    String dietaryKey, {
    required String editedBy,
  }) {
    final newOverrides = Map<String, TriState>.from(dietaryOverrides)
      ..remove(dietaryKey);
    return copyWith(
      dietaryOverrides: newOverrides,
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Clears all overrides.
  TagOverrides cleared({required String editedBy}) {
    return TagOverrides(
      lastEditedAt: DateTime.now(),
      lastEditedBy: editedBy,
    );
  }

  /// Converts to JSON for storage.
  Map<String, dynamic> toJson() {
    return {
      'allergenOverrides': allergenOverrides.map(
        (k, v) => MapEntry(k, v.name),
      ),
      'dietaryOverrides': dietaryOverrides.map(
        (k, v) => MapEntry(k, v.name),
      ),
      'addedTags': addedTags.toList(),
      'removedTags': removedTags.toList(),
      if (lastEditedAt != null) 'lastEditedAt': lastEditedAt!.toIso8601String(),
      if (lastEditedBy != null) 'lastEditedBy': lastEditedBy,
    };
  }

  /// Creates from JSON data.
  factory TagOverrides.fromJson(Map<String, dynamic>? data) {
    if (data == null) return const TagOverrides();

    return TagOverrides(
      allergenOverrides: _parseTriStateMap(data['allergenOverrides']),
      dietaryOverrides: _parseTriStateMap(data['dietaryOverrides']),
      addedTags: _parseStringSet(data['addedTags']),
      removedTags: _parseStringSet(data['removedTags']),
      lastEditedAt: SerializationUtils.safeDateTime(data, 'lastEditedAt'),
      lastEditedBy: SerializationUtils.safeNullableString(data, 'lastEditedBy'),
    );
  }

  static Map<String, TriState> _parseTriStateMap(dynamic data) {
    if (data == null || data is! Map) return {};
    final result = <String, TriState>{};
    for (final entry in data.entries) {
      final key = entry.key.toString();
      final value = TriStateParsing.fromString(entry.value?.toString());
      if (value != null) {
        result[key] = value;
      }
    }
    return result;
  }

  static Set<String> _parseStringSet(dynamic data) {
    if (data == null || data is! List) return {};
    return data.map((e) => e.toString()).toSet();
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! TagOverrides) return false;
    return _mapEquals(allergenOverrides, other.allergenOverrides) &&
        _mapEquals(dietaryOverrides, other.dietaryOverrides) &&
        _setEquals(addedTags, other.addedTags) &&
        _setEquals(removedTags, other.removedTags) &&
        lastEditedAt == other.lastEditedAt &&
        lastEditedBy == other.lastEditedBy;
  }

  @override
  int get hashCode => Object.hash(
        Object.hashAll(allergenOverrides.entries),
        Object.hashAll(dietaryOverrides.entries),
        Object.hashAll(addedTags),
        Object.hashAll(removedTags),
        lastEditedAt,
        lastEditedBy,
      );

  static bool _mapEquals<K, V>(Map<K, V> a, Map<K, V> b) {
    if (a.length != b.length) return false;
    for (final key in a.keys) {
      if (!b.containsKey(key) || a[key] != b[key]) return false;
    }
    return true;
  }

  static bool _setEquals<T>(Set<T> a, Set<T> b) {
    if (a.length != b.length) return false;
    return a.containsAll(b);
  }

  @override
  String toString() {
    return 'TagOverrides('
        'allergenOverrides: $allergenOverrides, '
        'dietaryOverrides: $dietaryOverrides, '
        'addedTags: $addedTags, '
        'removedTags: $removedTags, '
        'hasManualEdits: $hasManualEdits)';
  }
}
