// Mocks generated by Mockito 5.4.5 from annotations
// in butlery/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:butlery/models/friend_request.dart' as _i10;
import 'package:butlery/models/recipe.dart' as _i6;
import 'package:butlery/models/shopping_item.dart' as _i5;
import 'package:butlery/models/shopping_list.dart' as _i3;
import 'package:butlery/models/user_profile.dart' as _i9;
import 'package:butlery/services/friends_service.dart' as _i8;
import 'package:butlery/services/multi_shopping_list_service.dart' as _i2;
import 'package:butlery/services/share_service.dart' as _i11;
import 'package:butlery/viewmodels/shopping_list_viewmodel.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MultiShoppingListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiShoppingListService extends _i1.Mock
    implements _i2.MultiShoppingListService {
  MockMultiShoppingListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ShoppingList> get lists => (super.noSuchMethod(
        Invocation.getter(#lists),
        returnValue: <_i3.ShoppingList>[],
      ) as List<_i3.ShoppingList>);

  @override
  bool get hasLists => (super.noSuchMethod(
        Invocation.getter(#hasLists),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.ShoppingList?> createList(
    String? name, {
    List<_i5.ShoppingItem>? items,
    bool? setAsActive = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createList,
          [name],
          {
            #items: items,
            #setAsActive: setAsActive,
          },
        ),
        returnValue: _i4.Future<_i3.ShoppingList?>.value(),
      ) as _i4.Future<_i3.ShoppingList?>);

  @override
  _i4.Future<_i3.ShoppingList?> createListFromMenu(
    String? name,
    Map<String, List<_i6.Recipe>>? menu,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListFromMenu,
          [
            name,
            menu,
          ],
        ),
        returnValue: _i4.Future<_i3.ShoppingList?>.value(),
      ) as _i4.Future<_i3.ShoppingList?>);

  @override
  _i4.Future<bool> generateFromMenuToActiveList(
          Map<String, List<_i6.Recipe>>? menu) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromMenuToActiveList,
          [menu],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> renameList(
    String? listId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameList,
          [
            listId,
            newName,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setActiveList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #setActiveList,
          [listId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> updateItemInActiveList(
    int? index,
    _i5.ShoppingItem? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemInActiveList,
          [
            index,
            item,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> addItemToActiveList(_i5.ShoppingItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItemToActiveList,
          [item],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> toggleItemBought(int? index) => (super.noSuchMethod(
        Invocation.method(
          #toggleItemBought,
          [index],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeItemFromActiveList(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeItemFromActiveList,
          [index],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearBoughtItems() => (super.noSuchMethod(
        Invocation.method(
          #clearBoughtItems,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> uncheckAllItems() => (super.noSuchMethod(
        Invocation.method(
          #uncheckAllItems,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void updateActiveList(_i3.ShoppingList? updatedList) => super.noSuchMethod(
        Invocation.method(
          #updateActiveList,
          [updatedList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> syncAllLists() => (super.noSuchMethod(
        Invocation.method(
          #syncAllLists,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FriendsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsService extends _i1.Mock implements _i8.FriendsService {
  MockFriendsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.UserProfile> get friends => (super.noSuchMethod(
        Invocation.getter(#friends),
        returnValue: <_i9.UserProfile>[],
      ) as List<_i9.UserProfile>);

  @override
  List<_i10.FriendRequest> get incomingRequests => (super.noSuchMethod(
        Invocation.getter(#incomingRequests),
        returnValue: <_i10.FriendRequest>[],
      ) as List<_i10.FriendRequest>);

  @override
  List<_i10.FriendRequest> get sentRequests => (super.noSuchMethod(
        Invocation.getter(#sentRequests),
        returnValue: <_i10.FriendRequest>[],
      ) as List<_i10.FriendRequest>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  int get friendsCount => (super.noSuchMethod(
        Invocation.getter(#friendsCount),
        returnValue: 0,
      ) as int);

  @override
  int get pendingRequestsCount => (super.noSuchMethod(
        Invocation.getter(#pendingRequestsCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> sendFriendRequest(
    String? toUserId, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [toUserId],
          {#message: message},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> rejectFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeFriend(String? friendUserId) => (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [friendUserId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> cancelSentRequest(String? requestId) => (super.noSuchMethod(
        Invocation.method(
          #cancelSentRequest,
          [requestId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> areFriends(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #areFriends,
          [
            userId1,
            userId2,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i9.UserProfile>> getMutualFriends(String? otherUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMutualFriends,
          [otherUserId],
        ),
        returnValue:
            _i4.Future<List<_i9.UserProfile>>.value(<_i9.UserProfile>[]),
      ) as _i4.Future<List<_i9.UserProfile>>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadFriends() => (super.noSuchMethod(
        Invocation.method(
          #loadFriends,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareService extends _i1.Mock implements _i11.ShareService {
  MockShareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String formatRecipeComplete(_i6.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #formatRecipeComplete,
          [recipe],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatRecipeComplete,
            [recipe],
          ),
        ),
      ) as String);

  @override
  String formatRecipeCompact(_i6.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #formatRecipeCompact,
          [recipe],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatRecipeCompact,
            [recipe],
          ),
        ),
      ) as String);

  @override
  String formatRecipeMarkdown(_i6.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #formatRecipeMarkdown,
          [recipe],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatRecipeMarkdown,
            [recipe],
          ),
        ),
      ) as String);

  @override
  String formatShoppingList(List<_i5.ShoppingItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #formatShoppingList,
          [items],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatShoppingList,
            [items],
          ),
        ),
      ) as String);

  @override
  String formatShoppingListGrouped(
          Map<String, List<_i5.ShoppingItem>>? groupedItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #formatShoppingListGrouped,
          [groupedItems],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatShoppingListGrouped,
            [groupedItems],
          ),
        ),
      ) as String);

  @override
  String formatWeekMenu(Map<String, _i6.Recipe?>? weekMenu) =>
      (super.noSuchMethod(
        Invocation.method(
          #formatWeekMenu,
          [weekMenu],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatWeekMenu,
            [weekMenu],
          ),
        ),
      ) as String);

  @override
  String getSmartFormat(_i6.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #getSmartFormat,
          [recipe],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getSmartFormat,
            [recipe],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> shareRecipe(_i6.Recipe? recipe) => (super.noSuchMethod(
        Invocation.method(
          #shareRecipe,
          [recipe],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> shareRecipeWithFormat(
    _i6.Recipe? recipe,
    _i11.RecipeShareFormat? format,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareRecipeWithFormat,
          [
            recipe,
            format,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> shareShoppingList(List<_i5.ShoppingItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareShoppingList,
          [items],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> shareWeekMenuFromCategories(
          Map<String, List<_i6.Recipe>>? menu) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareWeekMenuFromCategories,
          [menu],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getFormattedRecipe(
    _i6.Recipe? recipe, {
    _i11.RecipeShareFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormattedRecipe,
          [recipe],
          {#format: format},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedRecipe,
            [recipe],
            {#format: format},
          ),
        ),
      ) as String);

  @override
  String getFormattedShoppingList(List<_i5.ShoppingItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormattedShoppingList,
          [items],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedShoppingList,
            [items],
          ),
        ),
      ) as String);

  @override
  String getFormattedWeekMenuFromCategories(
          Map<String, List<_i6.Recipe>>? menu) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormattedWeekMenuFromCategories,
          [menu],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedWeekMenuFromCategories,
            [menu],
          ),
        ),
      ) as String);

  @override
  String formatWeekMenuFromCategories(Map<String, List<_i6.Recipe>>? menu) =>
      (super.noSuchMethod(
        Invocation.method(
          #formatWeekMenuFromCategories,
          [menu],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #formatWeekMenuFromCategories,
            [menu],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> copyToClipboard(String? text) => (super.noSuchMethod(
        Invocation.method(
          #copyToClipboard,
          [text],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> copyRecipe(
    _i6.Recipe? recipe, {
    _i11.RecipeShareFormat? format,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyRecipe,
          [recipe],
          {#format: format},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ShoppingListViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListViewModel extends _i1.Mock
    implements _i13.ShoppingListViewModel {
  MockShoppingListViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ShoppingList> get lists => (super.noSuchMethod(
        Invocation.getter(#lists),
        returnValue: <_i3.ShoppingList>[],
      ) as List<_i3.ShoppingList>);

  @override
  List<_i5.ShoppingItem> get shoppingItems => (super.noSuchMethod(
        Invocation.getter(#shoppingItems),
        returnValue: <_i5.ShoppingItem>[],
      ) as List<_i5.ShoppingItem>);

  @override
  List<_i5.ShoppingItem> get unboughtItems => (super.noSuchMethod(
        Invocation.getter(#unboughtItems),
        returnValue: <_i5.ShoppingItem>[],
      ) as List<_i5.ShoppingItem>);

  @override
  List<_i5.ShoppingItem> get boughtItems => (super.noSuchMethod(
        Invocation.getter(#boughtItems),
        returnValue: <_i5.ShoppingItem>[],
      ) as List<_i5.ShoppingItem>);

  @override
  bool get hasLists => (super.noSuchMethod(
        Invocation.getter(#hasLists),
        returnValue: false,
      ) as bool);

  @override
  bool get hasItems => (super.noSuchMethod(
        Invocation.getter(#hasItems),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isCreatingList => (super.noSuchMethod(
        Invocation.getter(#isCreatingList),
        returnValue: false,
      ) as bool);

  @override
  bool get isChangingList => (super.noSuchMethod(
        Invocation.getter(#isChangingList),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  int get totalCount => (super.noSuchMethod(
        Invocation.getter(#totalCount),
        returnValue: 0,
      ) as int);

  @override
  int get checkedCount => (super.noSuchMethod(
        Invocation.getter(#checkedCount),
        returnValue: 0,
      ) as int);

  @override
  int get uncheckedCount => (super.noSuchMethod(
        Invocation.getter(#uncheckedCount),
        returnValue: 0,
      ) as int);

  @override
  bool get allItemsChecked => (super.noSuchMethod(
        Invocation.getter(#allItemsChecked),
        returnValue: false,
      ) as bool);

  @override
  bool get needsSync => (super.noSuchMethod(
        Invocation.getter(#needsSync),
        returnValue: false,
      ) as bool);

  @override
  List<String> get formattedItems => (super.noSuchMethod(
        Invocation.getter(#formattedItems),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i13.DropdownItem> get listDropdownItems => (super.noSuchMethod(
        Invocation.getter(#listDropdownItems),
        returnValue: <_i13.DropdownItem>[],
      ) as List<_i13.DropdownItem>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int getOriginalIndex(_i5.ShoppingItem? item) => (super.noSuchMethod(
        Invocation.method(
          #getOriginalIndex,
          [item],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> selectList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #selectList,
          [listId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> createList(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createList,
          [name],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> createListFromMenu(
    String? name,
    Map<String, List<_i6.Recipe>>? menu,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListFromMenu,
          [
            name,
            menu,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> renameList(
    String? listId,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameList,
          [
            listId,
            newName,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> generateFromMenu(Map<String, List<_i6.Recipe>>? menu) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateFromMenu,
          [menu],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> addItem(_i5.ShoppingItem? item) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [item],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> toggleItem(int? index) => (super.noSuchMethod(
        Invocation.method(
          #toggleItem,
          [index],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> removeItem(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [index],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> undoRemove() => (super.noSuchMethod(
        Invocation.method(
          #undoRemove,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCheckedItems() => (super.noSuchMethod(
        Invocation.method(
          #clearCheckedItems,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uncheckAllItems() => (super.noSuchMethod(
        Invocation.method(
          #uncheckAllItems,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void insertItem(
    int? index,
    _i5.ShoppingItem? item,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insertItem,
          [
            index,
            item,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateItem(
    int? index,
    _i5.ShoppingItem? updated,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [
            index,
            updated,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> forceSync() => (super.noSuchMethod(
        Invocation.method(
          #forceSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadLists() => (super.noSuchMethod(
        Invocation.method(
          #loadLists,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String exportAsText() => (super.noSuchMethod(
        Invocation.method(
          #exportAsText,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #exportAsText,
            [],
          ),
        ),
      ) as String);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i14.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i4.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
