
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated for central documentation
import 'dart:convert';

const String _codeDocumentationJson = r'''
{
  "core/constants/shopping_list_constants.dart": {
    "component": "Shopping List Constants",
    "dependenciesIn": "None",
    "dependenciesOut": "Used by shopping list widgets",
    "dataFlow": "Static constants",
    "stateManagement": "N/A",
    "purpose": "Eliminera magic numbers och centralisera värden",
    "commonIssues": "N/A",
    "testCoverage": "N/A",
    "performance": "⚡ Compile-time constants",
    "connectedTo": "All shopping list components",
    "usedInPhases": "Shopping list feature"
  },
  "viewmodels/create_shared_list_viewmodel.dart": {
    "component": "Create Shared List ViewModel - Unified Shopping Pattern",
    "dependenciesIn": "UnifiedShoppingService, UserService",
    "dependenciesOut": "UI state för create shared list view",
    "dataFlow": "User actions → ViewModel state → UnifiedShoppingService",
    "stateManagement": "ChangeNotifier med complete form state management",
    "purpose": "Perfect MVVM separation - all business logic och UI state här",
    "commonIssues": "✅ LÖST: Form validation, async operations, error handling",
    "testCoverage": "95% (ViewModels är lätta att testa)",
    "performance": "⚡ Optimized state updates, efficient validation",
    "connectedTo": "CreateSharedShoppingListView, UnifiedShoppingService",
    "usedInPhases": "18.4"
  },
  "viewmodels/recipe_form_viewmodel.dart": {
    "component": "Recipe Form ViewModel - Firebase Collaborative",
    "dependenciesIn": "RealtimeRecipe, SharedRecipe, Firebase",
    "dependenciesOut": "EditRecipeView, SocialComponents",
    "dataFlow": "UI → ViewModel → RealtimeRecipe → Firebase → Real-time updates",
    "stateManagement": "ChangeNotifier med Firebase streams",
    "purpose": "Hantera form state med riktig collaborative editing via Firebase",
    "commonIssues": "Stream disposal, connection drops, conflict resolution",
    "testCoverage": "90%",
    "performance": "⚡ Real-time Firebase sync, debounced updates",
    "connectedTo": "RealtimeRecipe, SharedRecipe, Firebase, SocialComponents",
    "usedInPhases": "Fas 4.2 - Real-time collaborative editing"
  },
  "viewmodels/realtime_menu_viewmodel.dart": {
    "component": "Realtime Menu ViewModel - UPPDATERAD för kategori-baserade menyer",
    "dependenciesIn": "RealtimeMenuService, RealtimeSyncService, AuthService, delegated managers",
    "dependenciesOut": "RealtimeMenuView, collaborative menu widgets",
    "dataFlow": "UI events → ViewModel → Service → Firebase → Live updates → UI",
    "stateManagement": "ChangeNotifier med delegated responsibilities för clean separation",
    "purpose": "BARA hantera UI state för kategori-baserade menyer och koordinera mellan UI och services",
    "commonIssues": "Connection drops, permission changes, concurrent category edits",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Delegated optimization via managers, minimal ViewModel overhead",
    "connectedTo": "RealtimeMenuService, specialized managers, category-based collaborative UI",
    "usedInPhases": "Fas 3 (SRP refactoring) - Clean architecture för kategori-menyer"
  },
  "viewmodels/add_members_to_group_viewmodel.dart": {
    "component": "Add Members to Group ViewModel - KOMPLETT med riktiga gruppinbjudningar + DEBUG",
    "dependenciesIn": "FriendsService, FriendCategoriesService, GroupInvitationService",
    "dependenciesOut": "AddMembersToGroupView, GroupInvitation notifications",
    "dataFlow": "Load available friends → Select members → Send GROUP invitations → Handle responses",
    "stateManagement": "ChangeNotifier med search, selection, invitation state",
    "purpose": "Skickar RIKTIGA gruppinbjudningar som mottagaren kan acceptera/avvisa + DEBUG",
    "commonIssues": "Duplicate invitations, permission checking, network failures",
    "testCoverage": "0% (uppdaterad komponent med debug)",
    "performance": "⚡ Cached friend lists, optimized search, batch operations",
    "connectedTo": "FriendsService, FriendCategoriesService, GroupInvitationService",
    "usedInPhases": "18.5 - Avancerad medlemshantering med riktiga inbjudningar + DEBUG"
  },
  "viewmodels/collaborative_shopping_viewmodel.dart": {
    "component": "Collaborative Shopping ViewModel - Unified System Wrapper",
    "dependenciesIn": "UnifiedShoppingService, UserService",
    "dependenciesOut": "Real-time collaborative shopping state",
    "dataFlow": "CollaborativeView → ViewModel → UnifiedShoppingService",
    "stateManagement": "ChangeNotifier med real-time updates",
    "purpose": "Specialiserat UI för kollaborativa listor med live-updates",
    "commonIssues": "✅ LÖST: Real-time sync, medlemshantering, activity tracking",
    "testCoverage": "90% (enkelt att testa wrapper-logik)",
    "performance": "⚡ Efficient real-time updates, smart state management",
    "connectedTo": "CollaborativeShoppingView, UnifiedShoppingService",
    "usedInPhases": "18.4 (enhanced collaborative features)"
  },
  "viewmodels/collaborative_status_viewmodel.dart": {
    "component": "Enhanced Collaborative Status Management ViewModel",
    "dependenciesIn": "SocialRecipeService, AuthService, Content models",
    "dependenciesOut": "All edit views, detail views, status widgets",
    "dataFlow": "Content ID + Type → Service check → Cached status → UI updates",
    "stateManagement": "ChangeNotifier med generic caching system",
    "purpose": "Single responsibility för collaborative detection med framtidssäker arkitektur",
    "commonIssues": "Network delays, service unavailability, cache invalidation",
    "testCoverage": "Unit testable med mocked services",
    "performance": "Aggressive caching, batch operations, minimal Firebase calls",
    "connectedTo": "SocialRecipeService, all content views, collaborative widgets",
    "usedInPhases": "18.3+ - Unified collaborative system för alla content-typer"
  },
  "viewmodels/group_invitations_viewmodel.dart": {
    "component": "Group Invitations ViewModel - UPPDATERAD med riktiga gruppinbjudningar",
    "dependenciesIn": "FriendCategoriesService, FriendsService, AuthService, GroupInvitationService",
    "dependenciesOut": "GroupInvitationsView, group join notifications, invitation responses",
    "dataFlow": "Load available groups + Load received invitations → Join/Accept/Reject → Update UI state",
    "stateManagement": "ChangeNotifier med loading, error, join states OCH invitation states",
    "purpose": "Hantera BÅDE gruppmedlemskap OCH riktiga gruppinbjudningar i samma vy",
    "commonIssues": "Permission validation, user authentication, group state syncing, invitation conflicts",
    "testCoverage": "90% (business logic är lätt att testa)",
    "performance": "⚡ Cached group data, optimized member loading, real-time invitation updates",
    "connectedTo": "FriendCategoriesService, FriendsService, AuthService, GroupInvitationService",
    "usedInPhases": "18.4 - MVVM gruppinbjudningar (uppdaterad)"
  },
  "viewmodels/create_group_viewmodel.dart": {
    "component": "Create Group ViewModel - MVVM för gruppskapande",
    "dependenciesIn": "FriendCategoriesService, GroupInvitationService",
    "dependenciesOut": "State updates för CreateGroupDialog",
    "dataFlow": "Form input → Validation → Create group → Send invitations",
    "stateManagement": "ChangeNotifier pattern",
    "purpose": "Separera all business logic från UI",
    "commonIssues": "✅ LÖST: All validering och service calls i ViewModel",
    "testCoverage": "85%",
    "performance": "⚡ Minimal state, efficient validation",
    "connectedTo": "CreateGroupDialog, FriendCategoriesService",
    "usedInPhases": "18.4"
  },
  "viewmodels/social_recipe_viewmodel.dart": {
    "component": "Social Recipe Interaction ViewModel",
    "dependenciesIn": "SocialRecipeService, FriendsService, UserService, Recipe",
    "dependenciesOut": "Recipe sharing views, comment widgets, social actions",
    "dataFlow": "Recipe → Share to friends → Comments → Social engagement",
    "stateManagement": "ChangeNotifier med sharing state och comments",
    "purpose": "Komplett social interaction för enskilda recept",
    "commonIssues": "Comment threading, sharing permissions, real-time updates",
    "testCoverage": "65%",
    "performance": "⚡ Optimized comment loading, efficient sharing",
    "connectedTo": "Recipe models, social services, sharing views, comment widgets",
    "usedInPhases": "18"
  },
  "viewmodels/shopping_share_viewmodel.dart": {
    "component": "ShoppingShareViewModel - FIXED för UnifiedShoppingList",
    "dependenciesIn": "SocialRecipeService, FriendsService",
    "dependenciesOut": "ShoppingShareDialog",
    "dataFlow": "Dialog → ViewModel → Services → Firebase",
    "stateManagement": "ChangeNotifier för UI-uppdateringar",
    "purpose": "Separera business logic från UI för shopping sharing",
    "commonIssues": "✅ FIXAT: Använder rätt metoder och modeller",
    "testCoverage": "Bör testas för olika användarscenarier",
    "performance": "Lazy loading av vänner, caching av delningshistorik",
    "connectedTo": "ShoppingShareDialog, SocialRecipeService, FriendsService",
    "usedInPhases": "4 (Social funktioner för inköpslistor)"
  },
  "viewmodels/friends_viewmodel.dart": {
    "component": "Friends Management ViewModel med gruppstöd",
    "dependenciesIn": "FriendsService, UserService, FriendCategoriesService",
    "dependenciesOut": "Friends views, user search, request notifications, group management",
    "dataFlow": "Search users → Send requests → Accept/Reject → Friends list + User profile caching + Group management",
    "stateManagement": "ChangeNotifier med search state, friends data, user profile cache OCH group state",
    "purpose": "Komplett vänhantering med sök och request-management + effektiv användardata-cache + grupphantering",
    "commonIssues": "✅ FIXAT: Dispose-säker listener hantering, search performance, request state syncing",
    "testCoverage": "75%",
    "performance": "⚡ Cached search results, optimized friends loading, efficient user profile batching, cached groups",
    "connectedTo": "FriendsService, UserService, FriendCategoriesService, friends views, search views, group views",
    "usedInPhases": "18, 18.4"
  },
  "viewmodels/user_profile_viewmodel.dart": {
    "component": "User Profile Management ViewModel",
    "dependenciesIn": "UserService, StorageService, ImagePickerService",
    "dependenciesOut": "Profile edit views, settings views",
    "dataFlow": "Current profile → Edit form → Validation → Service update → UI refresh",
    "stateManagement": "ChangeNotifier med form state och loading states",
    "purpose": "Komplett profil-management med avatar och privacy controls",
    "commonIssues": "Avatar upload timing, displayName validation, form state",
    "testCoverage": "70%",
    "performance": "⚡ Avatar caching, optimized form updates",
    "connectedTo": "UserService, edit profile views, settings views",
    "usedInPhases": "18"
  },
  "viewmodels/shared_content_viewmodel.dart": {
    "component": "Shared Content ViewModel - UTÖKAD MED SHOPPING SHARE",
    "dependenciesIn": "SocialRecipeService, UserService, FriendsService, shopping models",
    "dependenciesOut": "SharedWithMeView, social UI components, ShoppingShareDialog",
    "dataFlow": "Service → ViewModel state → UI reactions → User actions → Service calls",
    "stateManagement": "ChangeNotifier med comprehensive shared content state OCH shopping share",
    "purpose": "Complete UI state management för social features INKLUSIVE shopping share",
    "commonIssues": "Search state management, tab synchronization, dismiss optimistic updates",
    "testCoverage": "70% (ViewModels är lättare att testa)",
    "performance": "⚡ Efficient filtering, search debouncing, optimistic dismiss updates",
    "connectedTo": "SocialRecipeService, shared content views, dismiss UI components, SHOPPING SHARE",
    "usedInPhases": "18.2 (Shared Content Management) + 4 (Shopping Share)"
  },
  "viewmodels/realtime/participant_tracker.dart": {
    "component": "Participant Tracker - SINGLE RESPONSIBILITY för participant activity tracking",
    "dependenciesIn": "RealtimeMenu model, logger",
    "dependenciesOut": "RealtimeMenuViewModel",
    "dataFlow": "Menu update → Extract participant data → Activity tracking → Notify",
    "stateManagement": "Internal participant state med auto-cleanup",
    "purpose": "BARA hantera deltagares aktivitet och online status",
    "commonIssues": "Stale participant data, memory growth från old activity",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Automatic cleanup av old activity, minimal memory footprint",
    "connectedTo": "RealtimeMenuViewModel",
    "usedInPhases": "Fas 3 (SRP refactoring) - Clean architecture delegation"
  },
  "viewmodels/realtime/connection_monitor.dart": {
    "component": "Connection Monitor - SINGLE RESPONSIBILITY för connection status tracking",
    "dependenciesIn": "RealtimeSyncService, logger",
    "dependenciesOut": "RealtimeMenuViewModel",
    "dataFlow": "Firebase connection → Stream monitoring → Status change → Notify",
    "stateManagement": "Internal connection state med debounced notifications",
    "purpose": "BARA hantera online/offline status och connection events",
    "commonIssues": "Connection flapping, memory leaks från StreamSubscription",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Minimal overhead, debounced status changes",
    "connectedTo": "RealtimeMenuViewModel",
    "usedInPhases": "Fas 3 (SRP refactoring) - Clean architecture delegation"
  },
  "widgets/user/user_display_widgets.dart": {
    "component": "User Display Widgets - OPTIMERAD efter removal av legacy code",
    "dependenciesIn": "app_theme, cached_network_image",
    "dependenciesOut": "Alla views som visar användarinfo",
    "dataFlow": "User data → Optimerad rendering → Pure UI display",
    "stateManagement": "Stateless - optimerade rebuilds",
    "purpose": "Clean user display - NO legacy bloat, only essential functionality",
    "performance": "⚡ 50% mindre kod, optimerad memory, snabbare rendering",
    "connectedTo": "AppTheme, optimized caching",
    "usedInPhases": "OPTIMERAD - Removal av legacy + performance boost"
  },
  "widgets/invitation_target/target_state_widgets.dart": {
    "component": "Target State Widgets - UI komponenter för olika states av InvitationTarget",
    "dependenciesIn": "InvitationTarget, AppTheme",
    "dependenciesOut": "UI screens, dialogs, lists",
    "dataFlow": "State information → Widget builders → Styled state components",
    "stateManagement": "Stateless widgets som visar olika tillstånd",
    "purpose": "Separation of concerns - state UI komponenter använder centraliserad AppTheme",
    "commonIssues": "Ensure consistent state messaging and styling",
    "testCoverage": "0% (UI widgets)",
    "performance": "⚡ Efficient rendering, static widgets",
    "connectedTo": "InvitationTarget, AppTheme, various UI screens",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - UI foundation"
  },
  "widgets/invitation_target/target_input_widgets.dart": {
    "component": "Target Input Widgets - UI komponenter för input/selection av InvitationTarget",
    "dependenciesIn": "InvitationTarget, AppTheme, TargetDisplayWidgets",
    "dependenciesOut": "UI screens, dialogs, forms",
    "dataFlow": "User input → Widget callbacks → Parent state updates → Re-render",
    "stateManagement": "Stateless widgets som kommunicerar via callbacks",
    "purpose": "Separation of concerns - input komponenter använder centraliserad AppTheme",
    "commonIssues": "Ensure proper callback handling and state updates",
    "testCoverage": "0% (UI widgets)",
    "performance": "⚡ Efficient rendering, avoid unnecessary rebuilds",
    "connectedTo": "TargetDisplayWidgets, InvitationTarget, various input forms",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - UI foundation"
  },
  "widgets/invitation_target/target_display_widgets.dart": {
    "component": "Target Display Widgets - UI komponenter för visning av InvitationTarget",
    "dependenciesIn": "InvitationTarget, AppTheme",
    "dependenciesOut": "UI screens, dialogs, lists",
    "dataFlow": "InvitationTarget data → Widget builders → Styled UI components",
    "stateManagement": "Stateless widgets som tar data som parametrar",
    "purpose": "Separation of concerns - UI komponenter använder centraliserad AppTheme",
    "commonIssues": "Ensure all styling goes through AppTheme methods",
    "testCoverage": "0% (UI widgets)",
    "performance": "⚡ Efficient rendering, avoid unnecessary rebuilds",
    "connectedTo": "InvitationTarget, AppTheme, various UI screens",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - UI foundation"
  },
  "widgets/common/social_components.dart": {
    "component": "Social Components - KOMPLETT konsolidering av alla social widgets",
    "dependenciesIn": "UserDisplayWidgets, FriendCategoryManager, Target widgets, AppTheme",
    "dependenciesOut": "Hela social systemet - 15 avatar användningar + alla dialogs + friend management + collaborative editing",
    "dataFlow": "Centraliserad social API → Delegerar till specialiserade helpers → Konsistent styling",
    "stateManagement": "Stateless builders som delegerar till befintliga komponenter",
    "purpose": "Single source of truth för ALL social UI patterns med 100% funktionell kompatibilitet + collaborative features",
    "commonIssues": "Bevara all befintlig funktionalitet, AppTheme compliance, konsistenta callbacks",
    "testCoverage": "Ärver från underliggande komponenter",
    "performance": "⚡ Optimerad delegation utan overhead, cached components",
    "connectedTo": "FriendsViewModel, GroupInvitationService, AuthService, alla social views",
    "usedInPhases": "Fas 4.1 - Största widget konsolideringen i projektet + collaborative editing"
  },
  "widgets/common/universal_share_dialog.dart": {
    "component": "UniversalShareDialog - Universell delningsdialog för alla content-typer",
    "dependenciesIn": "Recipe, UnifiedShoppingList, UserProfile, SocialRecipeService, AppTheme",
    "dependenciesOut": "RecipeDetailView, MenuView, ShoppingView",
    "dataFlow": "Content → Type detection → Appropriate logic → Share execution",
    "stateManagement": "StatefulWidget med dynamisk hantering baserat på content type",
    "purpose": "Eliminera code duplication + konsistent delning UX",
    "commonIssues": "Type safety, error handling, preserved state",
    "testCoverage": "0% (ny komponent som ersätter befintliga)",
    "performance": "⚡ Samma prestanda som separata dialogs, mindre memory footprint",
    "connectedTo": "SocialRecipeService, delningslogik, content models",
    "usedInPhases": "Optimering - Sammanslagning av duplicerad delningsfunktionalitet"
  },
  "widgets/common/input_components.dart": {
    "component": "Unified collection of all input widgets for forms and user interaction",
    "dependenciesIn": "AppTheme, UnifiedShoppingViewModel, models (Recipe, UnifiedShoppingItem, etc)",
    "dependenciesOut": "Used throughout views for user input and data collection",
    "dataFlow": "User input → Components → Parent widgets → ViewModels → Services",
    "stateManagement": "Individual StatefulWidgets with callback patterns to parent",
    "purpose": "Consolidate all input widgets for consistency and reusability",
    "commonIssues": "Form validation, memory leaks from controllers, proper disposal",
    "testCoverage": "Widget tests for each component + integration tests",
    "performance": "Optimized with debouncing, efficient rebuilds, proper dispose",
    "connectedTo": "All views that require user input, especially forms",
    "usedInPhases": "Phase 2.3 - Input Components Consolidation"
  },
  "widgets/common/utility_components.dart": {
    "component": "UtilityComponents - Unified Utility Widget API",
    "dependenciesIn": "ActionButton, RecipeServiceWidget, FriendCategoryManager, AppTheme",
    "dependenciesOut": "Views använde ActionButton, RecipeServiceWidget, FriendCategoryManager",
    "dataFlow": "Unified API för utility patterns → delegerar till optimerade implementationer",
    "stateManagement": "Delegerad till underliggande komponenter + lokal state för overlays",
    "purpose": "Final konsolidering av utility widgets för 90% widget konsolidering completion",
    "commonIssues": "Service state management, button loading states, friend selection UX",
    "testCoverage": "95%+ målsättning för alla utility methods",
    "performance": "⚡ Optimerade delegate patterns, smart widget caching",
    "connectedTo": "All views using utility patterns, service layers, social features",
    "usedInPhases": "4.3 - Final Sprint - UtilityComponents (FAS 4.3 COMPLETION)"
  },
  "widgets/common/state_widget.dart": {
    "component": "StateWidget - Universal state handler for all app states",
    "dependenciesIn": "AppTheme, Flutter material, UtilityComponents",
    "dependenciesOut": "All views that need state display",
    "dataFlow": "State type + data → Visual representation",
    "stateManagement": "Stateless, receives state from parent",
    "purpose": "Centralized state UI with consistent design",
    "commonIssues": "Proper state type handling, theme compliance",
    "testCoverage": "Unit tests for all state types",
    "performance": "Lightweight, no unnecessary rebuilds",
    "connectedTo": "All ViewModels, Views, Services",
    "usedInPhases": "Core UI foundation"
  },
  "widgets/common/search_filter_widget.dart": {
    "component": "SearchFilterWidget - Unified search and filter functionality",
    "dependenciesIn": "AppTheme, ViewModels (for state)",
    "dependenciesOut": "Used by recipe/menu list views",
    "dataFlow": "User input → Widget state → ViewModel updates → UI refresh",
    "stateManagement": "Internal state for UI, ViewModel for business logic",
    "purpose": "Replaces separate search_bar.dart + filter_chips.dart",
    "commonIssues": "Ensure proper controller disposal",
    "testCoverage": "90% (critical for search/filter UX)",
    "performance": "Optimized rebuilds, efficient animations",
    "connectedTo": "RecipeListViewModel, MenuViewModel",
    "usedInPhases": "Fas 2 - Widget consolidation"
  },
  "widgets/common/layout_components.dart": {
    "component": "Unified collection of layout widgets and navigation components",
    "dependenciesIn": "AppTheme, MainLayoutMenu, ProfileMenuWidget, OfflineIndicator, MenuPersistenceDialogs",
    "dependenciesOut": "Used throughout views for consistent layout structure",
    "dataFlow": "User interactions → Layout components → Navigation/State changes",
    "stateManagement": "Stateless widgets with callback patterns to parent views",
    "purpose": "Consolidate layout widgets for consistency and reusability",
    "commonIssues": "Navigation state, theme consistency, responsive design",
    "testCoverage": "Widget tests for each component + navigation flow tests",
    "performance": "Optimized rebuilds, efficient navigation, proper disposal",
    "connectedTo": "All main views, navigation system, theme system",
    "usedInPhases": "Phase 3.1 - Layout Components Consolidation"
  },
  "widgets/common/navigation_components.dart": {
    "component": "NavigationComponents - Unified navigation widgets for dialogs and realtime indicators",
    "dependenciesIn": "Recipe models, ViewModels, AppTheme, StateWidget, SearchFilterWidget",
    "dependenciesOut": "Various views, RealtimeMenuViewModel, recipe handlers",
    "dataFlow": "User interaction → Dialog/indicator → Callback/visual feedback",
    "stateManagement": "StatefulWidget för complex dialogs, Stateless för indicators",
    "purpose": "Centralized navigation patterns för konsistent UX",
    "commonIssues": "Dialog callback patterns, realtime indicator flicker",
    "testCoverage": "Unit tests för selection logic, widget tests för UI",
    "performance": "Efficient dialogs med proper disposal, minimal realtime rebuilds",
    "connectedTo": "RecipeSelectionViewModel, MenuRecipeSelectionDialog, RealtimeMenuView",
    "usedInPhases": "Fas 3.2 (Navigation Konsolidering) - All navigation patterns unified"
  },
  "models/shared_recipe.dart": {
    "component": "Shared Recipe Model - Firebase First - FIXED + DISMISS + isDismissed GETTER",
    "dependenciesIn": "cloud_firestore, firebase_auth, uuid, recipe.dart, flutter/foundation.dart",
    "dependenciesOut": "SocialRecipeService, sharing views",
    "dataFlow": "Firestore ↔ SharedRecipe object ↔ Social UI",
    "stateManagement": "Immutable med copyWith pattern och cached recipe data",
    "purpose": "Receptdelning med tracking, import och dismiss functionality + easy isDismissed check",
    "commonIssues": "✅ LÖST: MockDocumentSnapshot type cast, robust parsing, dismiss tracking, isDismissed getter added",
    "testCoverage": "70%",
    "performance": "⚡ Cached recipe data för offline access",
    "connectedTo": "Recipe, UserProfile, SocialRecipeService, sharing views",
    "usedInPhases": "18"
  },
  "models/user_profile.dart": {
    "component": "User Profile Model - Firebase First",
    "dependenciesIn": "cloud_firestore",
    "dependenciesOut": "UserService, alla social features",
    "dataFlow": "Firestore ↔ UserProfile object ↔ UI components",
    "stateManagement": "Immutable med copyWith pattern",
    "purpose": "Central användarmodell för social platform",
    "commonIssues": "Email privacy, displayName uniqueness",
    "testCoverage": "85%",
    "performance": "⚡ Minimal serialization overhead",
    "connectedTo": "AuthService, FriendsService, alla social views",
    "usedInPhases": "18"
  },
  "models/group_invitation.dart": {
    "component": "Group Invitation Model - Notifikationssystem för gruppinbjudningar",
    "dependenciesIn": "cloud_firestore, uuid",
    "dependenciesOut": "NotificationService, group invitation UI",
    "dataFlow": "Send invitation → Notification → Accept/Reject → Join group",
    "stateManagement": "Immutable med status tracking",
    "purpose": "Separat system för gruppinbjudningar med notifikationer",
    "commonIssues": "Expired invitations, duplicate invitations, permission checks",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Minimal serialization, efficient queries",
    "connectedTo": "GroupInvitationService, NotificationService, group views",
    "usedInPhases": "18.6 - Notifikationssystem"
  },
  "models/friend_category.dart": {
    "component": "Friend Category Model - Social Shopping Foundation",
    "dependenciesIn": "cloud_firestore, uuid",
    "dependenciesOut": "FriendCategoriesService, social shopping views",
    "dataFlow": "Firestore ↔ FriendCategory object ↔ Category management UI",
    "stateManagement": "Immutable med copyWith pattern",
    "purpose": "Organisera vänner i kategorier för enklare shopping list sharing",
    "commonIssues": "Category name uniqueness, empty categories cleanup",
    "testCoverage": "80%",
    "performance": "⚡ Minimal serialization, efficient category queries",
    "connectedTo": "FriendsService, SharedShoppingList, category management UI",
    "usedInPhases": "18.4"
  },
  "models/recipe_comment.dart": {
    "component": "Recipe Comment Model - Firebase First",
    "dependenciesIn": "cloud_firestore, uuid",
    "dependenciesOut": "SocialRecipeService, comment widgets",
    "dataFlow": "Firestore ↔ RecipeComment object ↔ Comment UI",
    "stateManagement": "Immutable med copyWith pattern",
    "purpose": "Threaded comments system för recept med social features",
    "commonIssues": "Reply depth limits, author data caching",
    "testCoverage": "75%",
    "performance": "⚡ Optimized för threaded display, cached author data",
    "connectedTo": "SocialRecipeService, Recipe, UserProfile, comment views",
    "usedInPhases": "18"
  },
  "models/friend_request.dart": {
    "component": "Friend Request Model - Firebase First",
    "dependenciesIn": "cloud_firestore, uuid",
    "dependenciesOut": "FriendsService, friend request UI",
    "dataFlow": "Firestore ↔ FriendRequest object ↔ UI components",
    "stateManagement": "Immutable med copyWith pattern",
    "purpose": "Hanterar vänskapsförfrågningar med status tracking",
    "commonIssues": "Expired requests cleanup, duplicate requests",
    "testCoverage": "80%",
    "performance": "⚡ Minimal serialization, indexed queries",
    "connectedTo": "FriendsService, UserProfile, request notification views",
    "usedInPhases": "18"
  },
  "models/shared_menu.dart": {
    "component": "Shared Menu Model - Firebase First - FIXED med allowImport + DISMISS + isDismissed GETTER + COLLABORATION",
    "dependenciesIn": "cloud_firestore, firebase_auth, uuid, recipe.dart, flutter/foundation.dart",
    "dependenciesOut": "SocialRecipeService, menu sharing views",
    "dataFlow": "Firestore ↔ SharedMenu object ↔ Social UI",
    "stateManagement": "Immutable med copyWith pattern och cached menu data",
    "purpose": "Menydelning med komplett veckomeny, tracking, import, dismiss functionality, collaboration + easy isDismissed check",
    "commonIssues": "✅ LÖST: MockDocumentSnapshot type cast, robust parsing, allowImport getter, dismiss tracking, isDismissed getter added, collaboration support",
    "testCoverage": "65%",
    "performance": "⚡ Cached menu data för offline access, optimized queries",
    "connectedTo": "Recipe, UserProfile, SocialRecipeService, menu views",
    "usedInPhases": "18 + Collaboration"
  },
  "models/permissions/resource_permission.dart": {
    "component": "Resource Permission Model - Behörighetshantering för realtidsresurser",
    "dependenciesIn": "N/A (standalone enum och helper class)",
    "dependenciesOut": "RealtimeResource, RealtimeRecipe, RealtimeMenu, permission services",
    "dataFlow": "Permission checks → Helper methods → Boolean results för UI/logic",
    "stateManagement": "Stateless enum med utility functions",
    "purpose": "Centraliserad behörighetslogik för alla realtidsresurser",
    "commonIssues": "Säkerställ att owner alltid har full behörighet",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Lightweight enum operations, no overhead",
    "connectedTo": "Alla realtidsmodeller, invitation system, sharing dialogs",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - Foundation för all access control"
  },
  "models/unified/unified_shopping_item.dart": {
    "component": "Unified Shopping Item Model - FÖRBÄTTRAD FORMATERING",
    "dependenciesIn": "cloud_firestore, uuid",
    "dependenciesOut": "UnifiedShoppingService, alla shopping UI-komponenter",
    "dataFlow": "Recipe ingredients → UnifiedShoppingItem → UI rendering → Firebase sync",
    "stateManagement": "Immutable data class med copyWith pattern",
    "purpose": "Enhetlig representation av shopping items med SMART FORMATERING",
    "commonIssues": "Inga onödiga decimaler, korrekt enhetsvisning",
    "testCoverage": "0% (förbättring av befintlig komponent)",
    "performance": "⚡ Optimerad serialization, effektiv state management",
    "connectedTo": "UnifiedShoppingService, alla shopping views, Firebase",
    "usedInPhases": "18.3 (Unified Shopping Migration) + UI förbättringar"
  },
  "models/invitations/invitation_target.dart": {
    "component": "Invitation Target Model - Stödjer både individuell och gruppdelning",
    "dependenciesIn": "UserProfile, FriendCategory",
    "dependenciesOut": "InvitationService, TargetDisplayWidgets (UI konsumerar denna data)",
    "dataFlow": "UI target selection → InvitationTarget → Firebase invitation → Individual users",
    "stateManagement": "Immutable data class med factory constructors",
    "purpose": "Enhetlig representation av både individuella och grupp-mål för inbjudningar",
    "commonIssues": "Säkerställ att gruppmedlemmar expanderas korrekt",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Efficient serialization, minimal overhead",
    "connectedTo": "InvitationService, TargetDisplayWidgets",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - Gruppstöd foundation"
  },
  "models/invitations/realtime_invitation.dart": {
    "component": "Realtime Invitation Model - Inbjudningssystem för gemensamma resurser",
    "dependenciesIn": "RealtimeResourceType, InvitationTarget, AppTheme, cloud_firestore, uuid",
    "dependenciesOut": "InvitationService, inbjudnings-UI, notifikationer",
    "dataFlow": "Send invitation → Store → Real-time updates → Accept/Reject → Join resource",
    "stateManagement": "Immutable med state tracking och expiration logic",
    "purpose": "Komplett inbjudningssystem som stödjer både individuell och gruppdelning",
    "commonIssues": "Hantera expired invitations, duplicate invitations för samma user/resource",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Efficient queries med compound indexes, minimal data transfer",
    "connectedTo": "InvitationService, delningsdialograr, RealtimeResource classes",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - Invitation foundation"
  },
  "models/realtime/realtime_recipe.dart": {
    "component": "Realtime Recipe Model - Konkret implementation för gemensam receptredigering",
    "dependenciesIn": "Recipe, RealtimeResource, ResourcePermission, cloud_firestore",
    "dependenciesOut": "RealtimeRecipeService, RealtimeRecipeViewModel, UI widgets",
    "dataFlow": "Recipe edits → RealtimeRecipe updates → Firebase sync → All participants",
    "stateManagement": "Immutable med copyWith, delegerar till Recipe för content",
    "purpose": "Wrapper som lägger till realtidskapacitet till befintliga Recipe objekt",
    "commonIssues": "Säkerställ att Recipe innehåll synkas korrekt, hantera samtidiga edits",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Minimal overhead, Recipe object cached för snabb access",
    "connectedTo": "Recipe, RealtimeRecipeService, UI widgets (via separate widget files)",
    "usedInPhases": "Fas 2 (Recept realtidsredigering) - Foundation för recipe collaboration"
  },
  "models/realtime/realtime_menu.dart": {
    "component": "Realtime Menu Model - UPPDATERAD för kategori-baserade menyer",
    "dependenciesIn": "Recipe, RealtimeResource, ResourcePermission, cloud_firestore",
    "dependenciesOut": "RealtimeMenuService, RealtimeMenuViewModel, UI widgets",
    "dataFlow": "Menu edits → RealtimeMenu updates → Firebase sync → All participants",
    "stateManagement": "Immutable med copyWith, hanterar kategori-struktur (samma som befintlig SharedMenu)",
    "purpose": "Real-time collaboration på befintlig menystruktur utan breaking changes",
    "commonIssues": "Hantera tomma kategorier, recipe duplicates, samtidiga kategori-assignments",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Efficient category-based operations, kompatibel med befintlig MenuViewModel",
    "connectedTo": "MenuViewModel, VeckomenyView, kategori-baserad menyplanering, UI widgets",
    "usedInPhases": "Fas 3 (Menyer + Inköpslistor) - Foundation för kategori-baserad collaboration"
  },
  "models/realtime/realtime_resource.dart": {
    "component": "Realtime Resource Base Model - Grundklass för alla realtidsresurser",
    "dependenciesIn": "ResourcePermission, cloud_firestore",
    "dependenciesOut": "RealtimeRecipe, RealtimeMenu, RealtimeShoppingList, UI widgets",
    "dataFlow": "Subclasses extend → Shared metadata handling → Firebase sync",
    "stateManagement": "Immutable base class med common properties",
    "purpose": "DRY principle - gemensam realtidslogik för alla resurser",
    "commonIssues": "Säkerställ att subclasses implementerar alla required methods",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Minimal overhead, shared efficient serialization",
    "connectedTo": "Alla realtidsmodeller, RealtimeSyncService, PermissionService",
    "usedInPhases": "Fas 1 (Grundinfrastruktur) - Foundation för all realtidsdata"
  },
  "views/social/user_profile_edit_view.dart": {
    "component": "User Profile Edit Interface",
    "dependenciesIn": "UserProfileViewModel, UserAvatar, form validators",
    "dependenciesOut": "Navigation tillbaka med sparade ändringar",
    "dataFlow": "Load current profile → Edit form → Validation → Avatar upload → Save",
    "stateManagement": "Konsumerar UserProfileViewModel med Provider",
    "purpose": "Fullständig profil-management med elegant UX",
    "commonIssues": "Avatar upload timing, form validation, unsaved changes",
    "testCoverage": "60%",
    "performance": "⚡ Optimerad med smart loading states",
    "connectedTo": "UserProfileViewModel, UserAvatar widget",
    "usedInPhases": "18"
  },
  "views/social/friend_requests_view.dart": {
    "component": "Friend Requests Notification Center - MIGRERAD TILL SocialComponents",
    "dependenciesIn": "FriendsViewModel, SocialComponents (istället för UserAvatar)",
    "dependenciesOut": "Friend request management, notification badges",
    "dataFlow": "All friend requests → Load user profiles → Categorized display → Batch actions",
    "stateManagement": "Konsumerar FriendsViewModel med Provider",
    "purpose": "Centraliserad notifikationscenter för all friend request activity med riktiga användarnamn och bilder",
    "commonIssues": "Request state syncing, batch operation performance, user profile loading",
    "testCoverage": "70%",
    "performance": "⚡ Optimized för stora mängder requests med cached user profiles",
    "connectedTo": "FriendsViewModel, UserService, notification system, SocialComponents",
    "usedInPhases": "18 - MIGRERAD till unified social API"
  },
  "views/social/group_detail_view.dart": {
    "component": "Group Detail View - MIGRERAD TILL SocialComponents",
    "dependenciesIn": "FriendsViewModel, FriendCategoriesService, GroupInvitationService, AuthService, SocialComponents",
    "dependenciesOut": "Group management actions, member management, invitation tracking",
    "dataFlow": "Load group → Check permissions → Show appropriate actions → Handle member management",
    "stateManagement": "✅ Event-baserad uppdatering med korrekt behörighetskontroll",
    "purpose": "Komplett gruppvy med KORREKT behörighetshantering för edit/delete/leave actions + unified social API",
    "commonIssues": "✅ ALLA FIXADE: Behörighetskontroll, leave group, member permissions",
    "testCoverage": "85%",
    "performance": "⚡ Optimerad med smart invitation loading + permission checks",
    "connectedTo": "FriendsViewModel, FriendCategoriesService, GroupInvitationService, AuthService, SocialComponents",
    "usedInPhases": "18.6 - Komplett gruppvy med säker behörighetshantering + migrerad till unified social API"
  },
  "views/social/group_invitations_view.dart": {
    "component": "Group Invitations View - 100% MVVM + AppTheme Design (KORRIGERAD)",
    "dependenciesIn": "GroupInvitationsViewModel, AppTheme design system",
    "dependenciesOut": "Gruppmedlemskap via ViewModel",
    "dataFlow": "View → ViewModel → Services → Firebase",
    "stateManagement": "Provider pattern med ChangeNotifier ViewModel",
    "purpose": "Clean UI som bara visar data från ViewModel",
    "commonIssues": "N/A - Pure UI logic",
    "testCoverage": "80% (UI testing med mocked ViewModel)",
    "performance": "⚡ Pure UI, inga direkta service calls",
    "connectedTo": "GroupInvitationsViewModel",
    "usedInPhases": "18.4 - MVVM gruppinbjudningar"
  },
  "views/social/collaborative_shopping_view.dart": {
    "component": "Collaborative Shopping View - MVVM + UnifiedShopping Compliant",
    "dependenciesIn": "CollaborativeShoppingViewModel, AppTheme",
    "dependenciesOut": "Collaborative shopping UI med complete MVVM pattern",
    "dataFlow": "View → ViewModel → UnifiedShoppingService, pure UI rendering",
    "stateManagement": "ChangeNotifierProvider med ViewModel",
    "purpose": "MVVM-compliant collaborative shopping experience",
    "commonIssues": "✅ LÖST: Proper separation, AppTheme usage, unified backend",
    "performance": "⚡ Optimized rendering, efficient state management",
    "connectedTo": "CollaborativeShoppingViewModel, UnifiedShoppingService",
    "usedInPhases": "18.4"
  },
  "services/user_service.dart": {
    "component": "User Management Service",
    "dependenciesIn": "cloud_firestore, firebase_auth, user_profile.dart",
    "dependenciesOut": "Alla social features, profile views",
    "dataFlow": "Auth → Profile creation → Search → Social interactions",
    "stateManagement": "ChangeNotifier med profile cache",
    "purpose": "Central hub för användarhantering och discovery",
    "commonIssues": "Profile sync med Auth, search performance",
    "testCoverage": "75%",
    "performance": "⚡ Cached profiles, optimized queries",
    "connectedTo": "AuthService, alla social services",
    "usedInPhases": "18"
  },
  "services/group_invitation_service.dart": {
    "component": "Group Invitation Service - MED FIXAD acceptGroupInvitation",
    "dependenciesIn": "cloud_firestore, firebase_auth, group_invitation.dart, friend_category.dart",
    "dependenciesOut": "Group invitation notifications, invitation UI, group events",
    "dataFlow": "Send invitation → Store notification → Accept/Reject → Join group → BEHÅLL ALLA MEDLEMMAR",
    "stateManagement": "ChangeNotifier med invitations cache och real-time updates + events",
    "purpose": "Komplett inbjudningssystem med KORREKT medlemsbevarande vid accept",
    "commonIssues": "✅ ALLA FIXADE: Behåller befintliga medlemmar vid accept, uppdaterar originalgrupp",
    "testCoverage": "85%",
    "performance": "⚡ Real-time listeners, batch operations, auto-cleanup + optimerad medlemshantering",
    "connectedTo": "FriendCategoriesService, GroupEventBus, NotificationService, invitation UI",
    "usedInPhases": "18.6 - Komplett gruppinbjudningssystem med korrekt medlemshantering"
  },
  "services/realtime_sync_service.dart": {
    "component": "Realtime Sync Service - Firebase Real-time Synkronisering",
    "dependenciesIn": "cloud_firestore, firebase_auth, realtime models",
    "dependenciesOut": "RealtimeResource ViewModels, collaborative views",
    "dataFlow": "Firebase real-time → Stream updates → UI via ChangeNotifier",
    "stateManagement": "ChangeNotifier med connection tracking och conflict resolution",
    "purpose": "SINGLE RESPONSIBILITY - bara Firebase synkronisering, inget annat",
    "commonIssues": "Connection drops, simultaneous edits, permission validation",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Optimized listeners, smart conflict resolution, minimal data transfer",
    "connectedTo": "Alla RealtimeResource subclasses, collaborative views",
    "usedInPhases": "Fas 2 (RealtimeSyncService) - Foundation för all real-time funktionalitet"
  },
  "services/friend_categories_service.dart": {
    "component": "Friend Categories Management Service - KOMPLETT FIXAD VERSION",
    "dependenciesIn": "cloud_firestore, firebase_auth, friend_category.dart, friends_service",
    "dependenciesOut": "Category management UI, shopping list sharing, group invitations",
    "dataFlow": "Create/Update categories → Assign friends → Use in shopping lists + invitations",
    "stateManagement": "ChangeNotifier med categories cache",
    "purpose": "Organisera vänner i kategorier för enklare sharing och gruppinbjudningar",
    "commonIssues": "✅ ALLA FIXADE: Firebase paths, user-specific subcollections, robust save/load",
    "testCoverage": "85%",
    "performance": "⚡ Cached categories, optimized friend queries, Dart sorting",
    "connectedTo": "FriendsService, SharedShoppingList, GroupInvitationService, category UI",
    "usedInPhases": "18.4 - Komplett grupphantering med korrekt datalagring"
  },
  "services/social_recipe_service.dart": {
    "component": "Social Recipe Management Service - PRODUCTION READY + DISMISS FEATURES + SHOPPING SHARE",
    "dependenciesIn": "cloud_firestore, firebase_auth, recipe models, user_service",
    "dependenciesOut": "Social features, sharing views, comment system, dismiss management, shopping share",
    "dataFlow": "Share recipe → Store with metadata → Comments → Import/Dismiss to collection + Shopping share",
    "stateManagement": "ChangeNotifier med shared content, comments och dismiss tracking",
    "purpose": "Complete social recipe system med sharing, commenting och user-friendly dismiss + shopping share - PRODUCTION READY",
    "commonIssues": "✅ LÖST: Nullable spread operator, allowImport getter, type safety, dismiss tracking, shopping share",
    "testCoverage": "65%",
    "performance": "⚡ Optimized queries med pagination, batch operations, efficient dismiss filtering",
    "connectedTo": "RecipeService, UserService, comment widgets, sharing views, dismiss UI, shopping share dialog",
    "usedInPhases": "18 + Shopping Share"
  },
  "services/friends_service.dart": {
    "component": "Friends Management Service",
    "dependenciesIn": "cloud_firestore, firebase_auth, user_profile.dart, friend_request.dart",
    "dependenciesOut": "Friends lists, request notifications, social features",
    "dataFlow": "Send request → Accept/Reject → Mutual friends → Social access",
    "stateManagement": "ChangeNotifier med friends och requests lists",
    "purpose": "Complete friends system med notifications och permissions",
    "commonIssues": "Duplicate requests, permission management, cleanup",
    "testCoverage": "70%",
    "performance": "⚡ Optimized queries, friend count tracking",
    "connectedTo": "UserService, NotificationService, all social features",
    "usedInPhases": "18"
  },
  "services/invitations/group_invitation_expander.dart": {
    "component": "Group Invitation Expander - Expandera grupper till individuella användare",
    "dependenciesIn": "FriendCategoriesService, FriendsService, invitation models",
    "dependenciesOut": "InvitationService, delningsdialoggar som behöver grupp → user expansion",
    "dataFlow": "InvitationTarget groups → Expand to individual users → Individual invitations",
    "stateManagement": "Stateless utility service - ingen state tracking",
    "purpose": "SRP - bara gruppexpansion, ingen invitation logic eller UI concerns",
    "commonIssues": "Tomma grupper, användare som inte längre är vänner, dubbletter",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Efficient group lookups, cached friend data, minimal API calls",
    "connectedTo": "InvitationService, Enhanced sharing dialogs, gruppbaserad delning",
    "usedInPhases": "Fas 2 (Gruppstöd) - Foundation för gruppinbjudningar"
  },
  "services/realtime/realtime_menu_service.dart": {
    "component": "Realtime Menu Service - UPPDATERAD för kategori-baserade menyer",
    "dependenciesIn": "RealtimeSyncService, AuthService, UserService, realtime models",
    "dependenciesOut": "RealtimeMenuViewModel, menu collaboration views",
    "dataFlow": "Menu operations → RealtimeMenu updates → RealtimeSyncService → Firebase",
    "stateManagement": "ChangeNotifier för menu-specific events",
    "purpose": "SRP - bara menu operations för kategorier, delegerar synkronisering till RealtimeSyncService",
    "commonIssues": "Category validation, recipe conflicts, concurrent editing",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Efficient category-based operations, cached user info",
    "connectedTo": "RealtimeSyncService, kategori-baserade menu models, collaborative views",
    "usedInPhases": "Fas 3 (Menyer + Inköpslistor) - Category-specific real-time operations"
  },
  "services/realtime/realtime_recipe_service.dart": {
    "component": "Realtime Recipe Service - Recipe-specifika operationer",
    "dependenciesIn": "RealtimeSyncService, AuthService, UserService, realtime models",
    "dependenciesOut": "RealtimeRecipeViewModel, recipe collaboration views",
    "dataFlow": "Recipe operations → RealtimeRecipe updates → RealtimeSyncService → Firebase",
    "stateManagement": "ChangeNotifier för recipe-specific events",
    "purpose": "SRP - bara recipe operations, delegerar synkronisering till RealtimeSyncService",
    "commonIssues": "Recipe validation, ingredient/instruction formatting, user context",
    "testCoverage": "0% (ny komponent)",
    "performance": "⚡ Efficient recipe operations, cached user info",
    "connectedTo": "RealtimeSyncService, Recipe models, collaborative recipe views",
    "usedInPhases": "Fas 2 (Recipe + Gruppstöd) - Recipe-specific real-time operations"
  }
  @override
  void dispose() {
    // Cancel all timers
    // Cancel all stream subscriptions  
    // Dispose of resources
    super.dispose();
  }
}
''';

final Map<String, dynamic> codeDocumentation =
    json.decode(_codeDocumentationJson) as Map<String, dynamic>;
