#!/usr/bin/env python3
"""Generate docs/org/role-paths.json from ROLE_RESPONSIBILITY_MAP.md.

The map's per-role `**Evidence:**` line is the machine-readable signal of what
each role owns. This projects those evidence paths into repo-relative glob
patterns so the dossier-freshness PostToolUse hook can match an edited file to
the owning role(s) without parsing the 846-line Markdown on every edit.

Rule per evidence token:
  - strip the audit sandbox's `/home/user/butlery/` prefix -> repo-relative
  - a directory token (trailing `/`) -> `<dir>/**`
  - a file token -> the exact file path, PLUS a `<parent>/**` glob unless the
    parent dir is too generic (see GENERIC_DIRS) — there we keep exact-only so
    one role doesn't claim all of e.g. lib/services/.

Run after editing ROLE_RESPONSIBILITY_MAP.md:
    python tools/gen_role_paths.py
(`/refresh-dossiers` regenerates it as step 0.)
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, "docs", "architecture", "ROLE_RESPONSIBILITY_MAP.md")
OUT = os.path.join(ROOT, "docs", "org", "role-paths.json")

PREFIX = "/home/user/butlery/"

# Parent dirs too generic to glob — many roles own different files under them,
# so a parent glob would over-stamp. Files here match exact-only.
GENERIC_DIRS = {
    "", "lib", "lib/services", "lib/views", "lib/viewmodels", "lib/widgets",
    "lib/widgets/common", "lib/models", "lib/repositories", "lib/core",
    "lib/l10n", "functions/src", ".claude", ".claude/rules", ".claude/hooks",
    "docs", "docs/architecture", "assets", "tools", "test",
}


def normalize(token):
    t = token.strip().strip("`").replace("\\", "/")
    if t.startswith(PREFIX):
        t = t[len(PREFIX):]
    # Any other absolute sandbox path ending in /butlery/
    m = re.match(r"^/.*?/butlery/(.*)$", t)
    if m:
        t = m.group(1)
    return t.strip("/") if t.endswith("/") and t != "/" else t.lstrip("/") if t.startswith("/") else t


def patterns_for(token):
    raw = token.strip().strip("`").replace("\\", "/")
    is_dir = raw.endswith("/")
    t = normalize(token)
    if not t or "/home/user" in t:
        return []
    if is_dir:
        return [f"{t}/**"]
    pats = [t]
    parent = t.rsplit("/", 1)[0] if "/" in t else ""
    if parent and parent not in GENERIC_DIRS:
        pats.append(f"{parent}/**")
    return pats


def main():
    text = open(MAP, encoding="utf-8").read()
    # Split into role blocks at "## N. Name" headings.
    blocks = re.split(r"\n## (\d+)\. ", text)
    roles = {}
    # blocks[0] is the preamble; then (num, body) pairs.
    for i in range(1, len(blocks), 2):
        body = blocks[i + 1]
        name = body.splitlines()[0].strip()
        ev = re.search(r"^\*\*Evidence:\*\*(.+)$", body, re.MULTILINE)
        if not ev:
            continue
        tokens = re.findall(r"`([^`]+)`", ev.group(1))
        pats = []
        for tok in tokens:
            for p in patterns_for(tok):
                if p not in pats:
                    pats.append(p)
        roles[name] = sorted(pats)
    out = {
        "_doc": (
            "Generated by tools/gen_role_paths.py from "
            "docs/architecture/ROLE_RESPONSIBILITY_MAP.md (each role's Evidence line). "
            "Maps a role to repo-relative glob patterns it owns. Read by "
            ".claude/hooks/dossier-freshness-stamp.sh to stamp a dossier stale when an "
            "owned file is edited, and by the /refresh-dossiers skill. Do not hand-edit; "
            "re-run the generator after editing the map."
        ),
        "roles": roles,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {OUT}: {len(roles)} roles, "
          f"{sum(len(v) for v in roles.values())} patterns")


if __name__ == "__main__":
    main()
