import 'dart:io';
import 'dart:convert';

void main() {
  final documentation = <String, Map<String, String>>{};
  const startMarker = '/// 🔍 AI INFO BLOCK:';
  const endMarkerPrefix = '/// Used in phases:';

  final dartFiles = Directory('lib')
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'));

  for (final file in dartFiles) {
    final lines = File(file.path).readAsLinesSync();
    final startIndex = lines.indexWhere((l) => l.trim().startsWith(startMarker));
    if (startIndex == -1) continue;

    int endIndex = startIndex;
    while (endIndex < lines.length &&
        !lines[endIndex].trim().startsWith(endMarkerPrefix)) {
      endIndex++;
    }
    if (endIndex >= lines.length) continue;

    final blockLines = lines.sublist(startIndex + 1, endIndex + 1);
    final info = <String, String>{};
    for (final line in blockLines) {
      final match = RegExp(r'^///\s*([^:]+):\s*(.*)\$').firstMatch(line.trim());
      if (match != null) {
        final key = match.group(1)!.trim();
        final value = match.group(2)!.trim();
        switch (key) {
          case 'Component':
            info['component'] = value;
            break;
          case 'Purpose':
            info['purpose'] = value;
            break;
          case 'Dependencies IN':
            info['dependenciesIn'] = value;
            break;
          case 'Dependencies OUT':
            info['dependenciesOut'] = value;
            break;
          case 'Data flow':
            info['dataFlow'] = value;
            break;
          case 'State management':
            info['stateManagement'] = value;
            break;
          case 'Common issues':
            info['commonIssues'] = value;
            break;
          case 'Test coverage':
            info['testCoverage'] = value;
            break;
          case 'Performance':
            info['performance'] = value;
            break;
          case 'Connected to':
            info['connectedTo'] = value;
            break;
          case 'Used in phases':
            info['usedInPhases'] = value;
            break;
        }
      }
    }
    documentation[file.path.replaceFirst('lib/', '')] = info;
  }

  const encoder = JsonEncoder.withIndent('  ');
  final jsonStr = encoder.convert(documentation);

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// This file was generated by tools/generate_documentation.dart')
    ..writeln("import 'dart:convert';")
    ..writeln('')
    ..writeln('const String _codeDocumentationJson = r"""')
    ..writeln(jsonStr)
    ..writeln('""";')
    ..writeln('')
    ..writeln('final Map<String, dynamic> codeDocumentation =')
    ..writeln('    json.decode(_codeDocumentationJson) as Map<String, dynamic>;');

  File('lib/docs/code_documentation.dart').writeAsStringSync(buffer.toString());
}
