// tools/generate_butlery_icons.dart
// P7-U08: generates lib/widgets/common/icons/butlery_icons.dart, the
// ButleryIcons register, from the design system's icon masters.
//
// Inputs, read where the design system keeps them:
//   design/icons.json                the normative inventory (names, meanings)
//   design/assets/icons/<name>.svg   one master per glyph
//
// Usage: dart run tools/generate_butlery_icons.dart && dart format \
//          lib/widgets/common/icons/butlery_icons.dart
//
// Never edit the output by hand. To add a glyph, add it to design/icons.json,
// draw its master in design/assets/icons/ and rerun.

// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

const _out = 'lib/widgets/common/icons/butlery_icons.dart';

/// Filled masters that also have an outline state. The outline is the same
/// geometry drawn as a 1.75 stroke: Skarmar v12 del 1:311 draws the heart
/// that way (not yet a favourite), and the star is drawn with fill none in
/// two places in the screen files. The bookmark's outline is the template
/// that is not saved (icons.json contract.exceptions.bookmark).
const _outlineVariants = ['bookmark', 'heart', 'star'];

/// Semantic aliases (migration-gap.md:46, K-10: map the family onto the
/// app's semantic aliases, not raw names). alias -> member.
const _aliases = {
  'favourite': 'heart',
  'favouriteOutline': 'heartOutline',
  'primary': 'star',
  'primaryOutline': 'starOutline',
  'back': 'arrowLeft',
  'close': 'x',
  'savedTemplate': 'bookmark',
  'savedTemplateOutline': 'bookmarkOutline',
};

String camel(String kebab) {
  final parts = kebab.split('-');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

/// A single-line Dart string literal. Newlines are written as `\n` escapes
/// so the embedded master stays byte-identical to the asset whatever line
/// endings a checkout gives this generated file.
String _sq(String s) {
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\r', r'\r')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

String _dartString(String s) => _sq(s);

void main() {
  final manifest =
      jsonDecode(File('design/icons.json').readAsStringSync())
          as Map<String, dynamic>;
  final entries = <Map<String, dynamic>>[
    for (final e in manifest['ui_family'] as List) e as Map<String, dynamic>,
    for (final e in manifest['nav_family'] as List) e as Map<String, dynamic>,
  ];
  final b = StringBuffer()
    ..writeln('// GENERATED by tools/generate_butlery_icons.dart. Do not edit.')
    ..writeln(
      '// Source: design/icons.json v${manifest['version']} '
      '(${manifest['date']}), ${entries.length} masters.',
    )
    ..writeln()
    ..writeln(
      "import 'package:butlery/widgets/common/icons/butlery_glyph.dart';",
    )
    ..writeln()
    ..writeln('/// The Butlery icon family (beslutslogg.md:9, B-02).')
    ..writeln('///')
    ..writeln('/// Render with `ButleryIcon`, never with a plain `Icon`.')
    ..writeln('abstract final class ButleryIcons {');
  var code = 0xF1000;
  final members = <String>[];
  for (final e in entries) {
    final name = e['name'] as String;
    final meaning = (e['meaning'] ?? name) as String;
    final svg = File('design/assets/icons/$name.svg').readAsStringSync();
    final member = camel(name);
    members.add(member);
    b
      ..writeln()
      ..writeln('  /// `$name`: $meaning.')
      ..writeln('  static const ButleryGlyph $member = ButleryGlyph(')
      ..writeln('    0x${code.toRadixString(16)},')
      ..writeln("    name: '$name',")
      ..writeln('    meaning: ${_sq(meaning)},')
      ..writeln('    svg: ${_dartString(svg)},')
      ..writeln('  );');
    code++;
  }
  code = 0xF1100;
  for (final name in _outlineVariants) {
    final member = '${camel(name)}Outline';
    members.add(member);
    b
      ..writeln()
      ..writeln('  /// `$name` drawn as an outline (the off state).')
      ..writeln('  static const ButleryGlyph $member = ButleryGlyph(')
      ..writeln('    0x${code.toRadixString(16)},')
      ..writeln("    name: '$name',")
      ..writeln('    meaning: ${camel(name)}Meaning,')
      ..writeln('    svg: ${camel(name)}Svg,')
      ..writeln('    outlined: true,')
      ..writeln('  );');
    b
      ..writeln()
      ..writeln('  /// The meaning of `$name`.')
      ..writeln(
        '  static const String ${camel(name)}Meaning = '
        '${_sq(entries.firstWhere((e) => e['name'] == name)['meaning'] as String)};',
      )
      ..writeln()
      ..writeln('  /// The master of `$name`.')
      ..writeln(
        '  static const String ${camel(name)}Svg = '
        '${_dartString(File('design/assets/icons/$name.svg').readAsStringSync())};',
      );
    code++;
  }
  b.writeln();
  _aliases.forEach((alias, member) {
    b
      ..writeln('  /// Semantic alias for [$member].')
      ..writeln('  static const ButleryGlyph $alias = $member;');
  });
  b
    ..writeln()
    ..writeln('  /// Every glyph, one per master, then the outline states.')
    ..writeln('  static const List<ButleryGlyph> values = [')
    ..writeln(members.map((m) => '    $m,').join('\n'))
    ..writeln('  ];')
    ..writeln('}');
  File(_out).writeAsStringSync(b.toString());
  print('Wrote $_out (${members.length} glyphs).');
}
