import 'package:butlery/core/l10n/app_locale.dart';
import 'package:butlery/services/tagging/config/allergen_config.dart';
import 'package:butlery/services/tagging/config/cuisine_config.dart';
import 'package:butlery/services/tagging/config/dietary_config.dart';

/// Reserved system tag names that cannot be used for personal tags.
/// Prevents confusion between auto-generated tags and user-created tags.
class ReservedTags {
  ReservedTags._();

  /// All reserved tag names (lowercase for comparison).
  static final Set<String> all = _buildReservedSet();

  /// Auto-generated tags from Phases 1-4.
  /// Phase 5 (cuisine) is derived from CuisineConfig at runtime.
  static const _autoGeneratedTags = {
    // Phase 1: Time
    'under-15-min', 'under-30-min', 'under-45-min', 'under-60-min',
    'över-60-min',
    // Phase 1: Protein
    'kyckling', 'anka', 'kalkon', 'fågel', 'nötkött', 'fläskkött', 'lamm',
    'vilt',
    'fisk', 'lax', 'torsk', 'sill', 'skaldjur', 'räkor',
    'tofu', 'tempeh', 'seitan', 'quorn', 'växtfärs', 'bönprotein', 'oumph',
    'växtprotein', 'baljväxter', 'ägg',
    // Phase 1: Carb/base
    'pastabaserad', 'risbaserad', 'potatisbaserad', 'nudelbaserad',
    'brödbaserad', 'fullkorn',
    // Phase 1: Cooking method
    'ugnsbakad', 'stekt', 'grillad', 'kokt', 'ångkokt', 'pocherad',
    'friterad', 'airfryer', 'slow-cooker', 'tryckkokare', 'sous-vide',
    'wokad', 'microugn', 'rökt',
    // Phase 1: Dish type
    'soppa', 'sallad', 'gryta', 'gratäng', 'curry', 'smörgås', 'hamburgare',
    'pizza', 'taco', 'bowl', 'paj', 'kaka', 'bröd', 'köttbullar', 'omelett',
    'pannkaka', 'våffla', 'smoothie', 'wok', 'dipp', 'sås',
    // Phase 2: Derived
    'pasta-dish', 'rice-dish', 'noodle-dish', 'potato-dish', 'bread-dish',
    'stark', 'mild', 'få-ingredienser', 'rå', 'one-pot', 'plåtmat',
    'no-bake', 'långkokt', 'över-natten', 'dessert', 'frukost', 'fika',
    'dryck',
    // Phase 3: Complex
    'enkel', 'medel', 'avancerad', 'krämig', 'krispig', 'ostig', 'kall-rätt',
    'varm-rätt', 'proteinrik', 'fiberrik', 'grönsaksrik', 'kryddrik',
    'barnvänlig', 'frysbar', 'meal-prep', 'storkok', 'klimatsmart',
    'budgetvänlig',
    // Phase 4: Mood & occasion
    'vardagsmiddag', 'helgmat', 'middagsbjudning', 'snabblagat',
    'fredagsmys', 'söndagsmiddag',
    'comfort-food', 'värmande', 'fräsch', 'lyxig',
    'jul', 'lucia', 'påsk', 'midsommar', 'kräftskiva', 'nyår',
    'vår', 'sommar', 'höst', 'vinter',
  };

  static Set<String> _buildReservedSet() {
    final reserved = <String>{};

    // Dietary tags
    for (final entry in DietaryConfig.all) {
      reserved.add(entry.tagSv.toLowerCase());
    }

    // Allergen tags
    for (final entry in AllergenConfig.all) {
      reserved.add(entry.containsTag.toLowerCase());
      if (entry.freeTag != null) {
        reserved.add(entry.freeTag!.toLowerCase());
      }
    }

    // Auto-generated tags from Phases 1-4
    reserved.addAll(_autoGeneratedTags);

    // Phase 5: Cuisine — derived from CuisineConfig to stay in sync
    reserved.addAll(CuisineConfig.cuisines.map((c) => c.tag));

    return reserved;
  }

  /// Check if a tag name conflicts with system tags.
  /// Comparison is case-insensitive.
  static bool isReserved(String tagName) {
    return all.contains(tagName.toLowerCase());
  }

  /// Validates a tag name, returning error message if invalid.
  /// Returns null if valid.
  static String? validateTagName(String tagName) {
    final trimmed = tagName.trim();
    if (trimmed.isEmpty) {
      return AppLocale.current.tagValidationEmpty;
    }
    if (trimmed.length < 2) {
      return AppLocale.current.tagValidationTooShort;
    }
    if (trimmed.length > 50) {
      return AppLocale.current.tagValidationTooLong;
    }
    if (isReserved(trimmed)) {
      return AppLocale.current.tagValidationReserved;
    }
    return null;
  }
}
