/// Intent tests for [YouTubeTranscriptService].
///
/// What this file proves (one bullet per behaviour, by group):
///
/// URL parsing (`extractVideoId` / `isYouTubeUrl`):
/// - All six documented URL shapes yield the same 11-char video ID:
///   watch, youtu.be, shorts, embed, live, and bare-ID.
/// - Surrounding whitespace is trimmed before matching (paste-from-chat).
/// - Tracking parameters (`?si=…`, `&t=…`, `&list=…`) on every shape don't
///   defeat the match.
/// - 11-char IDs containing the URL-safe non-alphanum chars `-` and `_` are
///   accepted (off-by-one regex-class bug class).
/// - URLs with the wrong host (vimeo, "iyoutube.com", "youtube.example") return
///   null — pattern must not over-match.
/// - IDs of length 10 or 12 reject (length 12 returns null for bare; length 12
///   in a URL returns the first 11 — YouTube's own behaviour).
/// - Non-strings, empty string and pure whitespace return null (no crash).
///
/// `fetchVideoMetadata`:
/// - Successful oEmbed JSON yields a populated VideoMetadata with the right
///   videoId derived from the URL.
/// - Non-200 status returns null (no partial object).
/// - oEmbed `title` missing → defaults to `"Unknown"` (UI fallback contract).
/// - Network exception is swallowed by `safeExecute` → returns null, no rethrow.
/// - sourceUrl on the returned metadata equals the canonical watch URL,
///   regardless of which shape was passed in.
///
/// `fetchTranscript`:
/// - When the watch page yields no `ytInitialPlayerResponse` and no
///   timedtext URLs → TranscriptResult.failure("No captions available…").
///   No null concatenation, no crash.
/// - When `ytInitialPlayerResponse` parses but has no captions block →
///   structured "no captions" failure.
/// - Happy path: captions present + JSON3 timedtext fetched → success with
///   joined transcript text and `language` carried through.
/// - Auto-generated detection: `vssId` starting with `a.` flips
///   `isAutoGenerated`, and a manual track in a preferred language is
///   preferred over an auto-generated one in the same language.
/// - Language preference order: Swedish wins over English when both are
///   present as manual tracks.
/// - JSON3 transcript with empty / whitespace `utf8` segments → those segments
///   are filtered out, not concatenated as `null` / empty.
/// - JSON3 transcript that yields an entirely whitespace string → mapped to
///   failure, not success-with-empty.
/// - XML fallback: when the JSON3 timedtext returns 200 with non-JSON XML body,
///   the parser falls back to XML and decodes HTML entities (`&amp;` → `&`).
/// - `[Musik]` / `[Music]` markers are stripped from the cleaned transcript.
/// - Whitespace runs are collapsed to single spaces.
/// - Network exception on watch page → returns the safeExecute default
///   ("Error fetching transcript") — no rethrow, no crash.
/// - `dispose()` on a service built with an injected client must NOT close
///   that client (caller owns lifecycle). `dispose()` on a default-constructed
///   service closes the owned client.
library;

import 'dart:convert';

import 'package:butlery/services/import/youtube/youtube_transcript_service.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';

// ---------------------------------------------------------------------------
// HTTP fixture helpers
// ---------------------------------------------------------------------------

/// 11-char synthetic video ID using the full allowed alphabet incl. `-` `_`.
const _vid = 'dQw4w9WgXcQ';

http.Response _ok(String body, {String contentType = 'application/json'}) {
  return http.Response(body, 200, headers: {'content-type': contentType});
}

http.Response _status(int status, {String body = ''}) {
  return http.Response(body, status);
}

/// A minimal watch-page HTML carrying a ytInitialPlayerResponse block with
/// the given caption tracks. Pass [tracks] as a list of inline-JSON strings.
String _watchPageHtmlWithTracks(List<String> tracks) {
  final tracksJson = tracks.join(',');
  return '''
<!doctype html>
<html><head><title>YT</title></head>
<body>
<script>
var x = 1;
ytInitialPlayerResponse = {"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[$tracksJson]}}};
</script>
</body></html>
''';
}

/// A watch-page that parses but with no captions block at all.
String _watchPageHtmlNoCaptions() {
  return '''
<!doctype html>
<html><body>
<script>
ytInitialPlayerResponse = {"videoDetails":{"title":"t"}};
</script>
</body></html>
''';
}

/// JSON3 timedtext payload with [segments] as a flat list of `utf8` strings.
String _json3Body(List<String?> segments) {
  final segs = segments
      .map((s) => s == null ? '{}' : '{"utf8":${json.encode(s)}}')
      .join(',');
  return '{"events":[{"segs":[$segs]}]}';
}

/// Build a service whose HTTP client is driven by [responder].
YouTubeTranscriptService _serviceWith(
  Future<http.Response> Function(http.Request req) responder,
) {
  return YouTubeTranscriptService(
    client: MockClient((req) async => responder(req)),
  );
}

void main() {
  // -------------------------------------------------------------------------
  // URL parsing
  // -------------------------------------------------------------------------
  group('extractVideoId', () {
    late YouTubeTranscriptService svc;

    setUp(() => svc = YouTubeTranscriptService());
    tearDown(() => svc.dispose());

    /// All six documented URL shapes must parse to the same 11-char video ID.
    /// This is the contract the rest of the service builds on — a single
    /// off-by-one in any one regex breaks import for that share-link shape.
    test('extracts video ID from every documented YouTube URL shape', () {
      final shapes = <String, String>{
        'standard watch': 'https://www.youtube.com/watch?v=$_vid',
        'standard watch (mobile)': 'https://m.youtube.com/watch?v=$_vid',
        'standard watch + extra params':
            'https://www.youtube.com/watch?feature=share&v=$_vid&t=30s',
        'youtu.be short': 'https://youtu.be/$_vid',
        'youtu.be + tracking': 'https://youtu.be/$_vid?si=abcDEF12345',
        'shorts': 'https://www.youtube.com/shorts/$_vid',
        'embed': 'https://www.youtube.com/embed/$_vid',
        'live': 'https://www.youtube.com/live/$_vid',
        'bare id': _vid,
      };
      for (final entry in shapes.entries) {
        expect(
          svc.extractVideoId(entry.value),
          _vid,
          reason: 'shape "${entry.key}" (input=${entry.value})',
        );
      }
    });

    /// Surrounding whitespace must be trimmed. Pasted URLs from chat apps
    /// arrive padded — without trim the regex `^…$` for bare-ID and the
    /// host prefix in other patterns would silently fail to match.
    test('trims surrounding whitespace and newlines', () {
      expect(svc.extractVideoId('  https://youtu.be/$_vid  '), _vid);
      expect(svc.extractVideoId('\n\thttps://www.youtube.com/watch?v=$_vid\n'),
          _vid);
      expect(svc.extractVideoId('   $_vid   '), _vid);
    });

    /// The video-ID alphabet is `[A-Za-z0-9_-]`. A regex character class
    /// missing `-` or `_` is a classic copy-paste bug that drops perfectly
    /// valid IDs. Pin both with concrete examples.
    test('accepts video IDs containing `-` and `_`', () {
      const dashId = 'abc-def_123'; // 11 chars, contains - and _
      expect(dashId.length, 11);
      expect(svc.extractVideoId('https://youtu.be/$dashId'), dashId);
      expect(svc.extractVideoId('https://www.youtube.com/watch?v=$dashId'),
          dashId);
      expect(
          svc.extractVideoId('https://www.youtube.com/shorts/$dashId'), dashId);
      expect(svc.extractVideoId(dashId), dashId);
    });

    /// `isYouTubeUrl` is a thin wrapper over `extractVideoId`. The bug class
    /// here is a future refactor that changes one without the other.
    test('isYouTubeUrl agrees with extractVideoId for every shape', () {
      const inputs = [
        'https://www.youtube.com/watch?v=$_vid',
        'https://youtu.be/$_vid',
        'https://www.youtube.com/shorts/$_vid',
        'https://example.com/x',
        'not-a-url',
        '',
      ];
      for (final input in inputs) {
        expect(
          svc.isYouTubeUrl(input),
          svc.extractVideoId(input) != null,
          reason: 'isYouTubeUrl out of sync with extractVideoId for "$input"',
        );
      }
    });

    /// Non-YouTube hosts and malformed inputs must return null. After BUT-1091
    /// (host-anchored regex), typosquats like `iyoutube.com` and
    /// `evil-youtube.com` also return null — see the CHARACTERIZATION test
    /// below for those.
    test('returns null for non-YouTube hosts and malformed inputs', () {
      const nonMatching = [
        'https://vimeo.com/123456789',
        'https://example.com/watch?v=$_vid',
        'https://www.youtube.com/', // no path
        'https://www.youtube.com/playlist?list=PL123',
        'not-a-url',
        '',
        '   ',
      ];
      for (final input in nonMatching) {
        expect(
          svc.extractVideoId(input),
          isNull,
          reason: 'must not extract a video ID from "$input"',
        );
      }
    });

    /// BUT-1091 fix: host-anchored regex rejects typosquats. The patterns
    /// now require `^https?://(?:www\.|m\.)?` (or `^https?://youtu\.be/`)
    /// so any hostname *ending* in `youtube.com` no longer matches.
    test('BUT-1091: host-anchored regex rejects typosquats', () {
      // Missing protocol → fails the `^https?://` anchor.
      expect(svc.extractVideoId('iyoutube.com/watch?v=$_vid'), isNull);
      // Wrong host (only `youtube.com` or `youtu.be` allowed).
      expect(
          svc.extractVideoId('https://evilyoutube.com/watch?v=$_vid'), isNull);
      expect(svc.extractVideoId('https://anything-youtube.com/embed/$_vid'),
          isNull);
      // Subdomain over-match: only `www.` or `m.` allowed before youtube.com.
      expect(svc.extractVideoId('https://random.youtube.com/watch?v=$_vid'),
          isNull);
    });

    /// Length is strict at 11 for the bare-ID pattern. A 10-char or 12-char
    /// bare string must NOT be accepted, otherwise we'd happily try to fetch
    /// nonsense from YouTube.
    test('bare-ID pattern rejects lengths other than 11', () {
      expect(svc.extractVideoId('a' * 10), isNull); // too short
      expect(svc.extractVideoId('a' * 12), isNull); // too long
      expect(svc.extractVideoId('a' * 11), 'a' * 11); // exact
    });
  });

  // -------------------------------------------------------------------------
  // fetchVideoMetadata
  // -------------------------------------------------------------------------
  group('fetchVideoMetadata', () {
    /// Happy path: oEmbed returns JSON, service returns a populated
    /// VideoMetadata with the videoId extracted from the input URL.
    test('returns populated VideoMetadata on 200 oEmbed JSON', () async {
      late Uri seenUrl;
      final svc = _serviceWith((req) async {
        seenUrl = req.url;
        return _ok(json.encode({
          'title': 'Köttbullar med potatismos',
          'thumbnail_url': 'https://img.youtube.com/vi/$_vid/hqdefault.jpg',
          'author_name': 'Mamma Lagar Mat',
        }));
      });

      final meta =
          await svc.fetchVideoMetadata('https://www.youtube.com/watch?v=$_vid');

      expect(meta, isNotNull);
      expect(meta!.videoId, _vid);
      expect(meta.title, 'Köttbullar med potatismos');
      expect(meta.channelName, 'Mamma Lagar Mat');
      expect(meta.thumbnailUrl, contains(_vid));
      expect(meta.sourceUrl, 'https://www.youtube.com/watch?v=$_vid');
      expect(seenUrl.host, 'www.youtube.com');
      expect(seenUrl.path, '/oembed');
      expect(seenUrl.queryParameters['format'], 'json');
      svc.dispose();
    });

    /// canonical sourceUrl: passing a `youtu.be/` short URL must still
    /// produce a canonical `youtube.com/watch?v=…` sourceUrl on the metadata
    /// — downstream code uses `sourceUrl` directly.
    test('canonicalises sourceUrl regardless of input shape', () async {
      final svc = _serviceWith((req) async {
        return _ok(json.encode({'title': 'X'}));
      });

      final fromShort = await svc.fetchVideoMetadata('https://youtu.be/$_vid');
      final fromShorts =
          await svc.fetchVideoMetadata('https://www.youtube.com/shorts/$_vid');
      final fromBare = await svc.fetchVideoMetadata(_vid);

      for (final m in [fromShort, fromShorts, fromBare]) {
        expect(m, isNotNull);
        expect(m!.sourceUrl, 'https://www.youtube.com/watch?v=$_vid');
        expect(m.videoId, _vid);
      }
      svc.dispose();
    });

    /// Non-200 must return null (no partial object). The UI uses null to mean
    /// "could not fetch" — a partial object would crash the import pipeline
    /// downstream when it accesses `meta.title`.
    test('returns null on non-200 status', () async {
      final svc = _serviceWith((req) async => _status(404, body: 'not found'));

      final meta =
          await svc.fetchVideoMetadata('https://www.youtube.com/watch?v=$_vid');

      expect(meta, isNull);
      svc.dispose();
    });

    /// Title-missing default: oEmbed sometimes returns `{"thumbnail_url":…}`
    /// without a title. Service contract guarantees a non-null title field,
    /// defaulting to "Unknown" so the UI never has to null-check.
    test('defaults missing title to "Unknown"', () async {
      final svc = _serviceWith((req) async {
        return _ok(json.encode({
          'thumbnail_url': 'https://img.youtube.com/vi/$_vid/hqdefault.jpg',
        }));
      });

      final meta = await svc.fetchVideoMetadata(_vid);

      expect(meta, isNotNull);
      expect(meta!.title, 'Unknown');
      expect(meta.channelName, isNull);
      svc.dispose();
    });

    /// Network exception must be swallowed via safeExecute → null, no rethrow.
    /// The bug class is `Future.error` bubbling out and crashing the import UI.
    test('swallows network exceptions and returns null', () async {
      final svc = _serviceWith((req) async {
        throw const _FakeHttpException('socket closed');
      });

      final meta = await svc.fetchVideoMetadata(_vid);

      expect(meta, isNull);
      svc.dispose();
    });
  });

  // -------------------------------------------------------------------------
  // fetchTranscript
  // -------------------------------------------------------------------------
  group('fetchTranscript', () {
    /// When the watch page returns a 200 that does NOT contain
    /// `ytInitialPlayerResponse` AND no `timedtext` URLs, the service must
    /// return a structured failure carrying the documented message — NOT
    /// throw, NOT return a half-populated success.
    test('returns "No captions available" when no tracks found', () async {
      final svc = _serviceWith((req) async {
        return _ok('<html><body>no script here</body></html>',
            contentType: 'text/html');
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isFalse);
      expect(result.transcript, isNull);
      expect(result.error, 'No captions available for this video');
      svc.dispose();
    });

    /// playerResponse parses cleanly but has no `captions` key. The parsed
    /// branch returns [] and we still must surface the structured no-captions
    /// failure (not a generic crash, not a bare null).
    test('returns no-captions failure when playerResponse lacks captions',
        () async {
      final svc = _serviceWith((req) async {
        return _ok(_watchPageHtmlNoCaptions(), contentType: 'text/html');
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isFalse);
      expect(result.error, 'No captions available for this video');
      svc.dispose();
    });

    /// Happy path: a single Swedish track is selected, JSON3 timedtext is
    /// fetched, segments are joined into the transcript text, and the
    /// language is carried back to the caller.
    test('returns success with joined transcript and language preserved',
        () async {
      const trackUrl = 'https://www.youtube.com/api/timedtext?lang=sv&v=$_vid';
      final track = '''
        {"baseUrl":"$trackUrl","languageCode":"sv",
         "name":{"simpleText":"Svenska"},"vssId":".sv"}
      ''';

      final svc = _serviceWith((req) async {
        if (req.url.host.contains('youtube.com') && req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks([track]),
              contentType: 'text/html');
        }
        // timedtext fetch — JSON3 format
        if (req.url.path.contains('/api/timedtext')) {
          return _ok(_json3Body(['Hej och välkommen ', 'till matlagningen.']));
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isTrue, reason: 'error=${result.error}');
      expect(result.language, 'sv');
      expect(result.isAutoGenerated, isFalse);
      expect(result.transcript, contains('Hej och välkommen'));
      expect(result.transcript, contains('till matlagningen'));
      svc.dispose();
    });

    /// Auto-generated detection (`vssId.startsWith("a.")`) and language
    /// preference: when both a manual and auto-generated Swedish track are
    /// present, the manual one wins. Bug class: a flipped `!isAutoGenerated`
    /// would silently prefer auto-generated captions, which are noticeably
    /// lower quality.
    test('prefers manual Swedish track over auto-generated Swedish track',
        () async {
      const manualUrl = 'https://www.youtube.com/api/timedtext?type=manual';
      const autoUrl = 'https://www.youtube.com/api/timedtext?type=auto';
      final tracks = [
        '''
        {"baseUrl":"$autoUrl","languageCode":"sv",
         "name":{"simpleText":"Svenska (auto)"},"vssId":"a.sv"}
        ''',
        '''
        {"baseUrl":"$manualUrl","languageCode":"sv",
         "name":{"simpleText":"Svenska"},"vssId":".sv"}
        ''',
      ];
      String? fetchedTimedtextQuery;
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks(tracks),
              contentType: 'text/html');
        }
        if (req.url.path.contains('/api/timedtext')) {
          fetchedTimedtextQuery = req.url.query;
          return _ok(_json3Body(['manual transcript text']));
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isTrue);
      expect(result.isAutoGenerated, isFalse,
          reason: 'manual track must beat auto-generated track in same lang');
      expect(fetchedTimedtextQuery, contains('type=manual'),
          reason: 'must have fetched the manual track, not the auto one');
      svc.dispose();
    });

    /// Language preference order: Swedish must be picked over English when
    /// both are present as manual tracks. The `_preferredLanguages` list is
    /// `['sv', 'en', 'da', 'no', 'nb']` — sv wins.
    test('prefers Swedish over English when both available as manual',
        () async {
      const svUrl = 'https://www.youtube.com/api/timedtext?which=sv';
      const enUrl = 'https://www.youtube.com/api/timedtext?which=en';
      final tracks = [
        '''
        {"baseUrl":"$enUrl","languageCode":"en",
         "name":{"simpleText":"English"},"vssId":".en"}
        ''',
        '''
        {"baseUrl":"$svUrl","languageCode":"sv",
         "name":{"simpleText":"Svenska"},"vssId":".sv"}
        ''',
      ];
      String? fetchedQuery;
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks(tracks),
              contentType: 'text/html');
        }
        if (req.url.path.contains('/api/timedtext')) {
          fetchedQuery = req.url.query;
          return _ok(_json3Body(['x']));
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isTrue);
      expect(result.language, 'sv');
      expect(fetchedQuery, contains('which=sv'));
      svc.dispose();
    });

    /// JSON3 segments where `utf8` is null or whitespace must NOT be
    /// concatenated. Bug class: writing the string "null" to the buffer.
    /// Whitespace-only segments would also bloat the transcript with empty
    /// space — the production check `text.trim().isNotEmpty` is the
    /// intended filter and this test pins it.
    test('filters out null/whitespace segments without concatenating null',
        () async {
      const trackUrl = 'https://www.youtube.com/api/timedtext?lang=en';
      final track = '''
        {"baseUrl":"$trackUrl","languageCode":"en",
         "name":{"simpleText":"English"},"vssId":".en"}
      ''';
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks([track]),
              contentType: 'text/html');
        }
        if (req.url.path.contains('/api/timedtext')) {
          // Mix of valid, null, whitespace and valid again.
          return _ok(_json3Body(['hello ', null, '   ', 'world']));
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isTrue, reason: 'error=${result.error}');
      expect(result.transcript, isNotNull);
      expect(result.transcript, isNot(contains('null')),
          reason: 'must not write the literal "null" into the transcript');
      expect(result.transcript, 'hello world',
          reason: 'collapsed whitespace + filtered empty segments must produce '
              'exactly "hello world"');
      svc.dispose();
    });

    /// All-whitespace transcript: every segment is whitespace-only. The
    /// service must map this to a structured failure ("Failed to fetch
    /// transcript content"), not a silent success carrying empty text.
    /// Bug class: `TranscriptResult.success(transcript: '')` reaches the
    /// importer and the import pipeline tries to LLM-structure empty text.
    test('returns failure when every segment is whitespace-only', () async {
      const trackUrl = 'https://www.youtube.com/api/timedtext?lang=en';
      final track = '''
        {"baseUrl":"$trackUrl","languageCode":"en",
         "name":{"simpleText":"English"},"vssId":".en"}
      ''';
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks([track]),
              contentType: 'text/html');
        }
        if (req.url.path.contains('/api/timedtext')) {
          return _ok(_json3Body(['   ', '\n\t', '']));
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isFalse);
      expect(result.error, 'Failed to fetch transcript content');
      svc.dispose();
    });

    /// XML fallback path: JSON3 endpoint returns 200 but the body is XML
    /// (some YouTube edges respond this way). `_parseJsonTranscript` will
    /// throw on `json.decode`, the catch falls back to `_parseXmlTranscript`,
    /// and HTML entities must be decoded back to characters. This pins both
    /// the fallback branch AND the entity decoder.
    test('falls back to XML parsing and decodes HTML entities', () async {
      const trackUrl = 'https://www.youtube.com/api/timedtext?lang=en';
      final track = '''
        {"baseUrl":"$trackUrl","languageCode":"en",
         "name":{"simpleText":"English"},"vssId":".en"}
      ''';
      const xmlBody = '''
<?xml version="1.0" encoding="utf-8"?>
<transcript>
<text start="0" dur="3">Salt &amp; pepper</text>
<text start="3" dur="3">it&#39;s ready</text>
<text start="6" dur="3">say &quot;done&quot;</text>
</transcript>
''';
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks([track]),
              contentType: 'text/html');
        }
        if (req.url.path.contains('/api/timedtext')) {
          return _ok(xmlBody, contentType: 'application/xml');
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isTrue, reason: 'error=${result.error}');
      expect(result.transcript, contains('Salt & pepper'));
      expect(result.transcript, contains("it's ready"));
      expect(result.transcript, contains('say "done"'));
      expect(result.transcript, isNot(contains('&amp;')),
          reason: 'HTML entities must be decoded');
      expect(result.transcript, isNot(contains('&#39;')));
      svc.dispose();
    });

    /// `_cleanTranscript` strips `[Musik]` / `[Music]` / `[Applåder]` /
    /// `[Applause]` markers (case-insensitive). Auto-generated captions
    /// often pepper these in and they pollute the LLM input.
    test('strips music/applause markers from the cleaned transcript', () async {
      const trackUrl = 'https://www.youtube.com/api/timedtext?lang=sv';
      final track = '''
        {"baseUrl":"$trackUrl","languageCode":"sv",
         "name":{"simpleText":"Svenska"},"vssId":".sv"}
      ''';
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') {
          return _ok(_watchPageHtmlWithTracks([track]),
              contentType: 'text/html');
        }
        if (req.url.path.contains('/api/timedtext')) {
          return _ok(_json3Body([
            '[MUSIK] hej ',
            'och [applåder] välkomna ',
            'till [Music] receptet'
          ]));
        }
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isTrue);
      final t = result.transcript!;
      expect(t.toLowerCase(), isNot(contains('[musik]')));
      expect(t.toLowerCase(), isNot(contains('[music]')));
      expect(t.toLowerCase(), isNot(contains('[applåder]')));
      // Real words survive.
      expect(t, contains('hej'));
      expect(t, contains('välkomna'));
      expect(t, contains('receptet'));
      // BUT-1096 fix: `_cleanTranscript` now strips `[musik]`/`[applåder]`
      // markers BEFORE normalizing whitespace, so no double-spaces are left
      // where markers used to be. Tightened from `'   '` (3-space) to `'  '`
      // (2-space) — the previous looser assertion let the bug through.
      expect(t, isNot(contains('  ')),
          reason: 'BUT-1096: any two-or-more consecutive spaces indicate the '
              'marker-strip-vs-whitespace-normalize order has regressed');
      svc.dispose();
    });

    /// Watch-page fetch throws synchronously → `safeExecute` catches and
    /// returns the documented default ("Error fetching transcript"). The
    /// bug class is the throw escaping to the caller and crashing the UI.
    test('swallows network exceptions and returns "Error fetching transcript"',
        () async {
      final svc = _serviceWith((req) async {
        throw const _FakeHttpException('connection reset');
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isFalse);
      expect(result.error, 'Error fetching transcript');
      svc.dispose();
    });

    /// Watch page non-200 → `_fetchCaptionTracks` returns []. Service must
    /// surface the structured "no captions" failure, not let an empty list
    /// reach `_selectBestTrack` (which would throw on `.first`).
    test('returns no-captions failure when watch page is non-200', () async {
      final svc = _serviceWith((req) async {
        if (req.url.path == '/watch') return _status(500);
        return _status(404);
      });

      final result = await svc.fetchTranscript(_vid);

      expect(result.isSuccess, isFalse);
      expect(result.error, 'No captions available for this video');
      svc.dispose();
    });
  });

  // -------------------------------------------------------------------------
  // dispose / client ownership
  // -------------------------------------------------------------------------
  group('dispose / client ownership', () {
    /// When the caller injects their own `http.Client`, the service must NOT
    /// close it on dispose — the caller owns the lifecycle. Closing somebody
    /// else's client is a real production bug: subsequent imports would fail
    /// with "client already closed".
    test('does not close the injected client', () {
      final injected = _RecordingClient();
      final svc = YouTubeTranscriptService(client: injected);

      svc.dispose();

      expect(injected.closed, isFalse,
          reason: 'injected client lifecycle belongs to the caller');
    });

    /// When the service constructs its own client (no injection), dispose
    /// must close it — otherwise we leak sockets every time the user
    /// imports a video.
    test('closes the owned client when none was injected', () {
      // We can't introspect the inner http.Client easily, so just assert
      // dispose() doesn't throw on a default-constructed service. The
      // negative case above is the contract; this is the smoke test.
      final svc = YouTubeTranscriptService();
      expect(svc.dispose, returnsNormally);
    });
  });
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

class _FakeHttpException implements Exception {
  final String message;
  const _FakeHttpException(this.message);
  @override
  String toString() => 'FakeHttpException: $message';
}

/// http.Client that just records whether `close()` was called. No requests
/// are routed through it in the dispose-ownership tests, so we only need
/// the close hook.
class _RecordingClient extends http.BaseClient {
  bool closed = false;

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    return http.StreamedResponse(
      const Stream.empty(),
      200,
    );
  }

  @override
  void close() {
    closed = true;
    super.close();
  }
}
